MSBasic - Applesoft BASIC Interpreter: InteractiveMode Class Reference
InteractiveMode Class Reference
Interactive REPL for Applesoft BASIC.
#include <interactive.h>
Public Member Functions
InteractiveMode (const GraphicsConfig &config=GraphicsConfig())
Construct interactive mode with graphics configuration.
void run ()
Enter REPL loop.
Detailed Description
Interactive REPL for Applesoft BASIC.
Provides command-line interface for direct interaction with the interpreter. Accepts immediate commands and program line entry.
Usage:
InteractiveMode repl;
repl.run();  // Enters REPL until user exits
Definition at line 44 of file interactive.h.
Constructor & Destructor Documentation
InteractiveMode()
InteractiveMode::InteractiveMode (const GraphicsConfig & config = GraphicsConfig())
Construct interactive mode with graphics configuration.
Construct an InteractiveMode instance.
Parameters
config Graphics configuration (default: graphics enabled)
config Graphics configuration to use for the interpreter
Definition at line 27 of file interactive.cpp.
Member Function Documentation
run()
void InteractiveMode::run ()
Enter REPL loop.
Run the interactive REPL loop.
Displays banner, then repeatedly prompts for input and executes commands until user exits (Ctrl+C or EXIT command).
Displays the banner, creates an interpreter, and enters the main loop:
Display prompt
Read input line
Execute line (immediate command or program line entry)
Display errors with "?" prefix
Repeat until EOF (Ctrl+D on Unix, Ctrl+Z on Windows)
Definition at line 74 of file interactive.cpp.
References Interpreter::executeImmediate().
Referenced by Interpreter::interactive(), and main().
The documentation for this class was generated from the following files:
src/interactive.h
src/interactive.cpp