MSBasic - Applesoft BASIC Interpreter: FileManager Class Reference
FileManager Class Reference
Singleton managing open file handles for BASIC file I/O.
#include <filesystem.h>
Public Member Functions
int openFile (const std::string &filename, FileAccessMode mode)
Open file and return handle (OPEN)
void closeFile (int handle)
Close file by handle (CLOSE)
void closeFile (const std::string &filename)
Close file by filename (CLOSE)
void closeAllFiles ()
Close all open files.
bool readLine (int handle, std::string &line)
Read line from file (READ#)
bool writeLine (int handle, const std::string &line)
Write line to file (WRITE#)
void setPosition (int handle, size_t position)
Set file position (seek)
size_t getPosition (int handle)
Get current file position.
void flushFile (int handle)
Flush buffered writes to disk (FLUSH#)
void flushFile (const std::string &filename)
Flush buffered writes by filename (FLUSH)
bool lockFile (const std::string &filename)
Lock file (LOCK)
bool unlockFile (const std::string &filename)
Unlock file (UNLOCK)
bool createFile (const std::string &filename)
Create empty file (CREATE)
std::vector< uint8_t > loadBinaryFile (const std::string &filename, int address=-1)
Load binary file (BLOAD)
void saveBinaryFile (const std::string &filename, const std::vector< uint8_t > &data, int address, int length)
Save binary file (BSAVE)
Static Public Member Functions
static FileManager & getInstance ()
Get FileManager singleton instance.
Detailed Description
Singleton managing open file handles for BASIC file I/O.
Provides ProDOS-style file operations with integer handles. Maintains open file state and coordinates file access across BASIC commands.
Thread safety: Not thread-safe. Single-threaded use only.
Definition at line 161 of file filesystem.h.
Member Function Documentation
closeAllFiles()
void FileManager::closeAllFiles ()
Close all open files.
Called on program termination or NEW command.
Used by interpreter lifecycle operations like NEW/CLEAR to ensure file buffers are released.
Definition at line 335 of file filesystem.cpp.
Referenced by Interpreter::closeAllFiles().
closeFile() [1/2]
void FileManager::closeFile (const std::string & filename)
Close file by filename (CLOSE)
Close an open file by filename.
Parameters
filename File path
Convenience wrapper over handle-based close.
Parameters
filename Path used when opening the file
Definition at line 322 of file filesystem.cpp.
References closeFile().
closeFile() [2/2]
void FileManager::closeFile (int handle)
Close file by handle (CLOSE)
Close an open file by handle.
Parameters
handle File handle from openFile()
Safe to call with an unknown handle: no action is taken.
Parameters
handle Handle returned by openFile()
Definition at line 304 of file filesystem.cpp.
Referenced by closeFile(), and Interpreter::closeFile().
createFile()
bool FileManager::createFile (const std::string & filename)
Create empty file (CREATE)
Create an empty file.
Parameters
filename File path
Returns
true if successful
Creates/truncates a file by opening it for output.
Parameters
filename Path to create
Returns
true on success, false on failure
Definition at line 524 of file filesystem.cpp.
flushFile() [1/2]
void FileManager::flushFile (const std::string & filename)
Flush buffered writes by filename (FLUSH)
Flush buffered writes by filename.
Parameters
filename File path
Convenience wrapper that flushes the file if it is currently open.
Parameters
filename Path used when opening the file
Definition at line 477 of file filesystem.cpp.
References flushFile().
flushFile() [2/2]
void FileManager::flushFile (int handle)
Flush buffered writes to disk (FLUSH#)
Flush buffered writes to disk.
Parameters
handle File handle
Safe to call for read-only files; flush() is a no-op in that case.
Parameters
handle File handle
Definition at line 463 of file filesystem.cpp.
References FileHandle::isOpen, and FileHandle::stream.
Referenced by flushFile(), and Interpreter::flushFile().
getInstance()
FileManager & FileManager::getInstance () static
Get FileManager singleton instance.
Get the FileManager singleton instance.
Returns
Reference to FileManager
Returns the global FileManager instance used to manage open files. Uses function-local static initialization to ensure thread-safe construction.
Returns
Reference to FileManager singleton
Definition at line 236 of file filesystem.cpp.
Referenced by Interpreter::appendFile(), Interpreter::bloadFile(), Interpreter::bsaveFile(), Interpreter::closeAllFiles(), Interpreter::closeFile(), Interpreter::createFile(), Interpreter::flushFile(), Interpreter::lockFile(), Interpreter::openFile(), Interpreter::readFile(), Interpreter::unlockFile(), and Interpreter::writeFile().
getPosition()
size_t FileManager::getPosition (int handle)
Get current file position.
Get the cached byte position of an open file.
Parameters
handle File handle
Returns
Current byte offset
Returns the internal position tracking value, which is updated after successful reads/writes and after setPosition().
Parameters
handle File handle
Returns
Current byte offset
Exceptions
std::runtime_error if the file is not open
Definition at line 448 of file filesystem.cpp.
References FileHandle::isOpen, and FileHandle::position.
loadBinaryFile()
std::vector< uint8_t > FileManager::loadBinaryFile (const std::string & filename, int address = -1)
Load binary file (BLOAD)
Load a file as binary bytes.
Parameters
filename File path
address Memory address (-1 to ignore address in file)
Returns
Vector of bytes read from file
Exceptions
RuntimeError on I/O error
Loads binary data with optional address header matching ProDOS format.
Reads the full file contents into a byte vector.
Note: The optional address parameter is accepted for API compatibility with Applesoft BLOAD semantics, but this host implementation currently treats it as informational (the bytes are returned to the caller without being copied into an emulated 64K memory image).
Parameters
filename Path to binary file
address Optional load address (unused)
Returns
File content as bytes
Exceptions
std::runtime_error with "PATH NOT FOUND ERROR" if open fails
std::runtime_error with "I/O ERROR" if read fails
Definition at line 549 of file filesystem.cpp.
Referenced by Interpreter::bloadFile().
lockFile()
bool FileManager::lockFile (const std::string & filename)
Lock file (LOCK)
Lock a file (stub)
Parameters
filename File path
Returns
true if successful
ProDOS file locking simulation. Implementation is platform-specific.
ProDOS supports file locking. Host-platform locking semantics are platform-specific and are not yet fully implemented.
Current behavior:
Returns true if the file exists.
Does not change filesystem permissions.
Parameters
filename Path to file
Returns
true if file exists (stub), false otherwise
Definition at line 497 of file filesystem.cpp.
References fileExists().
openFile()
int FileManager::openFile (const std::string & filename, FileAccessMode mode)
Open file and return handle (OPEN)
Open a file and return an integer handle.
Parameters
filename File path
mode Access mode (READ/WRITE/APPEND)
Returns
File handle (positive integer)
Exceptions
RuntimeError if file cannot be opened
Provides ProDOS-like OPEN semantics via a stable integer handle. If the file is already open, the existing handle is returned. Mode mapping:
READ: open for binary input
WRITE: create/truncate for binary output
APPEND: open or create for binary append
Error behavior:
Throws "PATH NOT FOUND ERROR" if the file cannot be opened.
Parameters
filename Path to file
mode Desired access mode (READ, WRITE, APPEND)
Returns
Positive integer handle
Exceptions
std::runtime_error if the file cannot be opened
Definition at line 258 of file filesystem.cpp.
References APPEND, FileHandle::filename, FileHandle::isOpen, FileHandle::mode, FileHandle::position, READ, FileHandle::stream, and WRITE.
Referenced by Interpreter::appendFile(), Interpreter::openFile(), Interpreter::readFile(), and Interpreter::writeFile().
readLine()
bool FileManager::readLine (int handle, std::string & line)
Read line from file (READ#)
Read a line of text from an open file.
Parameters
handle File handle
line String to store line (output parameter)
Returns
true if line read successfully, false on EOF
Implements the core behavior used by ProDOS READ/INPUT-from-file flows. The function returns false on EOF.
Error behavior:
Throws "FILE NOT OPEN" if the handle is invalid.
Parameters
handle File handle
line Output line buffer
Returns
true if a line was read, false if EOF reached
Exceptions
std::runtime_error if the file is not open
Definition at line 376 of file filesystem.cpp.
References FileHandle::isOpen, FileHandle::position, and FileHandle::stream.
saveBinaryFile()
void FileManager::saveBinaryFile (const std::string & filename, const std::vector< uint8_t > & data, int address, int length)
Save binary file (BSAVE)
Save bytes to a binary file.
Parameters
filename File path
data Byte vector to write
address Starting memory address (for header)
length Number of bytes to write
Exceptions
RuntimeError on I/O error
Saves binary data with address header matching ProDOS format.
Writes the provided data to a file. The address and length arguments exist to match BSAVE-style calling conventions.
Current behavior:
Writes up to length bytes if length > 0, otherwise writes all data.
Does not write a ProDOS binary header (address/length). Higher-level callers may add headers if desired.
Parameters
filename Output path
data Bytes to write
address Intended address (unused)
length Intended length; if >0, caps bytes written
Exceptions
std::runtime_error with "I/O ERROR" on open/write failure
Definition at line 585 of file filesystem.cpp.
Referenced by Interpreter::bsaveFile().
setPosition()
void FileManager::setPosition (int handle, size_t position)
Set file position (seek)
Set the current byte position in an open file.
Parameters
handle File handle
position Byte offset from start of file
This is a low-level primitive used by future/random-access style commands. For READ mode this calls seekg(); for WRITE/APPEND it calls seekp().
Parameters
handle File handle
position Byte offset from beginning of file
Exceptions
std::runtime_error if the file is not open
Definition at line 424 of file filesystem.cpp.
References FileHandle::isOpen, FileHandle::mode, FileHandle::position, READ, and FileHandle::stream.
unlockFile()
bool FileManager::unlockFile (const std::string & filename)
Unlock file (UNLOCK)
Unlock a file (stub)
Parameters
filename File path
Returns
true if successful
See lockFile() for rationale. Currently this only checks existence.
Parameters
filename Path to file
Returns
true if file exists (stub), false otherwise
Definition at line 511 of file filesystem.cpp.
References fileExists().
writeLine()
bool FileManager::writeLine (int handle, const std::string & line)
Write line to file (WRITE#)
Write a line of text to an open file.
Parameters
handle File handle
line String to write (newline appended)
Returns
true if successful
Writes the provided line followed by a newline. Intended for simple sequential text output.
Error behavior:
Throws "FILE NOT OPEN" if the handle is invalid.
Parameters
handle File handle
line Text to write (newline appended)
Returns
true if write succeeded, false otherwise
Exceptions
std::runtime_error if the file is not open
Definition at line 403 of file filesystem.cpp.
References FileHandle::isOpen, FileHandle::position, and FileHandle::stream.
The documentation for this class was generated from the following files:
src/filesystem.h
src/filesystem.cpp