MSBasic - Applesoft BASIC Interpreter: Interpreter Class Reference
Interpreter Class Reference
Runtime execution engine for Applesoft BASIC programs.
#include <interpreter.h>
Public Member Functions
Interpreter (const GraphicsConfig &config=GraphicsConfig())
Construct interpreter with optional graphics configuration.
void loadProgram (const std::string &filename)
Load BASIC program from file.
void saveProgram (const std::string &filename)
Save BASIC program to text file.
void chainProgram (const std::string &filename)
Load and run program keeping current variables (CHAIN)
void dashProgram (const std::string &filename)
Run program without clearing variables (-)
void newProgram ()
Clear program and variables (NEW)
void listProgram (int startLine=-1, int endLine=-1)
List program lines to output (LIST)
void addLine (LineNumber lineNum, const std::string &text)
Add or replace program line.
void deleteLine (LineNumber lineNum)
Delete program line.
void run ()
Run program from first line (RUN)
void runFrom (LineNumber lineNum)
Run program from specified line (RUN n)
void executeImmediate (const std::string &line)
Execute single line without line number (immediate mode)
void interactive ()
Enter interactive REPL mode.
Variables & getVariables ()
Get variable storage for expression evaluation.
const GraphicsConfig & getGraphicsConfig () const
Get graphics configuration.
bool isGraphicsEnabled () const
Check if graphics mode is enabled.
LineNumber getCurrentLine () const
Get currently executing line number.
void gotoLine (LineNumber lineNum)
Jump to specified line (GOTO)
void gosub (LineNumber lineNum)
Call subroutine at line (GOSUB)
void returnFromGosub ()
Return from subroutine (RETURN)
void endProgram ()
End program execution (END)
void stop ()
Stop program execution (STOP)
void cont ()
Continue after STOP (CONT)
void htab (int col1)
Move cursor to column (HTAB)
void vtab (int row1)
Move cursor to row (VTAB)
void setInverse (bool on)
Enable inverse video mode (INVERSE)
void setFlash (bool on)
Enable flashing text mode (FLASH)
void setNormal ()
Return to normal video mode (NORMAL)
void printText (const std::string &text)
Output text string.
void printNewline ()
Output newline.
void printToNextZone ()
Tab to next print zone (14-character zones)
void resetOutputPosition ()
Reset output position to column 1.
void requireGraphicsMode () const
Verify graphics operations are allowed.
void setTextMode (TextMode mode)
Set text display mode (40 or 80 column)
TextMode getTextMode () const
bool isImmediateMode () const
void addDataValue (const Value &value)
Add a data value to the DATA cache.
Value readData ()
Read next value from DATA statements (READ implementation)
void restoreData (int line=-1)
Reset DATA pointer (RESTORE implementation)
void pushForLoop (const std::string &varName, double endValue, double stepValue, LineNumber returnLine)
Push a new FOR loop onto the loop stack (FOR statement)
bool isInForLoop (const std::string &varName)
Check if a variable is currently a FOR loop control variable.
void nextForLoop (const std::string &varName)
Process NEXT statement for loop iteration.
void setErrorHandler (LineNumber lineNum)
Set error handler line (ONERR GOTO implementation)
void handleError (const std::string &message)
Throw a runtime error.
void handleError (const std::string &message, int errorCode)
Throw a runtime error with ProDOS error code.
void resume ()
Resume execution after error (RESUME implementation)
void setTrace (bool on)
bool isTracing () const
void randomize (double seed)
Initialize random number generator (implicit RND behavior)
void setSpeedDelay (int delayMs)
Set statement execution delay (SPEED implementation)
int getSpeedDelay () const
void setOutputDevice (int slot)
Set output device slot (PR# implementation)
void setInputDevice (int slot)
Set input device slot (IN# implementation)
int getOutputDevice () const
int getInputDevice () const
void pushWhileLoop (std::shared_ptr< Expression > condition, LineNumber returnLine)
Push WHILE loop state onto stack (WHILE implementation helper)
void nextWhileLoop ()
Handle WEND statement (WHILE loop terminator)
void setHimem (int val)
void setLomem (int val)
int getHimem () const
int getLomem () const
void popGosub ()
Pop GOSUB return address from stack (POP implementation)
void catalog ()
List files in the current directory (CATALOG immediate command)
void catalogFiles (const std::string &path=".")
List files in specified directory (internal CATALOG helper)
void execFile (const std::string &filename)
Execute commands from a text file (EXEC implementation)
void deleteFile (const std::string &filename)
Delete a file (DELETE implementation)
void renameFile (const std::string &oldName, const std::string &newName)
Rename a file (RENAME implementation)
void showPrefix ()
Print the current prefix (PREFIX with no argument)
void setPrefix (const std::string &path)
Set or show directory prefix (internal PREFIX helper)
void changePrefix (const std::string &path)
Change directory prefix (PREFIX implementation)
void chainProgram (const std::string &filename, int startLine)
Load and run program with optional starting line (CHAIN implementation)
void dashRun (const std::string &filename)
void openFile (const std::string &filename, const std::string &options)
Open a file (OPEN implementation)
void closeFile (const std::string &filename)
Close an open file (CLOSE implementation)
void closeAllFiles ()
Close all open files.
void appendFile (const std::string &filename)
Open file in append mode (APPEND implementation)
void flushFile (const std::string &filename)
Flush buffered file data to disk (FLUSH implementation)
void positionFile (const std::string &filename, int record, int byte)
Position a file pointer (POSITION pn[,Rrecord][,Bbyte])
void readFile (const std::string &filename, int record, int byte)
Open file for reading with optional positioning (READ implementation)
void writeFile (const std::string &filename, int record)
Open file for writing with optional positioning (WRITE implementation)
void lockFile (const std::string &filename)
Lock a file (LOCK implementation)
void unlockFile (const std::string &filename)
Unlock a file (UNLOCK implementation)
void createFile (const std::string &filename, const std::string &options)
Create a new empty file (CREATE implementation)
void bloadFile (const std::string &filename, int address)
Load binary file into memory (BLOAD implementation)
void bsaveFile (const std::string &filename, int address, int length)
Save memory region to binary file (BSAVE implementation)
void brunFile (const std::string &filename, int address)
Load and execute binary file (BRUN implementation)
void callAddress (int address)
Execute machine language at address (CALL implementation)
void storeArray (const std::string &arrayName)
Save array to tape or disk (STORE implementation)
void recallArray (const std::string &arrayName)
Load array from tape or disk (RECALL implementation)
void storeVariables (const std::string &filename)
Save all variables to a file (extension of Applesoft functionality)
void restoreVariables (const std::string &filename)
Load all variables from a file (extension of Applesoft functionality)
void loadShapeTableFromFile (const std::string &filename)
Load shape table from file or tape (SHLOAD implementation)
void setTapeFile (const std::string &filename)
std::string getTapeFile () const
void changeTapeFile ()
void setTapeHotkey (const std::string &hotkey)
std::string getTapeHotkey () const
void clearState ()
Clear variables and control stacks (CLR command)
Detailed Description
Runtime execution engine for Applesoft BASIC programs.
The Interpreter executes parsed BASIC statements and manages all runtime state. It maintains program lines, variable storage, control flow stacks, and handles all I/O operations while preserving Applesoft BASIC semantics.
Program execution flow:
NEW: Clear program and variables
LOAD: Load program from disk (clears variables)
CHAIN: Load program keeping variables
-: Run program without clearing variables
RUN: Execute from first line or specified line
CONT: Continue after STOP
Control flow:
Maintains GOSUB return stack
Tracks FOR/NEXT loop state
Handles GOTO/GOSUB target line lookup
Supports ONERR error trapping with RESUME
Memory model:
LOMEM/HIMEM define variable storage bounds
PEEK/POKE/WAIT access memory addresses
Memory location 222 holds ProDOS error codes
Memory locations for text/graphics configuration
Graphics:
TEXT, GR (4048 low-res), HGR/HGR2 (280192 high-res)
COLOR n (low-res), HCOLOR=n (high-res)
PLOT x,y / HPLOT x,y
DRAW/XDRAW shape commands
ROTATE/SCALE shape transformations
Definition at line 106 of file interpreter.h.
Constructor & Destructor Documentation
Interpreter()
Interpreter::Interpreter (const GraphicsConfig & config = GraphicsConfig())
Construct interpreter with optional graphics configuration.
Parameters
config Graphics rendering configuration (default: graphics enabled)
Definition at line 51 of file interpreter.cpp.
References pokeMemory().
Member Function Documentation
addDataValue()
void Interpreter::addDataValue (const Value & value)
Add a data value to the DATA cache.
Called during program initialization to build the data cache. This is used internally by the DATA statement collection process.
Parameters
value Value to add to data cache
Definition at line 2694 of file interpreter.cpp.
Referenced by DataStmt::execute().
addLine()
void Interpreter::addLine (LineNumber lineNum, const std::string & text)
Add or replace program line.
Add or update a program line.
Parameters
lineNum Line number (0-32767)
text Line content (statements)
If line exists, replaces it; otherwise inserts new line in sorted order. Empty text deletes the line.
If text is empty, deletes the line. Otherwise, tokenizes and parses the line, then stores it in the program map. Lines are kept sorted by line number via std::map.
Parameters
lineNum Line number (0-32767)
text BASIC code for this line
Definition at line 156 of file interpreter.cpp.
References ProgramLine::lineNumber, Parser::parse(), ProgramLine::statements, ProgramLine::text, Tokenizer::tokenize(), and ProgramLine::tokens.
Referenced by chainProgram(), chainProgram(), dashProgram(), executeImmediate(), and loadProgram().
appendFile()
void Interpreter::appendFile (const std::string & filename)
Open file in append mode (APPEND implementation)
Opens a file for appending data at the end. This is a convenience wrapper that calls openFile() with APPEND mode.
Error conditions:
Empty filename: "SYNTAX ERROR"
I/O errors: Propagated from openFile()
BASIC Usage: APPEND "LOG.TXT"
Parameters
filename Name of file to open for appending
Definition at line 1502 of file interpreter.cpp.
References APPEND, FileManager::getInstance(), handleError(), and FileManager::openFile().
Referenced by AppendFileStmt::execute(), and executeImmediate().
bloadFile()
void Interpreter::bloadFile (const std::string & filename, int address)
Load binary file into memory (BLOAD implementation)
Loads a binary file from disk, optionally at a specific memory address. This implements the BLOAD command from Applesoft BASIC, used for loading machine language programs and data files.
BASIC Usage: BLOAD "PROGRAM.BIN" (load at default/stored address) BLOAD "PROGRAM.BIN",A8192 (load at address 8192/$2000) BLOAD "DATA.BIN",A$4000 (load at hex address $4000)
Address handling:
If address = -1: Uses address stored in file header (if any)
If address >= 0: Loads at specified address, ignoring file header
Negative addresses use Apple II 16-bit wraparound convention
File format compatibility:
ProDOS binary format: 4-byte header (address, length)
Raw binary files: No header, requires explicit address
Current implementation:
Loads file data but doesn't populate emulated memory yet
Full Apple II emulation would copy bytes to memory array
Useful for loading shape tables, fonts, or ML routines
Parameters
filename Path to binary file to load
address Target memory address, or -1 for file's stored address
Exceptions
std::runtime_error on I/O errors or invalid file format
Definition at line 1714 of file interpreter.cpp.
References FileManager::getInstance(), handleError(), and FileManager::loadBinaryFile().
Referenced by brunFile(), dashRun(), BloadFileStmt::execute(), and executeImmediate().
brunFile()
void Interpreter::brunFile (const std::string & filename, int address)
Load and execute binary file (BRUN implementation)
Loads a binary file into memory and executes it as machine language code. This implements the BRUN command from Applesoft BASIC. BRUN is equivalent to BLOAD followed by CALL.
BASIC Usage: BRUN HELLO (standard DOS 3.3 boot) BRUN PROGRAM.BIN,A$300 (load and execute at page 3)
Execution sequence:
Load binary file via bloadFile()
If address specified, call machine code at that address
If no address, use file's stored start address
Common uses:
Boot programs: BRUN HELLO
Launch ML utilities: BRUN TOOLKIT
Run assembly programs: BRUN GAME.BIN
Current implementation:
Loads file but doesn't execute actual machine code
Calls callAddress() which handles special Apple II ROM addresses
Full implementation would require CPU emulation
Parameters
filename Path to binary file to load and execute
address Execution address, or -1 to use file's stored address
Definition at line 1815 of file interpreter.cpp.
References bloadFile(), and callAddress().
Referenced by BrunFileStmt::execute(), and executeImmediate().
bsaveFile()
void Interpreter::bsaveFile (const std::string & filename, int address, int length)
Save memory region to binary file (BSAVE implementation)
Saves a region of memory to a binary file with ProDOS-compatible format. This implements the BSAVE command from Applesoft BASIC, used for saving machine language programs, screen images, and data arrays.
BASIC Usage: BSAVE "SCREEN.BIN",A8192,L8192 (save hi-res page 1) BSAVE "PROG.BIN",A$300,L$100 (save page 3 ML routine) BSAVE "DATA.BIN",A16384,L4096 (save 4K data block)
Parameters:
filename: Output file path
address: Starting memory address to save from
length: Number of bytes to save
File format:
4-byte header: 2-byte address (little-endian), 2-byte length
Followed by raw memory contents
Compatible with ProDOS BLOAD command
Common uses in Applesoft:
Save hi-res graphics: BSAVE "PIC",A8192,L8192 (page 1)
Save shape tables: After creating with DRAW/XDRAW
Save ML routines: After POKEing machine code
Current implementation:
Creates dummy data (zeros) instead of reading from memory
Full implementation would copy bytes from emulated memory array
Parameters
filename Path to output binary file
address Starting memory address
length Number of bytes to save
Exceptions
std::runtime_error on I/O errors or invalid parameters
Definition at line 1768 of file interpreter.cpp.
References FileManager::getInstance(), handleError(), and FileManager::saveBinaryFile().
Referenced by BsaveFileStmt::execute(), and executeImmediate().
callAddress()
void Interpreter::callAddress (int address)
Execute machine language at address (CALL implementation)
Simulates calling machine language routines at specific memory addresses. This implements the CALL command from Applesoft BASIC. Since we don't have a full 6502 emulator, we handle known Apple II ROM addresses specially.
BASIC Usage: CALL -936 (HOME - clear screen, same as $FC58) CALL 768 (page 3 user ML routine, same as $0300) CALL -3288 (clean up stack, same as $F308)
Address handling:
Negative addresses use Apple II 16-bit wraparound convention: CALL -936 becomes $10000 + (-936) = $FC58 (65,368)
This matches Applesoft BASIC address notation
Known ROM addresses (special handling):
Text/Screen Control:
$FC58 (-936): HOME - Clear screen and home cursor
$FC66 (-922): Line feed
$FC70 (-912): Scroll text window up
$FC9C (-868): CLREOL - Clear to end of line
$FC42 (-958): Clear from cursor to bottom-right
Graphics Control:
$F3D2 (-3086): Clear hi-res page to black
$F3D6 (-3082): Clear hi-res to last HPLOT color
$F832 (-1998): BKGND - Set background color
System Control:
$F308 (-3288): Stack cleanup routine
$FF69 (-151): Enter Monitor (not implemented)
$03EA: Restore ProDOS connection
User ML Area:
$0300 (768): Common location for user ML routines (page 3)
Implementation notes:
Known ROM addresses output stub messages or perform equivalent actions
Unknown addresses print "NOT IMPLEMENTED" message
Full implementation would require 6502 CPU emulation
HOME ($FC58) is fully implemented with ANSI clear screen
CLREOL ($FC9C) is fully implemented with ANSI clear to EOL
Parameters
address Memory address to call (may be negative)
Definition at line 1872 of file interpreter.cpp.
References formatHexAddress(), and pokeMemory().
Referenced by brunFile(), and CallStmt::execute().
catalog()
void Interpreter::catalog ()
List files in the current directory (CATALOG immediate command)
Prints a simple file listing for the current working directory. The implementation is intentionally lightweight and omits full ProDOS-style metadata (file types, sizes, dates). Use PREFIX to change directories before calling CATALOG to list other locations.
Definition at line 1219 of file interpreter.cpp.
References listFiles().
Referenced by executeImmediate().
catalogFiles()
void Interpreter::catalogFiles (const std::string & path = ".")
List files in specified directory (internal CATALOG helper)
Lists all non-hidden files in the specified directory. This is similar to catalog() but allows specifying a directory path instead of using the current directory.
Output format:
Header: "CAT <path>"
One filename per line with leading space
Hidden files (starting with '.') are excluded
Directories are excluded (files only)
Used internally by ProDOS-style CATALOG commands that specify a path.
Parameters
path Directory path to list
Definition at line 3614 of file interpreter.cpp.
References listFiles().
Referenced by CatStmt::execute().
chainProgram() [1/2]
void Interpreter::chainProgram (const std::string & filename)
Load and run program keeping current variables (CHAIN)
Chain to another program (CHAIN command implementation)
Parameters
filename Path to program file
Loads the specified program and begins execution while preserving all variable values. Used for multi-part programs.
Loads and runs a new BASIC program while preserving variable values. This allows breaking large programs into multiple files that share data.
BASIC Usage: CHAIN "PART2.BAS"
Behavior:
Clears current program
Keeps all variable values intact
Loads new program from file
Begins execution at first line of new program
Common variables automatically transfer between programs
Use Cases:
Multi-part adventures/games
Menu systems that load different modules
Programs that exceed memory by splitting into parts
Parameters
filename Path to next program to chain to
Definition at line 1131 of file interpreter.cpp.
References addLine(), readTextFile(), and run().
Referenced by ChainStmt::execute(), and executeImmediate().
chainProgram() [2/2]
void Interpreter::chainProgram (const std::string & filename, int startLine)
Load and run program with optional starting line (CHAIN implementation)
Implements the CHAIN command which loads a new program and runs it while preserving all variables. Optionally starts execution from a specified line number instead of the beginning.
Behavior:
Clears the current program listing
Loads new program from file
Preserves all variables and arrays
Clears DATA/READ state
Starts execution from specified line or beginning
Difference from dash (-) command:
CHAIN allows specifying starting line
CHAIN is more flexible for program chaining
Both preserve variables
Error handling:
File not found: Displays error message
Invalid starting line: Propagated from runFrom()
Parse errors: Handled during program loading
BASIC Usage: CHAIN "PROG2" (run from beginning) CHAIN "PROG2", 100 (run from line 100)
Parameters
filename Path to BASIC program file
startLine Line number to start from (0 or negative = start from beginning)
Definition at line 3659 of file interpreter.cpp.
References addLine(), readTextFile(), run(), and runFrom().
changePrefix()
void Interpreter::changePrefix (const std::string & path)
Change directory prefix (PREFIX implementation)
Changes the current working directory (the interpreter's ProDOS prefix). Subsequent file operations use this directory as the base for partial pathnames.
Path handling:
Absolute paths start from root
Relative paths are resolved relative to the current prefix
Parent directory: ".." (Unix-style)
Error conditions:
Empty path: "SYNTAX ERROR"
Path not found or not a directory: "PATH NOT FOUND ERROR"
Usage in BASIC: PREFIX "/VOLUME/DIR" PREFIX (no argument shows current prefix)
Parameters
path New directory path (absolute or relative)
Definition at line 1379 of file interpreter.cpp.
References handleError(), and setPrefix().
Referenced by executeImmediate(), and setPrefix().
changeTapeFile()
void Interpreter::changeTapeFile ()
Definition at line 3834 of file interpreter.cpp.
References TapeManager::setTapeFile(), and TapeManager::showFileSelector().
clearState()
void Interpreter::clearState ()
Clear variables and control stacks (CLR command)
Clears variables, FOR/NEXT and GOSUB stacks, DATA state, and error handlers. Preserves program lines. This is equivalent to the CLR command in Applesoft BASIC.
Definition at line 210 of file interpreter.cpp.
References Variables::clear(), and resetOutputPosition().
Referenced by ClrStmt::execute().
closeAllFiles()
void Interpreter::closeAllFiles ()
Close all open files.
Closes all files that are currently open and flushes any buffered data. This is called by CLOSE with no arguments or during program cleanup.
BASIC Usage: CLOSE (no filename closes all files)
Definition at line 1483 of file interpreter.cpp.
References FileManager::closeAllFiles(), and FileManager::getInstance().
Referenced by CloseFileStmt::execute(), and executeImmediate().
closeFile()
void Interpreter::closeFile (const std::string & filename)
Close an open file (CLOSE implementation)
Closes a previously opened file and releases its file handle. Any buffered data is flushed to disk. This implements the CLOSE command from ProDOS Applesoft BASIC.
Behavior:
Flushes any buffered write data
Releases file handle for reuse
Safe to call on already-closed files (no-op)
File can be reopened after closing
BASIC Usage: CLOSE "DATA.TXT" CLOSE (closes all files)
Parameters
filename Name of file to close
Close an open file (CLOSE implementation)
Definition at line 1466 of file interpreter.cpp.
References FileManager::closeFile(), FileManager::getInstance(), and handleError().
Referenced by CloseFileStmt::execute(), and executeImmediate().
cont()
void Interpreter::cont ()
Continue after STOP (CONT)
Continue execution after STOP (CONT implementation)
Exceptions
RuntimeError if no program stopped
Resumes program execution from the point where it was stopped by a STOP statement. This allows interactive debugging and controlled program flow.
Continuation process:
Validate that program is in paused state
Find the line where STOP occurred
Advance to the NEXT line (don't re-execute STOP line)
Resume normal execution loop
State validation:
Must have paused_ flag set (STOP was executed)
Must have valid continueAfterLine_
Program and continue line must still exist
Error conditions:
Not paused: "CANT CONTINUE"
Program cleared: "CANT CONTINUE"
Continue line deleted: "CANT CONTINUE"
Example session: ] 10 PRINT "START" ] 20 STOP ] 30 PRINT "END" ] RUN START (program stops at line 20) ] CONT END
Exceptions
std::runtime_error if continuation is not possible
Definition at line 985 of file interpreter.cpp.
References gotoLine().
Referenced by executeImmediate().
createFile()
void Interpreter::createFile (const std::string & filename, const std::string & options)
Create a new empty file (CREATE implementation)
Creates a new empty file with the specified name. If the file already exists, behavior depends on the filesystem implementation. This implements the CREATE command from ProDOS Applesoft BASIC.
File creation:
Creates empty file (0 bytes)
Default permissions set by OS
Directory must exist
Parent directory must be writable
Error conditions:
Empty filename: "SYNTAX ERROR"
Directory not found: "I/O ERROR"
Permission denied: "I/O ERROR"
Disk full: "I/O ERROR"
BASIC Usage: CREATE "NEWFILE.DAT" CREATE "DATA.TXT", T=TXT (with type, not yet implemented)
Parameters
filename Name of file to create
options File type and options (currently ignored)
Definition at line 1670 of file interpreter.cpp.
References createFile(), FileManager::getInstance(), and handleError().
Referenced by createFile(), CreateFileStmt::execute(), and executeImmediate().
dashProgram()
void Interpreter::dashProgram (const std::string & filename)
Run program without clearing variables (-)
DASH program load+run without clearing variables ("-" command)
Parameters
filename Path to program file
Similar to CHAIN but doesn't automatically start execution.
Loads a BASIC program from disk and runs it immediately while preserving the interpreter's current variable state. This matches the ProDOS BASIC.SYSTEM behavior for the dash command: it clears the current program listing, loads the new program, clears DATA/READ state (dataValues_, dataOffsets_), and starts execution from the first line.
Difference from CHAIN:
CHAIN may specify a starting line and pass values; DASH always starts from the first line and is a simpler load+run operation.
Usage in BASIC:
"NEXT.BAS" (load and run NEXT.BAS, keep variables)
Parameters
filename Path to BASIC program file
Definition at line 1180 of file interpreter.cpp.
References addLine(), readTextFile(), and run().
Referenced by dashRun(), and executeImmediate().
dashRun()
void Interpreter::dashRun (const std::string & filename)
Definition at line 3694 of file interpreter.cpp.
References bloadFile(), and dashProgram().
Referenced by DashStmt::execute().
deleteFile()
void Interpreter::deleteFile (const std::string & filename)
Delete a file (DELETE implementation)
Deletes the specified file from disk. Implements the DELETE command from ProDOS Applesoft BASIC. On failure, a ProDOS-style error is raised (e.g., "PATH NOT FOUND ERROR" for missing files).
Error conditions:
Empty filename: "SYNTAX ERROR"
File not found: "PATH NOT FOUND ERROR"
Permission denied: Handled by filesystem layer
BASIC Usage: DELETE "FILE"
Parameters
filename Path to file to delete
Definition at line 1298 of file interpreter.cpp.
References deleteFile(), and handleError().
Referenced by deleteFile(), DeleteFileStmt::execute(), and executeImmediate().
deleteLine()
void Interpreter::deleteLine (LineNumber lineNum)
Delete program line.
Delete a program line.
Parameters
lineNum Line number to remove
Removes a program line from memory. If the line number doesn't exist, this operation silently succeeds (no error is raised).
Usage in BASIC: Type just a line number (e.g., "10") to delete line 10
Parameters
lineNum Line number to delete
Definition at line 186 of file interpreter.cpp.
Referenced by executeImmediate().
endProgram()
void Interpreter::endProgram ()
End program execution (END)
Stop program execution permanently (END implementation)
Halts program normally. State preserved for CONT.
Terminates program execution by clearing the running_ flag. Unlike STOP, END does not support continuation with CONT.
Typical usage:
END statement at end of main program
Prevents "fall-through" into subroutines at end of program
Example: 100 PRINT "DONE" 110 END 1000 REM SUBROUTINES FOLLOW
Definition at line 918 of file interpreter.cpp.
Referenced by EndStmt::execute().
execFile()
void Interpreter::execFile (const std::string & filename)
Execute commands from a text file (EXEC implementation)
Reads a sequential text file and executes each line as if typed at the keyboard. Lines beginning with REM are skipped. Each non-empty, non-REM line is executed via executeImmediate(). Errors are caught and reported but do not stop execution of the remaining lines.
Processing:
Reads file line by line
Skips empty lines and REM comments
Executes each line via executeImmediate()
Lines can be immediate commands or numbered program lines
Common uses:
Automated testing (EXEC TEST.COMMANDS)
Configuration (EXEC STARTUP scripts)
Batch program loading
Usage in BASIC: EXEC "STARTUP"
Parameters
filename Path to EXEC text file
Definition at line 1255 of file interpreter.cpp.
References executeImmediate(), and readTextFile().
Referenced by ExecStmt::execute(), and executeImmediate().
executeImmediate()
void Interpreter::executeImmediate (const std::string & line)
Execute single line without line number (immediate mode)
Execute an immediate command or add a program line.
Parameters
line BASIC statement(s) to execute
Parses and executes the line immediately. Used for direct commands and REPL interaction.
This is the main entry point for processing user input in interactive mode. It handles two types of input:
Numbered lines (e.g., "10 PRINT "HELLO""):
Adds or updates a program line
If code is empty, deletes the line
Immediate commands (no line number):
Special commands handled directly (RUN, LIST, NEW, etc.)
Other statements executed immediately in immediate mode
Special Command Processing:
RUN [line]: Start execution from beginning or specified line
LIST [start[,end]]: Display program lines
NEW: Clear program and variables
LOAD, SAVE, CATALOG, DEL: File/program management
CONT: Continue after STOP
The function uses case-insensitive command matching and trims whitespace from arguments. Syntax errors in special commands print an error message but don't stop the interpreter.
Parameters
line Input line from user (may have line number or be immediate)
Definition at line 423 of file interpreter.cpp.
References addLine(), appendFile(), bloadFile(), brunFile(), bsaveFile(), catalog(), chainProgram(), changePrefix(), closeAllFiles(), closeFile(), cont(), createFile(), dashProgram(), deleteFile(), deleteLine(), execFile(), flushFile(), handleError(), listProgram(), loadProgram(), lockFile(), newProgram(), openFile(), Parser::parse(), positionFile(), renameFile(), run(), runFrom(), saveProgram(), showPrefix(), Tokenizer::tokenize(), and unlockFile().
Referenced by execFile(), and InteractiveMode::run().
flushFile()
void Interpreter::flushFile (const std::string & filename)
Flush buffered file data to disk (FLUSH implementation)
Forces any buffered write data for the specified file to be written to disk immediately. Useful for ensuring data persistence before long operations or potential crashes.
Error conditions:
Empty filename: "SYNTAX ERROR"
File not open: Varies by implementation
I/O error: Propagated from filesystem
BASIC Usage: FLUSH "DATA.TXT"
Parameters
filename Name of file to flush
Definition at line 1532 of file interpreter.cpp.
References FileManager::flushFile(), FileManager::getInstance(), and handleError().
Referenced by FlushFileStmt::execute(), and executeImmediate().
getCurrentLine()
LineNumber Interpreter::getCurrentLine () const inline
Get currently executing line number.
Returns
Current line number or -1 if in immediate mode
Definition at line 248 of file interpreter.h.
Referenced by ForStmt::execute(), and WhileStmt::execute().
getGraphicsConfig()
const GraphicsConfig & Interpreter::getGraphicsConfig () const inline
Get graphics configuration.
Returns
Reference to GraphicsConfig
Definition at line 234 of file interpreter.h.
getHimem()
int Interpreter::getHimem () const inline
Definition at line 421 of file interpreter.h.
getInputDevice()
int Interpreter::getInputDevice () const inline
Definition at line 398 of file interpreter.h.
getLomem()
int Interpreter::getLomem () const inline
Definition at line 422 of file interpreter.h.
getOutputDevice()
int Interpreter::getOutputDevice () const inline
Definition at line 397 of file interpreter.h.
getSpeedDelay()
int Interpreter::getSpeedDelay () const inline
Definition at line 392 of file interpreter.h.
getTapeFile()
std::string Interpreter::getTapeFile () const
Definition at line 3830 of file interpreter.cpp.
References TapeManager::getTapeFile().
Referenced by TapeStmt::execute().
getTapeHotkey()
std::string Interpreter::getTapeHotkey () const inline
Definition at line 478 of file interpreter.h.
getTextMode()
TextMode Interpreter::getTextMode () const inline
Definition at line 361 of file interpreter.h.
References GraphicsConfig::textMode.
getVariables()
Variables & Interpreter::getVariables () inline
Get variable storage for expression evaluation.
Returns
Reference to Variables instance
Definition at line 226 of file interpreter.h.
Referenced by VariableExpr::evaluate(), ArrayAccessExpr::evaluate(), UserFunctionCallExpr::evaluate(), LetStmt::execute(), ArrayLetStmt::execute(), ForStmt::execute(), InputStmt::execute(), DimStmt::execute(), ReadStmt::execute(), GetStmt::execute(), and DefStmt::execute().
gosub()
void Interpreter::gosub (LineNumber lineNum)
Call subroutine at line (GOSUB)
Call a subroutine (GOSUB implementation)
Parameters
lineNum Subroutine line number
Exceptions
RuntimeError if line not found or stack overflow
Pushes return address on GOSUB stack and jumps to target line.
Saves the current line number on the return stack and jumps to the specified subroutine line. The RETURN statement will pop the stack and continue execution after the GOSUB.
Stack structure:
Each GOSUB pushes the current line number (not program counter)
RETURN pops the line and continues from the NEXT line
Nested GOSUBs work through standard stack behavior
Stack is cleared by CLR or program termination
Error conditions:
Target line not found: "UNDEF'D STATEMENT ERROR"
Stack overflow: Limited only by system memory
Unmatched RETURN: "RETURN WITHOUT GOSUB ERROR" (checked in returnFromGosub)
Example: 10 GOSUB 100 ' Push line 10, jump to 100 20 PRINT "BACK" ... 100 PRINT "SUB" 110 RETURN ' Pop line 10, continue at line 20
Parameters
lineNum Target subroutine line number
Exceptions
std::runtime_error if line number not found
Definition at line 855 of file interpreter.cpp.
Referenced by OnTransferStmt::execute(), and GosubStmt::execute().
gotoLine()
void Interpreter::gotoLine (LineNumber lineNum)
Jump to specified line (GOTO)
Jump to a program line (GOTO implementation)
Parameters
lineNum Target line number
Exceptions
RuntimeError if line not found
Changes the program counter to execute from the specified line number. This is the core implementation of GOTO and is also used by GOSUB, error handlers (ONERR), and ON...GOTO statements.
The function validates that the target line exists in the program and throws "UNDEF'D STATEMENT ERROR" if not found. The jumped_ flag is set to prevent automatic advancement to the next line.
Implementation notes:
Does not affect the GOSUB stack (unlike gosub())
Sets jumped_ flag to override normal sequential execution
Used by: GOTO, error handlers, ON...GOTO, RESTORE (for DATA)
Parameters
lineNum Target line number to jump to
Exceptions
std::runtime_error if line number not found in program
Jump to a specific line (GOTO implementation)
Changes program execution to the specified line number. This is the core control flow primitive used by GOTO, IF...THEN, and ON...GOTO.
Implementation:
Searches program_ map for target line
Updates programCounter_ to point to that line
Sets jumped_ flag to prevent automatic advancement
The jumped_ flag tells the main execution loop not to advance to the next line automatically, since we've explicitly changed position.
BASIC Usage: GOTO 100 IF X > 10 THEN GOTO 200 ON N GOTO 100,200,300
Parameters
lineNum Target line number to jump to
Exceptions
std::runtime_error if line number not found
Definition at line 818 of file interpreter.cpp.
Referenced by cont(), OnTransferStmt::execute(), GotoStmt::execute(), resume(), and runFrom().
handleError() [1/2]
void Interpreter::handleError (const std::string & message)
Throw a runtime error.
Simple error throwing mechanism. Throws std::runtime_error with the provided message. If an ONERR handler is active, the main execution loop will catch this and transfer control to the handler.
Parameters
message Error message text (e.g., "SYNTAX ERROR", "OUT OF DATA ERROR")
Exceptions
std::runtime_error always
Definition at line 3211 of file interpreter.cpp.
Referenced by appendFile(), bloadFile(), bsaveFile(), changePrefix(), closeFile(), createFile(), deleteFile(), executeImmediate(), flushFile(), lockFile(), openFile(), positionFile(), readFile(), renameFile(), requireGraphicsMode(), unlockFile(), and writeFile().
handleError() [2/2]
void Interpreter::handleError (const std::string & message, int errorCode)
Throw a runtime error with ProDOS error code.
Extended error throwing that includes a ProDOS-compatible error code. The error code is stored in memory location 222 ($DE) for compatibility with Applesoft BASIC programs that check error codes via PEEK.
Common ProDOS error codes:
4: PATH NOT FOUND
5: VOLUME NOT FOUND
7: DUPLICATE FILENAME
45: FILE LOCKED
46: VOLUME LOCKED
52: NOT A PRODOS DISK
56: BAD BUFFER ADDRESS
Parameters
message Error message text
errorCode ProDOS error code to store in memory location 222
Exceptions
std::runtime_error always
Definition at line 3235 of file interpreter.cpp.
References pokeMemory().
htab()
void Interpreter::htab (int col1)
Move cursor to column (HTAB)
Move cursor to horizontal column (HTAB implementation)
Parameters
col1 Column number (1-based, 1-40 for 40-col, 1-80 for 80-col)
Moves the cursor to the specified column by printing spaces. This implements the HTAB (horizontal tab) command from Applesoft BASIC.
Behavior:
Column numbers are 1-based (HTAB 1 = leftmost column)
If target column is left of or at current position, does nothing
If target column is right of current position, prints spaces to reach it
Does not wrap to next line if target exceeds line width
BASIC Usage: HTAB 10: PRINT "TEXT" (print starting at column 10) HTAB 1 (return to left margin)
Parameters
col1 Target column (1-based, 1 = leftmost)
Definition at line 2780 of file interpreter.cpp.
References printText().
Referenced by HtabStmt::execute().
interactive()
void Interpreter::interactive ()
Enter interactive REPL mode.
Displays prompt and processes user input until exit. Deprecated: Use InteractiveMode class instead.
Definition at line 3821 of file interpreter.cpp.
References interactive(), and InteractiveMode::run().
Referenced by interactive().
isGraphicsEnabled()
bool Interpreter::isGraphicsEnabled () const inline
Check if graphics mode is enabled.
Returns
true if graphics operations are allowed
Definition at line 240 of file interpreter.h.
References GraphicsConfig::isGraphicsEnabled().
isImmediateMode()
bool Interpreter::isImmediateMode () const inline
Definition at line 364 of file interpreter.h.
Referenced by DataStmt::execute().
isInForLoop()
bool Interpreter::isInForLoop (const std::string & varName)
Check if a variable is currently a FOR loop control variable.
Searches the FOR loop stack to determine if the specified variable is currently controlling an active FOR loop. Used to prevent certain operations that would corrupt loop state.
Parameters
varName Variable name to check
Returns
true if variable is a FOR loop control variable, false otherwise
Definition at line 3099 of file interpreter.cpp.
isTracing()
bool Interpreter::isTracing () const inline
Definition at line 385 of file interpreter.h.
listProgram()
void Interpreter::listProgram (int startLine = -1, int endLine = -1)
List program lines to output (LIST)
List program lines to stdout (LIST command)
Parameters
startLine Starting line number (-1 for first line)
endLine Ending line number (-1 for last line)
Displays program lines in the specified range. With no arguments, lists entire program.
Displays program lines with line numbers. If startLine or endLine are negative, lists all lines. Otherwise, lists lines in the specified range.
Parameters
startLine First line to list (-1 for beginning)
endLine Last line to list (-1 for end)
Definition at line 234 of file interpreter.cpp.
Referenced by executeImmediate().
loadProgram()
void Interpreter::loadProgram (const std::string & filename)
Load BASIC program from file.
Load a BASIC program from disk (LOAD command implementation)
Parameters
filename Path to .bas or tokenized BASIC file
Exceptions
RuntimeError on file I/O errors
Clears current program and variables, then loads the specified file. Supports both plain text (.bas) and tokenized BASIC formats.
Loads a BASIC program from a text file, replacing the current program. The file should contain BASIC source code with line numbers.
BASIC Usage: LOAD "MYPROG.BAS"
File Format: 10 PRINT "HELLO" 20 GOTO 10
Behavior:
Clears current program and variables (like NEW)
Parses each line and adds to program
Silently ignores lines without valid line numbers
On error, prints error message and continues
Parameters
filename Path to BASIC program file
Definition at line 1055 of file interpreter.cpp.
References addLine(), newProgram(), and readTextFile().
Referenced by executeImmediate(), and main().
loadShapeTableFromFile()
void Interpreter::loadShapeTableFromFile (const std::string & filename)
Load shape table from file or tape (SHLOAD implementation)
Loads a shape table containing vector graphics shapes for use with DRAW and XDRAW commands. This implements the SHLOAD command from Applesoft BASIC which originally loaded shape tables from cassette tape.
Shape table format:
Shape count (1 byte)
For each shape:
Point count (2 bytes, little-endian)
Points as (x,y) pairs (4 bytes each: 2 for x, 2 for y, little-endian)
Loading behavior:
If filename is empty and tape is set: reads from tape
If filename provided: reads from disk file
Shape table pointer stored in memory locations 0xE8-0xE9
Shapes are numbered starting from 1
Shape 0 is invalid/undefined
Usage with graphics: SHLOAD "SHAPES.SHP" DRAW 1 AT 100,100 (draw shape 1) XDRAW 2 AT 50,50 (draw shape 2 in XOR mode)
Error conditions:
File not found: "PATH NOT FOUND ERROR"
Invalid format: "INVALID SHAPE TABLE FORMAT"
Corrupt data: "INVALID SHAPE TABLE FORMAT"
Too many shapes: Handled by format limits
Parameters
filename Path to shape table file (empty string for tape)
Exceptions
std::runtime_error if file not found or format invalid
Definition at line 2598 of file interpreter.cpp.
References TapeManager::hasTape(), TapeManager::openForRead(), pokeMemory(), and TapeManager::readRecord().
Referenced by ShloadStmt::execute().
lockFile()
void Interpreter::lockFile (const std::string & filename)
Lock a file (LOCK implementation)
Marks a file as locked to prevent deletion or modification. This implements the LOCK command from ProDOS Applesoft BASIC. Platform-specific behavior varies and the current implementation provides a graceful stub.
Error conditions:
Empty filename: "SYNTAX ERROR"
File not found: "I/O ERROR"
Permission denied: "I/O ERROR"
BASIC Usage: LOCK "IMPORTANT.DAT"
Parameters
filename Path to file
Definition at line 1605 of file interpreter.cpp.
References FileManager::getInstance(), handleError(), and lockFile().
Referenced by LockFileStmt::execute(), executeImmediate(), and lockFile().
newProgram()
void Interpreter::newProgram ()
Clear program and variables (NEW)
Clear program and all state (NEW command)
Resets interpreter to clean state: clears all program lines, variables, arrays, DEF FN definitions, and DATA pointers.
Clears program lines, variables, DATA values, and resets output position. This is equivalent to the NEW command in Applesoft BASIC.
Definition at line 194 of file interpreter.cpp.
References Variables::clear(), and resetOutputPosition().
Referenced by executeImmediate(), and loadProgram().
nextForLoop()
void Interpreter::nextForLoop (const std::string & varName)
Process NEXT statement for loop iteration.
Handles the NEXT statement which increments the loop variable and either continues the loop (jumping back to statement after FOR) or terminates it (popping from stack and continuing forward).
Algorithm:
Find matching FOR loop (search backwards through stack)
Increment loop variable by STEP value
Check termination condition:
Positive STEP: continue if var <= end
Negative STEP: continue if var >= end
If continuing: jump to line after FOR statement
If done: pop loop from stack and continue forward
BASIC Usage: FOR I = 1 TO 10 STEP 2 PRINT I NEXT I
FOR I = 10 TO 1 STEP -1 (counting down) PRINT I NEXT I
NEXT (NEXT without variable matches most recent FOR)
Error handling:
If no matching FOR found: "NEXT WITHOUT FOR ERROR"
Variable name matching uses normalized names (2-char significance)
Empty varName matches most recent loop (allows bare NEXT)
Parameters
varName Loop variable name (empty string matches most recent loop)
Exceptions
std::runtime_error if no matching FOR loop found
Definition at line 3142 of file interpreter.cpp.
References Value::getNumber(), Variables::getVariable(), and Variables::setVariable().
Referenced by NextStmt::execute().
nextWhileLoop()
void Interpreter::nextWhileLoop ()
Handle WEND statement (WHILE loop terminator)
Checks the WHILE loop condition and either continues the loop or exits. This implements the WEND statement which closes a WHILE loop.
Behavior:
Pops WHILE loop info from stack
Re-evaluates the loop condition
If true: Jumps back to line after WHILE statement
If false: Continues to next statement (exits loop)
Error conditions:
No matching WHILE: "WEND WITHOUT WHILE ERROR"
BASIC Usage: WHILE X < 10 X = X + 1 WEND (check condition and loop or continue)
Exceptions
std::runtime_error if no matching WHILE found
Definition at line 3494 of file interpreter.cpp.
References Value::getNumber().
Referenced by WendStmt::execute().
openFile()
void Interpreter::openFile (const std::string & filename, const std::string & options)
Open a file (OPEN implementation)
Opens a file with the specified access mode for reading or writing. This implements ProDOS-style OPEN semantics used by Applesoft BASIC. The interpreter maps OPEN to the FileManager helper which returns an integer handle for subsequent operations.
Access modes:
READ (default): Open for reading
WRITE (W): Open for writing (truncates existing file)
APPEND (A): Open for appending (writes at end)
File management:
Files are tracked by the FileManager singleton
Multiple files can be open simultaneously
Use CLOSE to release file handles
File position maintained across READ/WRITE operations
Error conditions:
Empty filename: "SYNTAX ERROR"
File not found (READ mode): Varies by implementation
Permission denied: Propagated from filesystem
BASIC Usage: OPEN "DATA.TXT", READ OPEN "OUTPUT.TXT", WRITE OPEN "LOG.TXT", APPEND
Parameters
filename Path to file
options Mode string (READ, WRITE, APPEND, W, A)
Definition at line 1422 of file interpreter.cpp.
References APPEND, FileManager::getInstance(), handleError(), FileManager::openFile(), READ, and WRITE.
Referenced by OpenFileStmt::execute(), and executeImmediate().
popGosub()
void Interpreter::popGosub ()
Pop GOSUB return address from stack (POP implementation)
Removes the top entry from the GOSUB stack without returning. This implements the POP command from Applesoft BASIC which allows exiting from a subroutine without using RETURN.
Use cases:
Exit subroutine early without returning
Clear return address after error in subroutine
Clean up stack when changing program flow
Error conditions:
Empty stack: "POP WITHOUT GOSUB ERROR"
BASIC Usage: 100 GOSUB 1000 110 PRINT "BACK" ... 1000 IF X < 0 THEN POP: GOTO 100 (restart instead of return) 1010 RETURN
Exceptions
std::runtime_error if GOSUB stack is empty
Definition at line 3540 of file interpreter.cpp.
Referenced by PopStmt::execute().
positionFile()
void Interpreter::positionFile (const std::string & filename, int record, int byte)
Position a file pointer (POSITION pn[,Rrecord][,Bbyte])
Sets the file pointer to a specific byte offset for random access I/O. This is a stub implementation: full ProDOS random-access positioning is not yet implemented; use sequential I/O where possible.
ProDOS Position semantics:
record: 512-byte record number
byte: byte offset within record
position = record * 512 + byte
Current status:
Positioning is a stub and reports that random-access positioning is not fully implemented
Sequential I/O remains supported
BASIC Usage: POSITION filename, Rrecord, Bbyte
Parameters
filename Path to file to open for reading
record Record number (512-byte blocks)
byte Byte offset within record
Definition at line 1569 of file interpreter.cpp.
References handleError().
Referenced by PositionFileStmt::execute(), and executeImmediate().
printNewline()
void Interpreter::printNewline ()
Output newline.
Print newline and update cursor tracking.
Outputs a newline character and updates cursor position tracking. Also updates memory location 0x0025 (37) with the new cursor row for compatibility with Applesoft BASIC PEEK operations.
Cursor updates:
outputColumn_ set to 0 (start of new line)
outputRow_ incremented
Memory location 37: Updated with new row value
Used by:
PRINT with no trailing semicolon/comma
VTAB to advance to target row
Automatic line wrapping (if implemented)
Definition at line 2983 of file interpreter.cpp.
References pokeMemory().
Referenced by PrintStmt::execute(), and vtab().
printText()
void Interpreter::printText (const std::string & text)
Output text string.
Print text to output (internal helper)
Parameters
text String to print
Respects current text attributes (inverse, flash) and handles TAB/SPC positioning.
Outputs text character by character, tracking cursor position for HTAB/VTAB. This is the low-level output primitive used by PRINT and other output commands.
Character handling:
Bell character (): Flushes output immediately for audible feedback
Newline (
): Resets column to 0, increments row
Other characters: Increments column position
Position tracking:
outputColumn_: Current horizontal position (0-based)
outputRow_: Current vertical position (0-based)
These are used by HTAB, VTAB, and POS() function
Parameters
text Text string to output
Definition at line 2951 of file interpreter.cpp.
Referenced by PrintStmt::execute(), htab(), and printToNextZone().
printToNextZone()
void Interpreter::printToNextZone ()
Tab to next print zone (14-character zones)
Advance to next print zone (comma separator handling)
Implements the comma separator behavior in PRINT statements. Advances the cursor to the next 14-column zone boundary. This matches Applesoft BASIC's columnar output formatting.
Zone layout:
Zones are 14 characters wide
Zone 1: columns 0-13
Zone 2: columns 14-27
Zone 3: columns 28-41
Zone 4: columns 42-55
Zone 5: columns 56-69
Behavior:
Calculates next zone boundary from current position
Prints spaces to reach that boundary
If already at boundary, advances to next zone
BASIC Usage: PRINT "NAME", "AGE", "CITY" PRINT A, B, C (values in columns)
Note
Zone width of 14 matches Applesoft BASIC convention
Definition at line 3017 of file interpreter.cpp.
References printText().
Referenced by PrintStmt::execute().
pushForLoop()
void Interpreter::pushForLoop (const std::string & varName, double endValue, double stepValue, LineNumber returnLine)
Push a new FOR loop onto the loop stack (FOR statement)
Creates and pushes a FOR loop control structure when a FOR statement is executed. The loop stack maintains nested loop state for proper NEXT processing.
Implementation details:
Stores loop variable name, end value, step value, and return line
Multiple nested FOR loops are supported through the stack
Each FOR creates a new stack entry even if variable name reused
NEXT processes loops from most recent (top of stack) backwards
BASIC Usage: FOR I = 1 TO 10 STEP 2 FOR J = 1 TO 5 ... NEXT J NEXT I
Stack behavior:
Nested loops push multiple entries
NEXT pops completed loops
Jumping out of loops leaves entries (cleaned by CLR or END)
Parameters
varName Loop control variable name
endValue Final value for loop (TO value)
stepValue Increment per iteration (STEP value, default 1)
returnLine Line number where FOR appears (for loop restart)
Definition at line 3079 of file interpreter.cpp.
Referenced by ForStmt::execute().
pushWhileLoop()
void Interpreter::pushWhileLoop (std::shared_ptr< Expression > condition, LineNumber returnLine)
Push WHILE loop state onto stack (WHILE implementation helper)
Records the current WHILE loop's condition and return point when entering a WHILE loop. This information is used by WEND to determine if the loop should continue or exit.
WHILE loop structure:
WHILE condition: Evaluate condition, push state if true
... loop body ...
WEND: Pop state, check condition, loop or exit
Stack entry contains:
condition: Expression to re-evaluate at WEND
returnLine: Line number to jump to if continuing
BASIC Usage: 10 X = 0 20 WHILE X < 10 30 PRINT X 40 X = X + 1 50 WEND
Parameters
condition Expression to evaluate for loop continuation
returnLine Line number to return to when continuing loop
Definition at line 3464 of file interpreter.cpp.
Referenced by WhileStmt::execute().
randomize()
void Interpreter::randomize (double seed)
Initialize random number generator (implicit RND behavior)
Seeds the random number generator used by RND() function. Uses Float40 for consistency with Applesoft BASIC's floating-point arithmetic.
Applesoft BASIC behavior:
RND(1) or RND(n > 0): next random number (doesn't reseed)
RND(0): repeat last random number
RND(n < 0): reseed with |n| and return first number
This function is called when negative argument to RND is used.
Parameters
seed Random seed value (typically negative when explicitly seeding)
Definition at line 3288 of file interpreter.cpp.
References Float40::setSeed().
Referenced by RandomizeStmt::execute().
readData()
Value Interpreter::readData ()
Read next value from DATA statements (READ implementation)
Returns the next value from the DATA cache and advances the data pointer. The DATA cache is built before program execution by scanning all DATA statements, regardless of where they appear in program flow.
BASIC Usage: READ A, B$, C
Behavior:
Returns next unread DATA value
Advances data pointer
Throws "OUT OF DATA ERROR" if no more data available
Works across multiple DATA statements
Not affected by program control flow (GOTO, IF, etc.)
Returns
Next value from DATA statements
Exceptions
std::runtime_error if no more data available
Definition at line 2718 of file interpreter.cpp.
Referenced by ShloadStmt::execute(), and ReadStmt::execute().
readFile()
void Interpreter::readFile (const std::string & filename, int record, int byte)
Open file for reading with optional positioning (READ implementation)
Opens a file for reading, optionally positioning to a specific record and byte offset. This implements the READ file command from ProDOS Applesoft BASIC (different from READ for DATA statements).
Positioning (currently stub):
record: 512-byte record number
byte: Byte offset within record
position = record * 512 + byte
Full positioning not yet implemented
Current behavior:
Opens file for reading via FileManager
Acknowledges the open operation
TODO: Implement actual file positioning
Error conditions:
Empty filename: "SYNTAX ERROR"
File not found: Propagated from FileManager
I/O error: Propagated from FileManager
Usage context:
ProDOS file I/O commands
Sequential or random access file reading
Use with subsequent READ operations
Parameters
filename Path to file to open for reading
record Record number for positioning (512-byte blocks)
byte Byte offset within record
Definition at line 3744 of file interpreter.cpp.
References FileManager::getInstance(), handleError(), FileManager::openFile(), and READ.
Referenced by ProdosReadStmt::execute().
recallArray()
void Interpreter::recallArray (const std::string & arrayName)
Load array from tape or disk (RECALL implementation)
Loads an array from cassette tape (if available) or from a disk file. This implements the RECALL command from Applesoft BASIC which was originally used for loading arrays from cassette tape.
Loading behavior:
If tape is set, reads next record from tape sequentially
Array name from tape record is used (parameter ignored for tape)
From disk, reads from <arrayname>.arr file
Creates array with DIM if it doesn't exist
Overwrites existing array data if it does exist
File format:
Same format as STORE command
Validates dimensions and data type
Checks for format corruption
Tape vs File:
Tape: Sequential reading, position maintained
File: Random access, reads specific array by name
Error conditions:
File not found (disk): "PATH NOT FOUND ERROR"
Invalid format: "INVALID TAPE FORMAT" or "INVALID ARRAY FILE FORMAT"
Dimension mismatch: Format validation error
I/O error: Propagated from filesystem or tape
BASIC Usage: RECALL A (load from tape or A.arr) RECALL B (load next array from tape, or B.arr from disk)
Parameters
arrayName Name of array to load (used for disk files)
Exceptions
std::runtime_error if file not found or format invalid
Definition at line 2180 of file interpreter.cpp.
References TapeManager::hasTape(), TapeManager::openForRead(), TapeManager::readRecord(), and Variables::setArrayData().
Referenced by RecallStmt::execute().
renameFile()
void Interpreter::renameFile (const std::string & oldName, const std::string & newName)
Rename a file (RENAME implementation)
Renames a file from oldName to newName. This implements the RENAME command from ProDOS Applesoft BASIC.
Error conditions:
Empty filename: "SYNTAX ERROR"
Source not found: "I/O ERROR"
Destination exists: "I/O ERROR"
Cross-device rename: Handled by filesystem layer
Usage in BASIC: RENAME "OLD","NEW" (or RENAME OLD.BAS, NEW.BAS)
Parameters
oldName Existing filename/path
newName New filename/path
Definition at line 1327 of file interpreter.cpp.
References handleError(), and renameFile().
Referenced by RenameFileStmt::execute(), executeImmediate(), and renameFile().
requireGraphicsMode()
void Interpreter::requireGraphicsMode () const
Verify graphics operations are allowed.
Check if graphics mode is enabled (internal helper)
Exceptions
RuntimeError if graphics disabled
Validates that graphics operations are allowed. Throws an error if graphics are disabled (–no-graphics flag). This is called by all graphics commands (GR, HGR, HPLOT, DRAW, etc.).
Error handling:
If graphics disabled: "GRAPHICS NOT ENABLED ERROR" with code 255
Error can be caught by ONERR handler
Allows programs to test for graphics availability
Usage context:
Called automatically by graphics commands
Not directly accessible from BASIC
Const method that modifies error state via const_cast (necessary for error reporting from const methods)
Exceptions
Uses handleError() which may throw or jump to ONERR handler
Definition at line 3567 of file interpreter.cpp.
References handleError(), and GraphicsConfig::isGraphicsEnabled().
Referenced by PlotStmt::execute(), HlinStmt::execute(), VlinStmt::execute(), HplotStmt::execute(), MoveStmt::execute(), RotateStmt::execute(), ScaleStmt::execute(), ShloadStmt::execute(), DrawStmt::execute(), XdrawStmt::execute(), HgrStmt::execute(), HcolorStmt::execute(), ColorStmt::execute(), GrStmt::execute(), and HiresStmt::execute().
resetOutputPosition()
void Interpreter::resetOutputPosition ()
Reset output position to column 1.
Reset output cursor position to home.
Resets the output cursor tracking to the top-left position (0,0) and clears all text attributes (inverse, flash). Called at the start of program execution and by screen-clearing operations.
Resets:
outputColumn_ = 0 (leftmost column)
outputRow_ = 0 (top row)
Text attributes to NORMAL (no inverse, no flash)
Used by:
Program startup (RUN command)
Screen clear operations
Initialize immediate mode
Definition at line 3043 of file interpreter.cpp.
References setNormal().
Referenced by clearState(), newProgram(), and runFrom().
restoreData()
void Interpreter::restoreData (int line = -1)
Reset DATA pointer (RESTORE implementation)
Resets the data pointer to the beginning of DATA statements or to a specific line number. This allows re-reading data values.
BASIC Usage: RESTORE (reset to beginning) RESTORE 1000 (reset to DATA on line 1000 or after)
Behavior:
RESTORE with no argument: reset to first DATA value
RESTORE line: reset to first DATA value at or after specified line
If line has no DATA, pointer set to end (OUT OF DATA on next READ)
Algorithm:
Uses dataOffsets_ map that links line numbers to positions in dataValues_
Searches for first line >= target line that has DATA
Sets dataPointer_ to corresponding position in dataValues_ array
Parameters
line Line number to restore to, or -1 for beginning
Definition at line 2747 of file interpreter.cpp.
Referenced by RestoreStmt::execute().
restoreVariables()
void Interpreter::restoreVariables (const std::string & filename)
Load all variables from a file (extension of Applesoft functionality)
Loads all scalar variables (numeric and string) from a text file previously saved with storeVariables(). This is an extension beyond standard Applesoft BASIC, providing persistent variable storage across sessions.
File format:
Must match format from storeVariables()
Validates version header "MSBASIC_VARS_V1"
Reads numeric variables first, then string variables
Escaped newlines (
) are unescaped
Behavior:
Existing variables with same names are overwritten
Variables not in file are preserved
Arrays are not affected (use RECALL for arrays)
Error conditions:
File not found: "PATH NOT FOUND ERROR"
Wrong format: "INVALID VARIABLE FILE FORMAT"
Corrupt data: "INVALID VARIABLE FILE FORMAT"
Example usage: CALL ... (implementation-specific call to restoreVariables) PRINT X, Y$ (variables restored from file)
Parameters
filename Path to file containing saved variables
Exceptions
std::runtime_error if file not found or format invalid
Definition at line 2497 of file interpreter.cpp.
References Variables::setVariable().
Referenced by ProdosRestoreStmt::execute().
resume()
void Interpreter::resume ()
Resume execution after error (RESUME implementation)
Returns execution to the line where an error occurred. Used in ONERR error handlers to retry the failed operation or continue from the error point.
BASIC Usage: 1000 ONERR GOTO 9000 ... 9000 REM ERROR HANDLER 9010 PRINT "ERROR: ";PEEK(218)+PEEK(219)*256 9020 RESUME
Behavior:
Jumps to the line number stored in errorLine_
Clears errorLine_ to prevent multiple RESUMEs
If no error active: "RESUME WITHOUT ERROR"
Note: Unlike some BASIC dialects, this implementation does not support RESUME NEXT (continue after error line). Only RESUME (retry error line).
Exceptions
std::runtime_error if no active error to resume from
Definition at line 3265 of file interpreter.cpp.
References gotoLine().
Referenced by ResumeStmt::execute().
returnFromGosub()
void Interpreter::returnFromGosub ()
Return from subroutine (RETURN)
Return from subroutine (RETURN implementation)
Exceptions
RuntimeError if GOSUB stack is empty
Pops return address from stack and continues execution.
Pops a line number from the GOSUB stack and continues execution at the line immediately following that line. This completes a GOSUB/RETURN pair.
Implementation details:
Pops the return line from the stack
Finds that line in the program
Advances to the NEXT line (incrementing the iterator)
Sets jumped_ flag to prevent further advancement
Special case: If the return line no longer exists (deleted after GOSUB), execution continues from the next available line.
Error handling:
Empty stack: "RETURN WITHOUT GOSUB ERROR"
Missing return line: Advances to next line if available
Exceptions
std::runtime_error if GOSUB stack is empty
Definition at line 886 of file interpreter.cpp.
Referenced by ReturnStmt::execute().
run()
void Interpreter::run ()
Run program from first line (RUN)
Execute program (RUN command implementation)
Initializes runtime state (clears variables, resets DATA pointer, clears stacks) and begins execution from first line.
Starts program execution from the first line. This is a convenience wrapper for runFrom(-1).
Definition at line 249 of file interpreter.cpp.
References runFrom().
Referenced by chainProgram(), chainProgram(), dashProgram(), executeImmediate(), and main().
runFrom()
void Interpreter::runFrom (LineNumber lineNum)
Run program from specified line (RUN n)
Execute program starting from specified line.
Parameters
lineNum Starting line number
Exceptions
RuntimeError if line not found
This is the main program execution loop implementing the Applesoft BASIC RUN and GOTO behaviors. It handles program flow, DATA caching, error trapping, and tracing.
Execution process:
Initialize execution state (running_ flag, immediate_ mode)
Build DATA cache by scanning all program lines
This ensures READ can access DATA regardless of program flow
dataOffsets_ maps line numbers to positions in dataValues_
Set program counter to starting line
Execute statements sequentially until:
END or STOP statement sets running_ = false
GOTO/GOSUB sets jumped_ flag
Error occurs
Program counter reaches end
Error Handling:
If ONERR handler is active (errorHandlerLine_ >= 0):
Records error line and message
Stores error info in memory locations 218-219 (line), 222 (code)
Jumps to error handler line
If no ONERR handler:
Prints error message and line number
Stops execution
Special Features:
TRACE mode: Prints [lineNumber] before executing each line
SPEED delay: Optional delay after each statement for debugging
Control flow: jumped_ flag coordinates with GOTO/GOSUB/RETURN
Parameters
lineNum Starting line number, or -1 to start from first line
Definition at line 286 of file interpreter.cpp.
References gotoLine(), peekMemory(), pokeMemory(), and resetOutputPosition().
Referenced by chainProgram(), executeImmediate(), and run().
saveProgram()
void Interpreter::saveProgram (const std::string & filename)
Save BASIC program to text file.
Save current program to disk (SAVE command implementation)
Parameters
filename Destination path for .bas file
Exceptions
RuntimeError on file I/O errors
Saves the current BASIC program to a text file. The file will contain line numbers followed by the BASIC code for each line.
BASIC Usage: SAVE "MYPROG.BAS"
File Format: Each line: <line_number><space>
Behavior:
Overwrites existing file without warning
Saves lines in sorted order by line number
On error, prints error message but doesn't stop interpreter
Parameters
filename Path where program will be saved
Definition at line 1096 of file interpreter.cpp.
References writeTextFile().
Referenced by executeImmediate().
setErrorHandler()
void Interpreter::setErrorHandler (LineNumber lineNum)
Set error handler line (ONERR GOTO implementation)
Enables error handling by setting the target line number for the ONERR handler. When an error occurs during program execution, control will jump to this line instead of terminating the program.
BASIC Usage: ONERR GOTO 9000 (enable error handler at line 9000)
Error handler behavior:
When error occurs, errorLine_ is set to the line where error happened
lastError_ contains the error message text
Memory location 218-219 contains error line number
Memory location 222 contains ProDOS error code
RESUME statement returns to the error line
Parameters
lineNum Target line number for error handler
Definition at line 3197 of file interpreter.cpp.
Referenced by OnErrStmt::execute().
setFlash()
void Interpreter::setFlash (bool on)
Enable flashing text mode (FLASH)
Enable flashing text mode (FLASH implementation)
Parameters
on true to enable, false to disable
Enables blinking/flashing text output. This implements the FLASH command from Applesoft BASIC.
Platform support:
Uses ANSI escape sequence \x1b[5m for blinking text
Windows: Requires virtual terminal support (enabled in constructor)
Unix/Linux: Works on terminals supporting ANSI codes
Note: Not all terminal emulators support blinking text
BASIC Usage: FLASH: PRINT "BLINKING" NORMAL: PRINT "STEADY"
Parameters
on true to enable flashing, false to disable
Definition at line 2861 of file interpreter.cpp.
Referenced by FlashStmt::execute().
setHimem()
void Interpreter::setHimem (int val) inline
Definition at line 406 of file interpreter.h.
References pokeMemory(), and setMemoryBounds().
Referenced by HimemStmt::execute().
setInputDevice()
void Interpreter::setInputDevice (int slot)
Set input device slot (IN# implementation)
Redirects input from a specific peripheral slot. This implements the IN# command from Applesoft BASIC which was used to select input devices like modems and serial interfaces.
Apple II slot assignments:
Slot 0: Keyboard (default input)
Slot 1-2: Serial/modem interfaces
Slot 3-7: Other peripherals
Current implementation:
All slots: Stored but no special behavior yet
Keyboard input always active
Future: Could redirect GET/INPUT to serial ports
BASIC Usage: IN#0 (keyboard input - default) IN#2 (serial port input - not fully implemented)
Parameters
slot Peripheral slot number (0-7)
Definition at line 3416 of file interpreter.cpp.
Referenced by InStmt::execute().
setInverse()
void Interpreter::setInverse (bool on)
Enable inverse video mode (INVERSE)
Enable inverse video mode (INVERSE implementation)
Parameters
on true to enable, false to disable
Enables inverse (reverse) video text output where foreground and background colors are swapped. This implements the INVERSE command from Applesoft BASIC.
Platform support:
Uses ANSI escape sequence \x1b[7m for inverse video
Windows: Requires virtual terminal support (enabled in constructor)
Unix/Linux: Works on any terminal supporting ANSI codes
BASIC Usage: INVERSE: PRINT "HIGHLIGHTED" NORMAL: PRINT "REGULAR"
Parameters
on true to enable inverse video, false to disable
Definition at line 2838 of file interpreter.cpp.
Referenced by InverseStmt::execute().
setLomem()
void Interpreter::setLomem (int val) inline
Definition at line 414 of file interpreter.h.
References pokeMemory(), and setMemoryBounds().
Referenced by LomemStmt::execute().
setNormal()
void Interpreter::setNormal ()
Return to normal video mode (NORMAL)
Reset text to normal mode (NORMAL implementation)
Disables both inverse and flash text modes, returning to normal text output. This implements the NORMAL command from Applesoft BASIC.
Behavior:
Clears inverse_ flag
Clears flash_ flag
Sends ANSI reset sequence \x1b[0m to terminal
BASIC Usage: INVERSE: PRINT "REVERSE" NORMAL: PRINT "REGULAR"
Definition at line 2881 of file interpreter.cpp.
Referenced by NormalStmt::execute(), and resetOutputPosition().
setOutputDevice()
void Interpreter::setOutputDevice (int slot)
Set output device slot (PR# implementation)
Redirects output to a specific peripheral slot. This implements the PR# (print) command from Applesoft BASIC which was used to select output devices like printers and 80-column cards.
Apple II slot assignments:
Slot 0: Internal screen (40-column text mode)
Slot 1-2: Serial/printer interfaces
Slot 3: 80-column card (switches to Text80 mode)
Slot 4-7: Other peripherals
Current implementation:
Slot 0: 40-column text mode
Slot 3: 80-column text mode
Other slots: Stored but no special behavior
BASIC Usage: PR#3 (switch to 80-column mode) PR#0 (switch back to 40-column mode) PR#1 (redirect to printer - not fully implemented)
Parameters
slot Peripheral slot number (0-7)
Definition at line 3349 of file interpreter.cpp.
References setTextMode(), Text40, and Text80.
Referenced by PrStmt::execute().
setPrefix()
void Interpreter::setPrefix (const std::string & path)
Set or show directory prefix (internal PREFIX helper)
Internal implementation of the PREFIX command. Dispatches to showPrefix() if path is empty, otherwise changes to the specified directory.
This is a convenience wrapper that handles the dual behavior of PREFIX:
PREFIX (no argument): Show current directory
PREFIX path: Change to directory
Parameters
path New directory path (empty to show current)
Definition at line 3589 of file interpreter.cpp.
References changePrefix(), and showPrefix().
Referenced by changePrefix(), and PrefixStmt::execute().
setSpeedDelay()
void Interpreter::setSpeedDelay (int delayMs)
Set statement execution delay (SPEED implementation)
Sets a delay in milliseconds that is applied after each statement execution. This implements the SPEED command from Applesoft BASIC, useful for debugging or creating animated effects.
BASIC Usage: SPEED=255 (maximum delay, very slow) SPEED=50 (moderate delay) SPEED=0 (no delay, full speed - default)
Delay range:
Minimum: 0 ms (no delay)
Maximum: 255 ms
Values outside range are clamped
The delay is applied via applySpeedDelay() called after each statement in the main execution loop.
Parameters
delayMs Delay in milliseconds (0-255)
Definition at line 3316 of file interpreter.cpp.
Referenced by SpeedStmt::execute().
setTapeFile()
void Interpreter::setTapeFile (const std::string & filename)
Definition at line 3826 of file interpreter.cpp.
References TapeManager::setTapeFile().
Referenced by TapeStmt::execute(), and main().
setTapeHotkey()
void Interpreter::setTapeHotkey (const std::string & hotkey) inline
Definition at line 477 of file interpreter.h.
Referenced by main().
setTextMode()
void Interpreter::setTextMode (TextMode mode)
Set text display mode (40 or 80 column)
Changes the text display mode between 40-column and 80-column modes. This is typically called by PR# command when switching between slot 0 (40-column) and slot 3 (80-column card).
Text modes:
Text40: Standard 40-column mode (classic Apple II)
Text80: 80-column mode (requires 80-column card in real hardware)
BASIC Usage: PR#3 (enables 80-column mode via setTextMode) PR#0 (returns to 40-column mode via setTextMode)
Future expansion:
Could update graphics renderer's text display
Could adjust line width for text wrapping
Mode is stored for PEEK/POKE compatibility
Parameters
mode Text display mode (Text40 or Text80)
Definition at line 3387 of file interpreter.cpp.
References GraphicsConfig::textMode.
Referenced by setOutputDevice().
setTrace()
void Interpreter::setTrace (bool on) inline
Definition at line 384 of file interpreter.h.
Referenced by TraceStmt::execute(), and NoTraceStmt::execute().
showPrefix()
void Interpreter::showPrefix ()
Print the current prefix (PREFIX with no argument)
Shows the current working directory (prefix in ProDOS terms). This implements the PREFIX command without arguments from ProDOS Applesoft BASIC.
Output format:
Absolute path to current directory (Unix-style by default, drive letters on Windows)
BASIC Usage: PREFIX (show current directory)
Definition at line 1352 of file interpreter.cpp.
References getCurrentPrefix().
Referenced by executeImmediate(), and setPrefix().
stop()
void Interpreter::stop ()
Stop program execution (STOP)
Pause program execution (STOP implementation)
Pauses program with "BREAK IN line" message. Can resume with CONT.
Suspends program execution but maintains state for continuation with CONT. Unlike END, STOP allows resuming execution from the next line.
State preservation:
Sets paused_ flag to indicate continuation is possible
Saves current line in continueAfterLine_
Clears running_ flag to exit execution loop
Preserves all variables, stacks, and program state
Used for:
Interactive debugging (insert STOP to examine variables)
Controlled program pauses
Breakpoint simulation
Example: 10 FOR I = 1 TO 10 20 PRINT I 30 IF I = 5 THEN STOP 40 NEXT I ' Can type CONT to resume from line 40
Definition at line 944 of file interpreter.cpp.
Referenced by StopStmt::execute().
storeArray()
void Interpreter::storeArray (const std::string & arrayName)
Save array to tape or disk (STORE implementation)
Saves an array to cassette tape (if available) or to a disk file. This implements the STORE command from Applesoft BASIC which was originally used for saving arrays to cassette tape.
Storage format (tape):
Array name length (1 byte) + name
Number of dimensions (1 byte)
Dimension sizes (4 bytes each, little-endian)
Data type flag (1 byte: 0=numeric, 1=string)
Array elements (8 bytes for numbers, length+chars for strings)
Storage format (disk):
Same format but saved to <arrayname>.arr file
Filename is sanitized (removes $, %, special chars)
Behavior:
If tape is set (via TAPE command), writes to tape
Otherwise creates .arr file in current directory
Tape maintains position (sequential writes)
Disk creates new file each time (overwrites)
Error conditions:
Array not defined: "UNDEFINED ARRAY ERROR"
I/O error: "FILE ERROR" or tape error
BASIC Usage: DIM A(100) STORE A (save to tape or A.arr)
Parameters
arrayName Name of array to save
Exceptions
std::runtime_error if array undefined or I/O error
Definition at line 2013 of file interpreter.cpp.
References Variables::getArrayData(), Variables::getArrayDimensions(), Variables::hasArray(), TapeManager::hasTape(), TapeManager::openForWrite(), and TapeManager::writeRecord().
Referenced by StoreStmt::execute().
storeVariables()
void Interpreter::storeVariables (const std::string & filename)
Save all variables to a file (extension of Applesoft functionality)
Saves all scalar variables (numeric and string) to a text file. This is an extension beyond standard Applesoft BASIC, providing persistent variable storage across sessions.
File format:
Header: "MSBASIC_VARS_V1"
Numeric variable count
Each numeric variable: name value
String variable count
Each string variable: name value (with escaped newlines as
)
Usage:
Save game state or configuration
Checkpoint long-running calculations
Transfer data between programs
Note: Arrays are not included (use STORE for arrays)
Error conditions:
Cannot create file: "I/O ERROR"
Write error: "I/O ERROR"
Example usage: X = 100: Y$ = "TEST" CALL ... (implementation-specific call to storeVariables)
Parameters
filename Path to file where variables will be saved
Exceptions
std::runtime_error if file cannot be created or written
Definition at line 2430 of file interpreter.cpp.
References Variables::getAllNumericVariables(), and Variables::getAllStringVariables().
Referenced by ProdosStoreStmt::execute().
unlockFile()
void Interpreter::unlockFile (const std::string & filename)
Unlock a file (UNLOCK implementation)
Removes the lock on a file, allowing it to be modified or deleted. This implements the UNLOCK command from ProDOS Applesoft BASIC. Platform behavior varies by OS; this implementation provides a graceful stub.
Error conditions:
Empty filename: "SYNTAX ERROR"
File not found: "I/O ERROR"
Permission denied: "I/O ERROR"
BASIC Usage: UNLOCK "IMPORTANT.DAT"
Parameters
filename Path to file to unlock
Definition at line 1633 of file interpreter.cpp.
References FileManager::getInstance(), handleError(), and unlockFile().
Referenced by UnlockFileStmt::execute(), executeImmediate(), and unlockFile().
vtab()
void Interpreter::vtab (int row1)
Move cursor to row (VTAB)
Move cursor to vertical row (VTAB implementation)
Parameters
row1 Row number (1-based, 1-24)
Moves the cursor to the specified row by printing newlines. This implements the VTAB (vertical tab) command from Applesoft BASIC.
Behavior:
Row numbers are 1-based (VTAB 1 = top row)
If target row is above current position, does nothing
If target row is below current position, prints newlines to reach it
Updates memory location 0x0025 (37) with current cursor row
BASIC Usage: VTAB 10: PRINT "TEXT" (print starting at row 10) VTAB 1 (return to top of screen) HTAB 1: VTAB 1 (home cursor to top-left)
Memory Update:
Location 37 ($25): Cursor vertical position (0-based internally)
Parameters
row1 Target row (1-based, 1 = top)
Definition at line 2812 of file interpreter.cpp.
References pokeMemory(), and printNewline().
Referenced by VtabStmt::execute().
writeFile()
void Interpreter::writeFile (const std::string & filename, int record)
Open file for writing with optional positioning (WRITE implementation)
Opens a file for writing, optionally positioning to a specific record number. This implements the WRITE file command from ProDOS Applesoft BASIC (different from WRITE for OUTPUT operations).
Positioning (currently stub):
record: 512-byte record number
Full positioning not yet implemented
Currently opens file for writing at beginning
Current behavior:
Opens file for writing via FileManager
Acknowledges the open operation
TODO: Implement actual record positioning
Error conditions:
Empty filename: "SYNTAX ERROR"
Cannot create file: Propagated from FileManager
I/O error: Propagated from FileManager
Usage context:
ProDOS file I/O commands
Sequential or random access file writing
Use with subsequent WRITE operations
Parameters
filename Path to file to open for writing
record Record number for positioning (512-byte blocks)
Definition at line 3798 of file interpreter.cpp.
References FileManager::getInstance(), handleError(), FileManager::openFile(), and WRITE.
Referenced by ProdosWriteStmt::execute().
The documentation for this class was generated from the following files:
src/interpreter.h
src/interpreter.cpp