MSBasic - Applesoft BASIC Interpreter: GraphicsRenderer Class Reference
GraphicsRenderer Class Reference
Platform-specific graphics rendering implementation.
#include <graphics_renderer.h>
Public Member Functions
GraphicsRenderer (const GraphicsConfig &config)
Construct renderer with configuration.
~GraphicsRenderer ()
Destructor, calls shutdown if needed.
bool initialize ()
Initialize window and resources.
void shutdown ()
Shutdown renderer and close window.
bool isInitialized () const
Check if renderer is initialized.
bool shouldClose () const
Check if user requested window close.
void beginFrame ()
Begin rendering frame.
void endFrame ()
End rendering frame and present to screen.
void clear ()
Clear screen to black.
void drawPixel (int x, int y, int color)
Draw single pixel.
void drawText (const std::string &text, int x, int y, int color)
Draw text string.
void drawChar (char ch, int x, int y, int color)
Draw single character.
int getWindowWidth () const
Get window width.
int getWindowHeight () const
Get window height.
int getScaleFactor () const
Get scale factor from configuration.
Detailed Description
Platform-specific graphics rendering implementation.
Implements window management and rendering operations using Raylib. Provides pixel drawing, text rendering with Apple II font, and frame management for the Graphics subsystem.
Lifecycle:
Construct with GraphicsConfig
Call initialize() to create window and load resources
Call beginFrame() before drawing
Perform drawing operations (drawPixel, drawText, etc.)
Call endFrame() to present frame
Call shutdown() when done
The renderer maintains window state and handles platform-specific rendering details, isolating the Graphics class from platform APIs.
Definition at line 65 of file graphics_renderer.h.
Constructor & Destructor Documentation
GraphicsRenderer()
GraphicsRenderer::GraphicsRenderer (const GraphicsConfig & config)
Construct renderer with configuration.
Construct a GraphicsRenderer.
Parameters
config Graphics configuration (mode, scale, text mode)
config Graphics configuration (scale, mode, etc.)
Definition at line 46 of file graphics_renderer.cpp.
~GraphicsRenderer()
GraphicsRenderer::~GraphicsRenderer ()
Destructor, calls shutdown if needed.
Destructor - ensures proper cleanup.
Calls shutdown() so any renderer resources (window/font) are released even if the owning subsystem exits early.
Definition at line 61 of file graphics_renderer.cpp.
References shutdown().
Member Function Documentation
beginFrame()
void GraphicsRenderer::beginFrame ()
Begin rendering frame.
Begin a new render frame.
Call before any drawing operations. Prepares rendering context.
Starts a new rendering frame. When compiled with Raylib support and the renderer is initialized, this wraps Raylib's BeginDrawing() and prepares the frame for drawing operations. When rendering is unavailable (Raylib not compiled in, graphics disabled, or initialization failed) this function is a no-op.
Typical usage pattern: beginFrame(); clear(); drawPixel()/drawText()/drawChar(); endFrame();
Definition at line 180 of file graphics_renderer.cpp.
clear()
void GraphicsRenderer::clear ()
Clear screen to black.
Clear the frame buffer to the Apple II background color.
Fills entire window with black. Typically called at start of frame.
Clears the drawing surface to black, matching the Apple II's default graphics background. When compiled with Raylib support and initialized, this calls ClearBackground(BLACK); otherwise it is a no-op.
Definition at line 211 of file graphics_renderer.cpp.
drawChar()
void GraphicsRenderer::drawChar (char ch, int x, int y, int color)
Draw single character.
Draw a single character in graphics coordinates.
Parameters
ch Character to render
x X position (pixels)
y Y position (pixels)
color Apple II color value
Renders single character using Apple II font.
Draws a single glyph at the specified logical coordinates. When the Apple II font is loaded, this renders the character using DrawTextEx to preserve authentic appearance; otherwise it falls back to drawText(). The renderer applies scaling according to config_.scaleFactor and supports horizontal 0.5× compression when in 80-column mode.
Color is provided as a packed 0xRRGGBB value and converted to a Raylib Color with full opacity.
Parameters
ch Character to draw
x Logical X coordinate in pixels
y Logical Y coordinate in pixels
color Packed 0xRRGGBB color
Definition at line 329 of file graphics_renderer.cpp.
References drawText(), GraphicsConfig::scaleFactor, Text80, and GraphicsConfig::textMode.
drawPixel()
void GraphicsRenderer::drawPixel (int x, int y, int color)
Draw single pixel.
Draw a single Apple II pixel at logical coordinates.
Parameters
x X coordinate (window coordinates)
y Y coordinate (window coordinates)
color Apple II color value
Draws a pixel in Apple II color at the specified position.
Draws a pixel at the given logical coordinates using a filled rectangle sized by config_.scaleFactor to achieve pixel-perfect scaling on modern displays. Color is provided as a packed 0xRRGGBB value and rendered as an opaque color.
Parameters
x Logical X coordinate in Apple II space
y Logical Y coordinate in Apple II space
color Packed 0xRRGGBB color
Definition at line 232 of file graphics_renderer.cpp.
References GraphicsConfig::scaleFactor.
drawText()
void GraphicsRenderer::drawText (const std::string & text, int x, int y, int color)
Draw text string.
Draw a text string in graphics coordinates.
Parameters
text String to render
x X position (pixels)
y Y position (pixels)
color Apple II color value
Renders text using Apple II font at specified position.
Renders text using the loaded Apple II font when available. In 80-column mode, text is horizontally compressed (0.5x) to emulate 80-column rendering. Falls back to Raylib's built-in font if the custom font is not available.
Parameters
text UTF-8 text string to render
x Logical X coordinate in pixels
y Logical Y coordinate in pixels
color Packed 0xRRGGBB color
Definition at line 262 of file graphics_renderer.cpp.
References GraphicsConfig::scaleFactor, Text80, and GraphicsConfig::textMode.
Referenced by drawChar().
endFrame()
void GraphicsRenderer::endFrame ()
End rendering frame and present to screen.
End the current render frame.
Finalizes frame and swaps buffers. Call after all drawing operations.
Ends and presents the current rendering frame. When compiled with Raylib support and the renderer is initialized, this wraps Raylib's EndDrawing() to finalize and display the frame. When rendering is unavailable this function is a no-op.
Definition at line 196 of file graphics_renderer.cpp.
getScaleFactor()
int GraphicsRenderer::getScaleFactor () const inline
Get scale factor from configuration.
Returns
Scale multiplier
Definition at line 185 of file graphics_renderer.h.
References GraphicsConfig::scaleFactor.
getWindowHeight()
int GraphicsRenderer::getWindowHeight () const inline
Get window height.
Returns
Window height in pixels
Definition at line 179 of file graphics_renderer.h.
getWindowWidth()
int GraphicsRenderer::getWindowWidth () const inline
Get window width.
Returns
Window width in pixels
Definition at line 173 of file graphics_renderer.h.
initialize()
bool GraphicsRenderer::initialize ()
Initialize window and resources.
Initialize the graphics window and renderer.
Returns
true if initialization successful
Creates window, loads Apple II font, sets up rendering context. Must be called before any drawing operations.
Creates a Raylib window scaled to the configured factor (default 2x). Base resolution is 280×192 matching Apple II high-res mode.
Performs checks:
Verifies DISPLAY environment variable (Unix/Linux)
Tests window creation success
Loads Apple II font if available
Returns false if initialization fails, allowing off-screen operation.
Returns
true if window created successfully, false otherwise
Definition at line 78 of file graphics_renderer.cpp.
References GraphicsConfig::isGraphicsEnabled(), and GraphicsConfig::scaleFactor.
isInitialized()
bool GraphicsRenderer::isInitialized () const inline
Check if renderer is initialized.
Returns
true if initialize() succeeded and window is open
Definition at line 100 of file graphics_renderer.h.
shouldClose()
bool GraphicsRenderer::shouldClose () const
Check if user requested window close.
Returns
true if window close button clicked
true if window close requested, false otherwise
Definition at line 156 of file graphics_renderer.cpp.
shutdown()
void GraphicsRenderer::shutdown ()
Shutdown renderer and close window.
Shutdown and cleanup the renderer.
Releases resources and closes window. Safe to call multiple times.
Unloads fonts, closes the window, and marks renderer as uninitialized. Safe to call multiple times.
Definition at line 138 of file graphics_renderer.cpp.
Referenced by ~GraphicsRenderer().
The documentation for this class was generated from the following files:
src/graphics_renderer.h
src/graphics_renderer.cpp