MSBasic - Applesoft BASIC Interpreter: Variables Class Reference
Variables Class Reference
Storage and management for program variables, arrays, and functions.
#include <variables.h>
Classes
struct FunctionInfo
Storage for user-defined function details.
Public Member Functions
Variables ()
Construct a new Variables storage system.
void setVariable (const std::string &name, const Value &value)
Set a variable's value.
void unsetVariable (const std::string &name)
Remove a variable.
Value getVariable (const std::string &name)
Get a variable's value.
bool hasVariable (const std::string &name) const
Check if a variable exists.
void clear ()
Clear all variables, arrays, and functions.
void dimArray (const std::string &name, const std::vector< int > &dimensions)
Dimension an array with specified sizes.
void setArrayElement (const std::string &name, const std::vector< int > &indices, const Value &value)
Set an array element's value.
Value getArrayElement (const std::string &name, const std::vector< int > &indices)
Get an array element's value.
void defineFunction (const std::string &name, const std::string &param, const std::shared_ptr< Expression > &expr)
Define a user function (DEF FN)
bool hasFunction (const std::string &name) const
Check if a function is defined.
const FunctionInfo & getFunction (const std::string &name)
Get function definition.
bool hasArray (const std::string &name) const
Check if an array exists.
const std::vector< int > & getArrayDimensions (const std::string &name) const
Get array dimensions.
const std::map< std::vector< int >, Value > & getArrayData (const std::string &name) const
Get array data (for persistence)
void setArrayData (const std::string &name, const std::vector< int > &dimensions, const std::map< std::vector< int >, Value > &data)
Set array data (for restoration)
std::map< std::string, double > getAllNumericVariables () const
Get all numeric variables.
std::map< std::string, std::string > getAllStringVariables () const
Get all string variables.
Detailed Description
Storage and management for program variables, arrays, and functions.
The Variables class implements the variable storage system for MSBasic, following Applesoft BASIC conventions for variable names and types.
Variable naming rules:
Only first 2 characters are significant (case-insensitive)
Exception: FN names preserve FN prefix + 2 chars (e.g., FNxy)
'$' suffix denotes string variables
'' suffix denotes integer variables (16-bit clamped)
Arrays:
Multi-dimensional with arbitrary dimension count
Auto-dimension to size 10 per dimension if undeclared
Sparse storage using std::map for memory efficiency
Bounds checking with "BAD SUBSCRIPT" error
User-defined functions:
Stored with parameter name and expression AST
Evaluated by substituting parameter value
Follow FN naming conventions
Definition at line 51 of file variables.h.
Constructor & Destructor Documentation
Variables()
Variables::Variables ()
Construct a new Variables storage system.
Definition at line 32 of file variables.cpp.
Member Function Documentation
clear()
void Variables::clear ()
Clear all variables, arrays, and functions.
Clear all variables and arrays.
Resets the Variables object to initial state. Called by CLR command.
Removes all variables and arrays from memory. User-defined functions (DEF FN) are preserved, matching Applesoft BASIC behavior where functions persist across CLEAR commands.
This is called by the CLR and NEW commands.
Definition at line 186 of file variables.cpp.
Referenced by Interpreter::clearState(), and Interpreter::newProgram().
defineFunction()
void Variables::defineFunction (const std::string & name, const std::string & param, const std::shared_ptr< Expression > & expr)
Define a user function (DEF FN)
Define a user function (DEF FN implementation)
Stores a user-defined function with its parameter and body expression. Function calls will substitute the parameter value and evaluate the body.
Parameters
name Function name (e.g., "FNxy")
param Parameter name (e.g., "x")
expr Expression AST for the function body
Stores a user-defined function definition for later evaluation. Functions defined with DEF FN can be called like built-in functions.
Function definition:
Function name must start with "FN" (e.g., FNxy, FNa, FNmax)
Single parameter (Applesoft limitation)
Expression can reference parameter and global variables
Function naming:
Name normalized to FN + 2 chars (FNxy, not FNxyz)
Case insensitive: FNA, FNa, Fna are the same
Normalized before storage for consistent lookup
Function storage:
Functions stored separately from variables
Functions persist across CLR (variables cleared, functions kept)
NEW command clears functions along with everything else
Redefining a function replaces the previous definition
Function evaluation:
Function call FNxy(10) substitutes parameter with value 10
Expression evaluated in context with parameter substituted
Can reference and modify global variables
Recursive calls supported but uncommon
Examples: DEF FNA(X) = X * X DEF FNB(Y) = SQR(Y * Y + 1) DEF FNC(Z) = INT(Z + 0.5)
Parameters
name Function name (e.g., "FNXY") - normalized internally
param Parameter variable name (e.g., "X")
expr Function body expression AST
Definition at line 394 of file variables.cpp.
References Variables::FunctionInfo::body, and Variables::FunctionInfo::parameter.
Referenced by DefStmt::execute().
dimArray()
void Variables::dimArray (const std::string & name, const std::vector< int > & dimensions)
Dimension an array with specified sizes.
Creates a new array with the given dimensions. Arrays are stored sparsely - elements are created on demand.
Parameters
name Array name (normalized)
dimensions Vector of dimension sizes (each must be > 0)
Exceptions
std::runtime_error if array already dimensioned (REDIM error)
Explicitly dimensions an array to specified sizes per dimension. This is called by the DIM statement or automatically on first array use.
Array index behavior:
Indices start at 0 and go to dimension size (inclusive)
DIM A(10) creates indices 0-10 (11 elements)
Multi-dimensional: DIM A(5,5) creates 6×6 grid (indices 0-5)
Auto-dimensioning:
If array accessed before DIM, auto-dimensioned to size 10 per dimension
Auto-dimensioning matches Applesoft BASIC behavior
Explicit DIM overrides auto-dimension (if array not yet used)
Memory management:
Uses sparse storage (only stores non-default values)
Clearing array data frees all element storage
Redimensioning clears existing array data
Error conditions:
Cannot redimension an array that's already in use (REDIM'D ARRAY ERROR)
Handled by caller (DimStmt) to check if array exists
Parameters
name Array name (normalized internally)
dimensions Vector of dimension sizes (e.g., [10] for 1D, [5,5] for 2D)
Definition at line 220 of file variables.cpp.
Referenced by DimStmt::execute(), getArrayElement(), and setArrayElement().
getAllNumericVariables()
std::map< std::string, double > Variables::getAllNumericVariables () const
Get all numeric variables.
Returns a map of all numeric (non-string, non-integer) variables for saving to disk via ProDOS STORE command.
Returns
std::map<std::string, double> Map of variable names to values
Returns a map of all numeric variables (non-string) for iteration or inspection. Used for debugging and state export.
Returns
Map of normalized variable names to numeric values
Definition at line 516 of file variables.cpp.
Referenced by Interpreter::storeVariables().
getAllStringVariables()
std::map< std::string, std::string > Variables::getAllStringVariables () const
Get all string variables.
Returns a map of all string variables (names ending in $) for saving to disk via ProDOS STORE command.
Returns
std::map<std::string, std::string> Map of variable names to values
Returns a map of all string variables for iteration or inspection. Used for debugging and state export.
Returns
Map of normalized variable names to string values
Definition at line 534 of file variables.cpp.
Referenced by Interpreter::storeVariables().
getArrayData()
const std::map< std::vector< int >, Value > & Variables::getArrayData (const std::string & name) const
Get array data (for persistence)
Get array data storage.
Returns the sparse map of array elements for saving to disk.
Parameters
name Array name
Returns
const std::map<std::vector<int>, Value>& Array element map
Exceptions
std::runtime_error if array doesn't exist
Returns the sparse array data map. Array elements are stored as map entries keyed by dimension indices. Uninitialized elements are not stored (sparse storage).
Parameters
name Array name
Returns
Map of dimension indices to values
Exceptions
std::runtime_error if array not defined
Definition at line 480 of file variables.cpp.
Referenced by Interpreter::storeArray().
getArrayDimensions()
const std::vector< int > & Variables::getArrayDimensions (const std::string & name) const
Get array dimensions.
Parameters
name Array name
Returns
const std::vector<int>& Vector of dimension sizes
Exceptions
std::runtime_error if array doesn't exist
Returns the dimension sizes for a dimensioned array.
Example: DIM A(5,10) creates array with dimensions [5, 10]
Parameters
name Array name
Returns
Vector of dimension sizes
Exceptions
std::runtime_error if array not defined
Definition at line 459 of file variables.cpp.
Referenced by Interpreter::storeArray().
getArrayElement()
Value Variables::getArrayElement (const std::string & name, const std::vector< int > & indices)
Get an array element's value.
Get an array element value.
Auto-dimensions the array to size 10 per dimension if not yet declared. Returns Value(0.0) for uninitialized numeric elements.
Parameters
name Array name
indices Subscript values for each dimension
Returns
Value The element's value
Exceptions
std::runtime_error on bad subscript (out of bounds)
Retrieves the value of a specific array element identified by indices. Automatically dimensions the array if not yet dimensioned (size 10 per dimension). Performs bounds checking and returns default values for uninitialized elements.
Auto-dimensioning:
If array not explicitly DIM'd, auto-dimensions to size 10
Matches Applesoft BASIC behavior for undeclared arrays
Multi-dimensional arrays auto-dimension each axis to 10
Default values:
Uninitialized numeric array elements return 0.0
Uninitialized string array elements return ""
Sparse storage: only explicitly set elements consume memory
Bounds checking:
Each index must be >= 0 and <= dimension size
Accessing A(11) when DIM A(10) raises "BAD SUBSCRIPT ERROR"
All dimensions checked before access
Type handling:
Numeric arrays return numeric values
String arrays (name ending with $) return string values
Integer arrays (name ending with %) return clamped integers
Examples: X = A(5) (1D array access) Y = B(2,3) (2D array access) S$ = C$(I) (string array) N% = D%(10) (integer array)
Parameters
name Array name
indices Vector of indices (one per dimension)
Returns
Array element value, or default (0 or "") if uninitialized
Exceptions
std::runtime_error if any index out of bounds ("BAD SUBSCRIPT ERROR")
Definition at line 326 of file variables.cpp.
References dimArray().
Referenced by ArrayAccessExpr::evaluate().
getFunction()
const Variables::FunctionInfo & Variables::getFunction (const std::string & name)
Get function definition.
Get user-defined function definition.
Parameters
name Function name
Returns
const FunctionInfo& Function details
Exceptions
std::runtime_error if function not defined
Retrieves the function definition for evaluation. Function calls substitute the parameter value and evaluate the function body expression.
Parameters
name Function name (e.g., "FNXY")
Returns
Function information (parameter name and body expression)
Exceptions
std::runtime_error if function is not defined
Definition at line 425 of file variables.cpp.
Referenced by UserFunctionCallExpr::evaluate().
getVariable()
Value Variables::getVariable (const std::string & name)
Get a variable's value.
Get a variable value.
Parameters
name Variable name to lookup
Returns
Value The variable's current value
Exceptions
std::runtime_error if variable doesn't exist
Retrieves the value of a variable. Returns default values for uninitialized variables following Applesoft BASIC conventions:
String variables ($): empty string ""
Numeric variables: 0.0
Examples: getVariable("X") → returns 0.0 if X not set getVariable("NAME$") → returns "" if NAME$ not set getVariable("COUNT%") → returns 0 if COUNT% not set
Parameters
name Variable name to retrieve
Returns
Variable value, or default if uninitialized
Definition at line 150 of file variables.cpp.
Referenced by VariableExpr::evaluate(), and Interpreter::nextForLoop().
hasArray()
bool Variables::hasArray (const std::string & name) const
Check if an array exists.
Check if an array has been dimensioned.
Parameters
name Array name to check
Returns
true if array is dimensioned, false otherwise
Tests whether an array has been explicitly dimensioned with DIM or auto-dimensioned by first use.
Parameters
name Array name
Returns
true if array exists, false otherwise
Definition at line 443 of file variables.cpp.
Referenced by Interpreter::storeArray().
hasFunction()
bool Variables::hasFunction (const std::string & name) const
Check if a function is defined.
Check if a user-defined function exists.
Parameters
name Function name to check
Returns
true if function is defined, false otherwise
Tests whether a function has been defined with DEF FN.
Parameters
name Function name (e.g., "FNXY")
Returns
true if function is defined, false otherwise
Definition at line 411 of file variables.cpp.
hasVariable()
bool Variables::hasVariable (const std::string & name) const
Check if a variable exists.
Parameters
name Variable name to check
Returns
true if variable is defined, false otherwise
Tests whether a variable has been explicitly set. Returns false for variables that would return default values (0 or "").
Parameters
name Variable name to check
Returns
true if variable has been set, false otherwise
Definition at line 173 of file variables.cpp.
setArrayData()
void Variables::setArrayData (const std::string & name, const std::vector< int > & dimensions, const std::map< std::vector< int >, Value > & data)
Set array data (for restoration)
Set array data (bulk restore)
Replaces array contents with loaded data. Used by RECALL command.
Parameters
name Array name
dimensions Dimension sizes
data Map of element values
Sets the complete array dimensions and data. Used by RECALL command to restore arrays from tape storage.
Parameters
name Array name
dimensions Array dimension sizes
data Complete array data map
Definition at line 499 of file variables.cpp.
Referenced by Interpreter::recallArray().
setArrayElement()
void Variables::setArrayElement (const std::string & name, const std::vector< int > & indices, const Value & value)
Set an array element's value.
Set an array element value.
Auto-dimensions the array to size 10 per dimension if not yet declared. Creates the element if it doesn't exist.
Parameters
name Array name
indices Subscript values for each dimension
value The value to store
Exceptions
std::runtime_error on bad subscript (out of bounds)
Sets the value of a specific array element identified by indices. Automatically dimensions the array if not yet dimensioned (size 10 per dimension). Performs bounds checking and raises error if indices out of range.
Auto-dimensioning:
If array not explicitly DIM'd, auto-dimensions to size 10
Example: A(5) = 10 auto-creates A with indices 0-10
Multi-dimensional arrays auto-dimension each axis to 10
Integer coercion:
Array names ending with % store integer values
Values are clamped to 16-bit signed range (-32768 to 32767)
Matches Applesoft BASIC integer variable behavior
Sparse storage:
Only explicitly set elements are stored in memory
Unset elements return default values (0 or "")
Efficient for large arrays with few used elements
Examples: A(5) = 100 (1D array access) B(2,3) = 50 (2D array access) C$(I) = "HELLO" (string array) D%(10) = 32000 (integer array)
Parameters
name Array name
indices Vector of indices (one per dimension)
value Value to store
Exceptions
std::runtime_error if any index out of bounds ("BAD SUBSCRIPT ERROR")
Definition at line 261 of file variables.cpp.
References dimArray().
Referenced by ArrayLetStmt::execute(), and ReadStmt::execute().
setVariable()
void Variables::setVariable (const std::string & name, const Value & value)
Set a variable's value.
Set a variable value.
Creates the variable if it doesn't exist, or updates its value. Variable name is normalized according to Applesoft conventions.
Parameters
name Variable name (may include $, %, or FN prefix)
value The value to store
Exceptions
std::runtime_error on type mismatch (e.g., string to numeric)
Stores a value in a variable, applying type coercion for integer variables. Variable names are normalized according to Applesoft rules (2-char significance).
Type handling:
Integer variables (name ends with %): value is clamped to 16-bit signed range
String variables (name ends with $): value stored as-is
Numeric variables: value stored as-is (Float40 precision)
Examples: setVariable("COUNTER%", 100) → stores 100 as integer setVariable("NAME$", "HELLO") → stores "HELLO" as string setVariable("X", 3.14159) → stores 3.14159 as number
Parameters
name Variable name (may include $ or % suffix)
value Value to store (type coercion applied for %)
Definition at line 114 of file variables.cpp.
Referenced by LetStmt::execute(), ForStmt::execute(), InputStmt::execute(), ReadStmt::execute(), GetStmt::execute(), Interpreter::nextForLoop(), and Interpreter::restoreVariables().
unsetVariable()
void Variables::unsetVariable (const std::string & name)
Remove a variable.
Remove a variable from storage.
Parameters
name Variable name to remove
Deletes a variable from memory. If the variable doesn't exist, this operation silently succeeds.
Parameters
name Variable name to remove
Definition at line 130 of file variables.cpp.
The documentation for this class was generated from the following files:
src/variables.h
src/variables.cpp