MSBasic - Applesoft BASIC Interpreter: Float40 Class Reference
Float40 Class Reference
Applesoft-compatible 40-bit floating point number.
#include <float40.h>
Public Member Functions
Float40 ()
Default constructor, initializes to zero.
Float40 (double value)
Construct from double value.
Float40 (int value)
Construct from integer value.
Float40 (const std::string &str)
Construct from string representation.
double toDouble () const
Convert to standard double.
std::string toString () const
Convert to Applesoft-style string.
Float40 operator+ (const Float40 &other) const
Addition operator.
Float40 operator- (const Float40 &other) const
Subtraction operator.
Float40 operator* (const Float40 &other) const
Multiplication operator.
Float40 operator/ (const Float40 &other) const
Division operator.
Float40 operator- () const
Unary negation operator.
bool operator== (const Float40 &other) const
Equality comparison.
bool operator!= (const Float40 &other) const
Inequality comparison.
bool operator< (const Float40 &other) const
Less than comparison.
bool operator> (const Float40 &other) const
Greater than comparison.
bool operator<= (const Float40 &other) const
Less than or equal comparison.
bool operator>= (const Float40 &other) const
Greater than or equal comparison.
Float40 power (const Float40 &exponent) const
Exponentiation (^)
Float40 mod (const Float40 &divisor) const
Modulo operation (MOD)
Float40 abs () const
Absolute value (ABS)
Float40 sgn () const
Sign function (SGN)
Float40 intPart () const
Integer part (INT)
Float40 sin () const
Sine function (SIN)
Float40 cos () const
Cosine function (COS)
Float40 tan () const
Tangent function (TAN)
Float40 atn () const
Arctangent function (ATN)
Float40 exp () const
Exponential function (EXP)
Float40 log () const
Natural logarithm (LOG)
Float40 sqr () const
Square root (SQR)
Static Public Member Functions
static Float40 rnd (const Float40 &seed)
Generate random number (RND)
static void setSeed (const Float40 &seed)
Set random number seed.
Detailed Description
Applesoft-compatible 40-bit floating point number.
Implements the 5-byte floating point format used by Applesoft BASIC, providing arithmetic operations and math functions with precision matching the original Apple II implementation.
Usage:
Float40 a(3.14159);
Float40 b("2.71828");
Float40 result = a * b;
std::cout << result.toString() << std::endl;
Definition at line 47 of file float40.h.
Constructor & Destructor Documentation
Float40() [1/4]
Float40::Float40 ()
Default constructor, initializes to zero.
Definition at line 43 of file float40.cpp.
Referenced by abs(), atn(), cos(), exp(), intPart(), log(), mod(), operator*(), operator+(), operator-(), operator-(), operator/(), power(), rnd(), sgn(), sin(), sqr(), and tan().
Float40() [2/4]
Float40::Float40 (double value) explicit
Construct from double value.
Parameters
value Initial value
Definition at line 45 of file float40.cpp.
Float40() [3/4]
Float40::Float40 (int value) explicit
Construct from integer value.
Parameters
value Initial value
Definition at line 47 of file float40.cpp.
Float40() [4/4]
Float40::Float40 (const std::string & str) explicit
Construct from string representation.
Parameters
str Numeric string (e.g., "3.14", "1.5E10")
Definition at line 49 of file float40.cpp.
Member Function Documentation
abs()
Float40 Float40::abs () const
Absolute value (ABS)
Returns
Absolute value
Definition at line 151 of file float40.cpp.
References Float40().
Referenced by funcAbs().
atn()
Float40 Float40::atn () const
Arctangent function (ATN)
Returns
Arctangent of value in radians
Definition at line 169 of file float40.cpp.
References Float40().
Referenced by funcAtn().
cos()
Float40 Float40::cos () const
Cosine function (COS)
Returns
Cosine of value (value in radians)
Definition at line 165 of file float40.cpp.
References Float40().
Referenced by funcCos().
exp()
Float40 Float40::exp () const
Exponential function (EXP)
Returns
e raised to this value
Definition at line 171 of file float40.cpp.
References Float40().
Referenced by funcExp().
intPart()
Float40 Float40::intPart () const
Integer part (INT)
Returns
Largest integer not greater than value (floor)
Definition at line 161 of file float40.cpp.
References Float40().
Referenced by funcInt().
log()
Float40 Float40::log () const
Natural logarithm (LOG)
Returns
Natural logarithm of value
Exceptions
RuntimeError if value <= 0
Definition at line 173 of file float40.cpp.
References Float40().
Referenced by funcLog().
mod()
Float40 Float40::mod (const Float40 & divisor) const
Modulo operation (MOD)
Parameters
divisor Divisor
Returns
Remainder after division
Definition at line 147 of file float40.cpp.
References Float40().
Referenced by BinaryExpr::evaluate().
operator!=()
bool Float40::operator!= (const Float40 & other) const
Inequality comparison.
Parameters
other Right operand
Returns
true if values are not equal
Definition at line 123 of file float40.cpp.
operator*()
Float40 Float40::operator* (const Float40 & other) const
Multiplication operator.
Parameters
other Right operand
Returns
Product with Applesoft precision
Definition at line 106 of file float40.cpp.
References Float40().
operator+()
Float40 Float40::operator+ (const Float40 & other) const
Addition operator.
Parameters
other Right operand
Returns
Sum with Applesoft precision
Definition at line 98 of file float40.cpp.
References Float40().
operator-() [1/2]
Float40 Float40::operator- () const
Unary negation operator.
Returns
Negated value
Definition at line 117 of file float40.cpp.
References Float40().
operator-() [2/2]
Float40 Float40::operator- (const Float40 & other) const
Subtraction operator.
Parameters
other Right operand
Returns
Difference with Applesoft precision
Definition at line 102 of file float40.cpp.
References Float40().
operator/()
Float40 Float40::operator/ (const Float40 & other) const
Division operator.
Parameters
other Right operand
Returns
Quotient with Applesoft precision
Exceptions
RuntimeError on division by zero
Definition at line 110 of file float40.cpp.
References Float40().
operator<()
bool Float40::operator< (const Float40 & other) const
Less than comparison.
Parameters
other Right operand
Returns
true if this < other
Definition at line 127 of file float40.cpp.
operator<=()
bool Float40::operator<= (const Float40 & other) const
Less than or equal comparison.
Parameters
other Right operand
Returns
true if this <= other
Definition at line 135 of file float40.cpp.
operator==()
bool Float40::operator== (const Float40 & other) const
Equality comparison.
Parameters
other Right operand
Returns
true if values are equal within precision
Definition at line 119 of file float40.cpp.
operator>()
bool Float40::operator> (const Float40 & other) const
Greater than comparison.
Parameters
other Right operand
Returns
true if this > other
Definition at line 131 of file float40.cpp.
operator>=()
bool Float40::operator>= (const Float40 & other) const
Greater than or equal comparison.
Parameters
other Right operand
Returns
true if this >= other
Definition at line 139 of file float40.cpp.
power()
Float40 Float40::power (const Float40 & exponent) const
Exponentiation (^)
Parameters
exponent Power to raise to
Returns
This value raised to exponent power
Definition at line 143 of file float40.cpp.
References Float40().
Referenced by BinaryExpr::evaluate().
rnd()
Float40 Float40::rnd (const Float40 & seed) static
Generate random number (RND)
Parameters
seed Seed control (see funcRnd documentation)
Returns
Random Float40 in range [0, 1)
Definition at line 187 of file float40.cpp.
References Float40().
Referenced by funcRnd().
setSeed()
void Float40::setSeed (const Float40 & seed) static
Set random number seed.
Parameters
seed New seed value
Definition at line 199 of file float40.cpp.
Referenced by Interpreter::randomize().
sgn()
Float40 Float40::sgn () const
Sign function (SGN)
Returns
-1, 0, or 1 based on sign
Definition at line 153 of file float40.cpp.
References Float40().
Referenced by funcSgn().
sin()
Float40 Float40::sin () const
Sine function (SIN)
Returns
Sine of value (value in radians)
Definition at line 163 of file float40.cpp.
References Float40().
Referenced by funcSin().
sqr()
Float40 Float40::sqr () const
Square root (SQR)
Returns
Square root of value
Exceptions
RuntimeError if value < 0
Definition at line 180 of file float40.cpp.
References Float40().
Referenced by funcSqr().
tan()
Float40 Float40::tan () const
Tangent function (TAN)
Returns
Tangent of value (value in radians)
Definition at line 167 of file float40.cpp.
References Float40().
Referenced by funcTan().
toDouble()
double Float40::toDouble () const
Convert to standard double.
Returns
Double precision value
Definition at line 58 of file float40.cpp.
Referenced by BinaryExpr::evaluate(), funcAbs(), funcAtn(), funcCos(), funcExp(), funcInt(), funcLog(), funcSgn(), funcSin(), funcSqr(), and funcTan().
toString()
std::string Float40::toString () const
Convert to Applesoft-style string.
Returns
String representation matching Applesoft output format
Definition at line 60 of file float40.cpp.
Referenced by funcStr(), and Value::getString().
The documentation for this class was generated from the following files:
src/float40.h
src/float40.cpp