MSBasic - Applesoft BASIC Interpreter: HplotStmt Class Reference
HplotStmt Class Reference
Public Member Functions
HplotStmt (std::vector< std::pair< std::shared_ptr< Expression >, std::shared_ptr< Expression > > > coords)
void execute (Interpreter *interp) override
Execute this statement.
Public Member Functions inherited from Statement
virtual ~Statement ()=default
virtual void collectData (std::vector< Value > &) const
Allow statements like DATA to contribute to pre-run data collection.
Detailed Description
Definition at line 135 of file parser.cpp.
Constructor & Destructor Documentation
HplotStmt()
HplotStmt::HplotStmt (std::vector< std::pair< std::shared_ptr< Expression >, std::shared_ptr< Expression > > > coords) inline
Definition at line 137 of file parser.cpp.
Member Function Documentation
execute()
void HplotStmt::execute (Interpreter * interp) inline override virtual
Execute this statement.
Parameters
interp Pointer to the interpreter (for I/O, control flow, etc.)
Exceptions
std::runtime_error On execution errors
Implements Statement.
Definition at line 141 of file parser.cpp.
References graphics(), Graphics::hplot(), Graphics::hplot_to(), and Interpreter::requireGraphicsMode().
The documentation for this class was generated from the following file:
src/parser.cpp