MSBasic - Applesoft BASIC Interpreter: Value Class Reference
Value Class Reference
Runtime value that can hold either a number or a string.
#include <types.h>
Public Member Functions
Value ()
Default constructor creates a numeric value of 0.0.
Value (double num)
Construct a numeric value.
Value (const std::string &str)
Construct a string value.
Value (const Float40 &f40)
Construct from a 40-bit floating-point value.
bool isNumber () const
Check if this value is a number.
bool isString () const
Check if this value is a string.
double getNumber () const
Get the numeric value.
std::string getString () const
Get the string value.
Value operator+ (const Value &other) const
Add two values (or concatenate strings)
Value operator- (const Value &other) const
Subtract two numeric values.
Value operator* (const Value &other) const
Multiply two numeric values.
Value operator/ (const Value &other) const
Divide two numeric values.
bool operator== (const Value &other) const
Compare two values for equality.
bool operator!= (const Value &other) const
Compare two values for inequality.
bool operator< (const Value &other) const
Less-than comparison.
bool operator> (const Value &other) const
Greater-than comparison.
bool operator<= (const Value &other) const
Less-than-or-equal comparison.
bool operator>= (const Value &other) const
Greater-than-or-equal comparison.
Detailed Description
Runtime value that can hold either a number or a string.
Value is the fundamental data type for all runtime computations in MSBasic. It uses std::variant to store either a double (for numeric values) or std::string (for string values). The class provides type-safe access and automatic type checking for operations.
Type coercion rules:
Numeric operations on strings attempt conversion via VAL()
String concatenation converts numbers to strings via STR$()
Comparisons work within types; cross-type comparisons convert to string
Definition at line 230 of file types.h.
Constructor & Destructor Documentation
Value() [1/4]
Value::Value ()
Default constructor creates a numeric value of 0.0.
Construct a default Value (numeric 0.0)
Definition at line 29 of file types.cpp.
Referenced by operator*(), operator+(), operator-(), and operator/().
Value() [2/4]
Value::Value (double num) explicit
Construct a numeric value.
Construct a numeric Value.
Parameters
num The numeric value to store
num Numeric value to store
Definition at line 35 of file types.cpp.
Value() [3/4]
Value::Value (const std::string & str) explicit
Construct a string value.
Construct a string Value.
Parameters
str The string value to store
str String value to store
Definition at line 41 of file types.cpp.
Value() [4/4]
Value::Value (const Float40 & f40) explicit
Construct from a 40-bit floating-point value.
Construct a Value from Float40.
Parameters
f40 The Float40 value to convert and store
f40 Float40 value (converted to double)
Definition at line 47 of file types.cpp.
Member Function Documentation
getNumber()
double Value::getNumber () const
Get the numeric value.
Get value as a number.
Returns
The numeric value as a double
Exceptions
std::runtime_error if the value is not a number
If the value is already numeric, returns it directly. If the value is a string, attempts to parse it as a number using std::stod. Returns 0.0 if conversion fails or string is invalid.
Returns
Numeric representation of the value
Definition at line 78 of file types.cpp.
References isNumber(), and isString().
Referenced by UnaryExpr::evaluate(), BinaryExpr::evaluate(), ShloadStmt::execute(), IfStmt::execute(), funcAbs(), funcAtn(), funcChr(), funcCos(), funcExp(), funcInt(), funcLeft(), funcLog(), funcMid(), funcPeek(), funcRight(), funcRnd(), funcScrn(), funcSgn(), funcSin(), funcSpc(), funcSqr(), funcStr(), funcTab(), funcTan(), Interpreter::nextForLoop(), Interpreter::nextWhileLoop(), operator*(), operator+(), operator-(), operator/(), operator<(), operator==(), and operator>().
getString()
std::string Value::getString () const
Get the string value.
Get value as a string.
Returns
The string value
Exceptions
std::runtime_error if the value is not a string
If the value is already a string, returns it directly. If the value is numeric, converts it using Float40::toString() to maintain Applesoft formatting conventions.
Returns
String representation of the value
Definition at line 103 of file types.cpp.
References isNumber(), isString(), and Float40::toString().
Referenced by PrintStmt::execute(), funcAsc(), funcLeft(), funcLen(), funcMid(), funcRight(), funcVal(), operator+(), operator<(), operator==(), and operator>().
isNumber()
bool Value::isNumber () const
Check if this value is a number.
Check if this Value holds a number.
Returns
true if the value holds a number, false if it holds a string
true if value is numeric, false otherwise
Definition at line 55 of file types.cpp.
Referenced by getNumber(), and getString().
isString()
bool Value::isString () const
Check if this value is a string.
Check if this Value holds a string.
Returns
true if the value holds a string, false if it holds a number
true if value is a string, false otherwise
Definition at line 63 of file types.cpp.
Referenced by getNumber(), getString(), operator+(), operator<(), operator==(), and operator>().
operator!=()
bool Value::operator!= (const Value & other) const
Compare two values for inequality.
Inequality comparison.
Parameters
other The value to compare with
Returns
true if values are not equal
Parameters
other Right-hand operand
Returns
true if values are not equal, false otherwise
Definition at line 209 of file types.cpp.
operator*()
Value Value::operator* (const Value & other) const
Multiply two numeric values.
Multiplication operator.
Parameters
other The value to multiply by
Returns
The result of the multiplication
Exceptions
std::runtime_error if either value is not a number
Performs numeric multiplication using Float40 arithmetic. Both operands are coerced to numbers if necessary.
Parameters
other Right-hand operand
Returns
Result of multiplication
Definition at line 161 of file types.cpp.
References getNumber(), and Value().
operator+()
Value Value::operator+ (const Value & other) const
Add two values (or concatenate strings)
Addition/concatenation operator.
Parameters
other The value to add
Returns
The result of the addition/concatenation
Exceptions
std::runtime_error on type mismatch
If either operand is a string, performs string concatenation. Otherwise, performs numeric addition using Float40 arithmetic.
Parameters
other Right-hand operand
Returns
Result of addition or concatenation
Definition at line 126 of file types.cpp.
References getNumber(), getString(), isString(), and Value().
operator-()
Value Value::operator- (const Value & other) const
Subtract two numeric values.
Subtraction operator.
Parameters
other The value to subtract
Returns
The result of the subtraction
Exceptions
std::runtime_error if either value is not a number
Performs numeric subtraction using Float40 arithmetic. Both operands are coerced to numbers if necessary.
Parameters
other Right-hand operand
Returns
Result of subtraction
Definition at line 146 of file types.cpp.
References getNumber(), and Value().
operator/()
Value Value::operator/ (const Value & other) const
Divide two numeric values.
Division operator.
Parameters
other The divisor
Returns
The result of the division
Exceptions
std::runtime_error if either value is not a number or divisor is zero
Performs numeric division using Float40 arithmetic. Both operands are coerced to numbers if necessary. Division by zero behavior follows Float40 conventions.
Parameters
other Right-hand operand
Returns
Result of division
Definition at line 177 of file types.cpp.
References getNumber(), and Value().
operator<()
bool Value::operator< (const Value & other) const
Less-than comparison.
Parameters
other The value to compare with
Returns
true if this value is less than other
Exceptions
std::runtime_error on type mismatch
For strings: compares strings lexicographically For numbers: compares using Float40 comparison Mixed types are coerced to numbers for comparison
Parameters
other Right-hand operand
Returns
true if this value is less than other, false otherwise
Definition at line 223 of file types.cpp.
References getNumber(), getString(), and isString().
operator<=()
bool Value::operator<= (const Value & other) const
Less-than-or-equal comparison.
Parameters
other The value to compare with
Returns
true if this value is less than or equal to other
Exceptions
std::runtime_error on type mismatch
Parameters
other Right-hand operand
Returns
true if this value is less than or equal to other, false otherwise
Definition at line 256 of file types.cpp.
operator==()
bool Value::operator== (const Value & other) const
Compare two values for equality.
Equality comparison.
Parameters
other The value to compare with
Returns
true if values are equal (same type and same value)
For strings: compares strings lexicographically For numbers: compares using Float40 equality Mixed types are coerced to numbers for comparison
Parameters
other Right-hand operand
Returns
true if values are equal, false otherwise
Definition at line 195 of file types.cpp.
References getNumber(), getString(), and isString().
operator>()
bool Value::operator> (const Value & other) const
Greater-than comparison.
Parameters
other The value to compare with
Returns
true if this value is greater than other
Exceptions
std::runtime_error on type mismatch
For strings: compares strings lexicographically For numbers: compares using Float40 comparison Mixed types are coerced to numbers for comparison
Parameters
other Right-hand operand
Returns
true if this value is greater than other, false otherwise
Definition at line 242 of file types.cpp.
References getNumber(), getString(), and isString().
operator>=()
bool Value::operator>= (const Value & other) const
Greater-than-or-equal comparison.
Parameters
other The value to compare with
Returns
true if this value is greater than or equal to other
Exceptions
std::runtime_error on type mismatch
Parameters
other Right-hand operand
Returns
true if this value is greater than or equal to other, false otherwise
Definition at line 265 of file types.cpp.
The documentation for this class was generated from the following files:
src/types.h
src/types.cpp