MSBasic - Applesoft BASIC Interpreter: FunctionCallExpr Class Reference
FunctionCallExpr Class Reference
Public Member Functions
FunctionCallExpr (TokenType func, std::vector< std::shared_ptr< Expression > > args)
Value evaluate (Interpreter *interp) override
Evaluate this expression to produce a value.
Public Member Functions inherited from Expression
virtual ~Expression ()=default
Detailed Description
Definition at line 554 of file parser.cpp.
Constructor & Destructor Documentation
FunctionCallExpr()
FunctionCallExpr::FunctionCallExpr (TokenType func, std::vector< std::shared_ptr< Expression > > args) inline
Definition at line 556 of file parser.cpp.
Member Function Documentation
evaluate()
Value FunctionCallExpr::evaluate (Interpreter * interp) inline override virtual
Evaluate this expression to produce a value.
Parameters
interp Pointer to the interpreter (for variable lookup, etc.)
Returns
Value The computed value of the expression
Exceptions
std::runtime_error On evaluation errors (type mismatch, etc.)
Implements Expression.
Definition at line 560 of file parser.cpp.
References ABS, ASC, ATN, CHR, COS, EXP, FRE, funcAbs(), funcAsc(), funcAtn(), funcChr(), funcCos(), funcExp(), funcFre(), funcInt(), funcLeft(), funcLen(), funcLog(), funcMid(), funcPdl(), funcPeek(), funcPos(), funcRight(), funcRnd(), funcScrn(), funcSgn(), funcSin(), funcSqr(), funcStr(), funcTan(), funcUsr(), funcVal(), INT, LEFT, LEN, LOG, MID, PDL, PEEK, POS, RIGHT, RND, SCRN, SGN, SIN, SQR, STR, TAN, USR, and VAL.
The documentation for this class was generated from the following file:
src/parser.cpp