MSBasic - Applesoft BASIC Interpreter: Graphics Class Reference
Graphics Class Reference
Singleton managing graphics state and operations.
#include <graphics.h>
Public Member Functions
void initialize (const GraphicsConfig &config)
Initialize graphics subsystem.
void setRenderer (std::shared_ptr< GraphicsRenderer > renderer)
Set platform-specific renderer.
void renderFrame ()
Render accumulated frame to window.
bool shouldClose () const
Check if window close requested.
void enterLowRes ()
Enter low-resolution graphics mode (GR)
void enterHighRes ()
Enter high-resolution graphics mode (HGR)
void setColor (int color)
Set drawing color.
int color () const
Get current drawing color.
GraphicsMode mode () const
Get current graphics mode.
const GraphicsWindow & window () const
Get graphics window dimensions.
const std::vector< PlotSample > & frame () const
Get frame buffer.
void clearFrame ()
Clear frame buffer.
void plot (double x, double y)
Plot a single point (PLOT/HPLOT implementation)
void hlin (double x1, double x2, double y)
Draw horizontal line (HLIN implementation)
void vlin (double y1, double y2, double x)
Draw vertical line (VLIN implementation)
void hplot (double x, double y)
Plot a high-resolution point (HPLOT implementation)
void hplot_to (double x, double y)
Plot a point relative to last position (HPLOT TO implementation)
void move (double x, double y)
Move drawing position without plotting (MOVE implementation)
void setRotate (int angle)
Set rotation angle for shape drawing (ROTATE implementation)
void setScale (int scale)
Set scale factor for shape drawing (SCALE implementation)
void draw (int shapeNum, double x=-1, double y=-1)
Draw a shape from shape table (DRAW implementation)
void xdraw (int shapeNum, double x=-1, double y=-1)
Draw shape with XOR mode (XDRAW implementation)
int scrn (double x, double y) const
Query pixel color at coordinates (SCRN function implementation)
void loadShape (int shapeNum, const std::vector< std::pair< double, double > > &points)
Load a custom shape into shape table.
Static Public Member Functions
static Graphics & instance ()
Get singleton instance.
Detailed Description
Singleton managing graphics state and operations.
The Graphics class implements Applesoft graphics commands and maintains graphics state. It uses an off-screen buffer (frame) to accumulate plot operations, which are rendered to the window via GraphicsRenderer.
Thread safety: Not thread-safe. Single-threaded use only.
Usage:
Graphics::instance().initialize(config);
Graphics::instance().enterHighRes();
Graphics::instance().setColor(3);
Graphics::instance().hplot(140, 96);
Graphics::instance().renderFrame();
Definition at line 99 of file graphics.h.
Member Function Documentation
clearFrame()
void Graphics::clearFrame ()
Clear frame buffer.
Clear the frame buffer.
Removes all accumulated plot operations without rendering.
Removes all accumulated plot operations. Does not clear the pixel buffer used for SCRN() lookups.
Definition at line 200 of file graphics.cpp.
Referenced by enterHighRes(), and enterLowRes().
color()
int Graphics::color () const inline
Get current drawing color.
Returns
Current color value
Definition at line 161 of file graphics.h.
Referenced by setColor().
draw()
void Graphics::draw (int shapeNum, double x = -1, double y = -1)
Draw a shape from shape table (DRAW implementation)
Draws a shape from the shape table at the specified position, applying current rotation and scale transformations. Shapes are stored as sequences of relative coordinate pairs.
Shape Drawing Process:
Look up shape by number in shapeTable_
Determine origin (x,y if valid, else last position, else 0,0)
For each point in shape: a. Apply rotation transformation (rotate by rotateAngle_) b. Apply scale transformation (multiply by scaleFactor_) c. Translate to origin position d. Record point in frame buffer
Transformation math: rotated_x = x * cos(angle) - y * sin(angle) rotated_y = x * sin(angle) + y * cos(angle) final_x = origin_x + rotated_x * scale final_y = origin_y + rotated_y * scale
Usage in BASIC: DRAW 1 (draw shape 1 at current position) DRAW 1 AT 100,50 (draw shape 1 at specific position) ROTATE=45: SCALE=2: DRAW 1 (rotated and scaled)
Parameters
shapeNum Shape number to draw (1-255)
x X coordinate of origin (< 0 uses last position)
y Y coordinate of origin (< 0 uses last position)
Definition at line 511 of file graphics.cpp.
Referenced by DrawStmt::execute().
enterHighRes()
void Graphics::enterHighRes ()
Enter high-resolution graphics mode (HGR)
Sets 280×192 graphics with 6 colors. Clears screen.
Sets 280×192 graphics mode matching Apple II HGR page 1. Clears the frame buffer.
Definition at line 176 of file graphics.cpp.
References clearFrame(), and HighRes.
Referenced by HgrStmt::execute(), and HiresStmt::execute().
enterLowRes()
void Graphics::enterLowRes ()
Enter low-resolution graphics mode (GR)
Sets 40×48 graphics with 16 colors. Clears screen.
Sets 40×40 graphics mode and clears the frame buffer. Note: Applesoft used 40×48, but this implementation uses 40×40 for simplicity.
Definition at line 164 of file graphics.cpp.
References clearFrame(), and LowRes.
Referenced by GrStmt::execute().
frame()
const std::vector< PlotSample > & Graphics::frame () const
Get frame buffer.
Returns
Reference to vector of PlotSamples
Definition at line 156 of file graphics.cpp.
hlin()
void Graphics::hlin (double x1, double x2, double y)
Draw horizontal line (HLIN implementation)
Draws a horizontal line from (x1,y) to (x2,y). In the simplified implementation, this just records the endpoints. A full implementation would interpolate points along the line.
Usage in BASIC: HLIN X1,X2 AT Y
Examples: HLIN 0,39 AT 20 (draw line across screen at row 20) HLIN 100,200 AT 96 (HGR mode horizontal line)
Parameters
x1 Starting X coordinate
x2 Ending X coordinate
y Y coordinate (constant for horizontal line)
Definition at line 347 of file graphics.cpp.
Referenced by HlinStmt::execute().
hplot()
void Graphics::hplot (double x, double y)
Plot a high-resolution point (HPLOT implementation)
Plots a single point in high-resolution graphics mode at the specified coordinates. This implements the HPLOT command from Applesoft BASIC.
Behavior:
Plots point in current HCOLOR (set by HCOLOR command)
Updates last position for HPLOT TO operations
Coordinates in Apple II hi-res space (0-279 horizontal, 0-191 vertical)
Points outside valid range are clipped
Usage in BASIC: HPLOT 100,100 (plot single point) HPLOT 0,0 (top-left corner) HPLOT 279,191 (bottom-right corner)
The last plotted position is saved for HPLOT TO operations which draw lines from the previous point.
Parameters
x X coordinate (0-279 in standard hi-res)
y Y coordinate (0-191 in standard hi-res)
Definition at line 397 of file graphics.cpp.
Referenced by HplotStmt::execute().
hplot_to()
void Graphics::hplot_to (double x, double y)
Plot a point relative to last position (HPLOT TO implementation)
Similar to plot() but used with HPLOT TO syntax for drawing connected lines. HPLOT maintains a "pen position" that TO operations draw from.
Usage in BASIC: HPLOT 100,100 (move to position) HPLOT TO 200,150 (draw line from 100,100 to 200,150) HPLOT TO 150,200 (draw line from 200,150 to 150,200)
Parameters
x Target X coordinate
y Target Y coordinate
Definition at line 418 of file graphics.cpp.
Referenced by HplotStmt::execute().
initialize()
void Graphics::initialize (const GraphicsConfig & config)
Initialize graphics subsystem.
Initialize graphics subsystem with configuration.
Parameters
config Graphics configuration
Creates and initializes the GraphicsRenderer if graphics are enabled. If initialization fails (e.g., no display available), continues without rendering but maintains off-screen buffer.
Parameters
config Graphics configuration (mode, scale factor, etc.)
Definition at line 99 of file graphics.cpp.
References GraphicsConfig::isGraphicsEnabled().
Referenced by main().
instance()
Graphics & Graphics::instance () static
Get singleton instance.
Get Graphics singleton instance.
Returns
Reference to Graphics singleton
Definition at line 79 of file graphics.cpp.
Referenced by graphics().
loadShape()
void Graphics::loadShape (int shapeNum, const std::vector< std::pair< double, double > > & points)
Load a custom shape into shape table.
Adds or replaces a shape in the shape table. Shapes are defined as a sequence of relative coordinate pairs that define a polyline.
Shape coordinate conventions:
All coordinates are relative to origin (0,0)
First point is usually (0,0) for the start
Last point typically returns to (0,0) for closed shapes
Coordinates can be negative for shapes extending in all directions
Usage (typically from SHLOAD command): Shape data is loaded from a file or tape Each shape has a number (1-255) and list of points
Parameters
shapeNum Shape number (1-255)
points Vector of coordinate pairs defining the shape
Definition at line 747 of file graphics.cpp.
Referenced by ShloadStmt::execute().
mode()
GraphicsMode Graphics::mode () const
Get current graphics mode.
Returns
Current GraphicsMode
Definition at line 152 of file graphics.cpp.
move()
void Graphics::move (double x, double y)
Move drawing position without plotting (MOVE implementation)
Sets the current position for shape drawing without actually plotting a point. Used primarily with DRAW/XDRAW to set the origin for shape operations.
The MOVE command affects:
Shape drawing origin (DRAW, XDRAW)
Relative HPLOT TO operations
Parameters
x New X position
y New Y position
Definition at line 438 of file graphics.cpp.
Referenced by MoveStmt::execute().
plot()
void Graphics::plot (double x, double y)
Plot a single point (PLOT/HPLOT implementation)
Plots a point at the specified coordinates and updates the "last position" for relative drawing operations (DRAW, XDRAW).
Usage in BASIC:
GR mode: PLOT X,Y where X=0-39, Y=0-39
HGR mode: HPLOT X,Y where X=0-279, Y=0-191
Side effects:
Adds point to frame buffer
Sets lastX_, lastY_ for relative operations
Sets lastValid_ flag indicating valid last position
Parameters
x Logical X coordinate
y Logical Y coordinate
Definition at line 322 of file graphics.cpp.
Referenced by PlotStmt::execute().
renderFrame()
void Graphics::renderFrame ()
Render accumulated frame to window.
Render accumulated frame buffer to window.
Sends all plot operations from the frame buffer to the renderer for display. Call this after graphics commands to update display.
Sends all plot operations from the frame buffer to the GraphicsRenderer for display. If no renderer is available or initialized, this is a no-op. The frame buffer persists until explicitly cleared.
Definition at line 124 of file graphics.cpp.
scrn()
int Graphics::scrn (double x, double y) const
Query pixel color at coordinates (SCRN function implementation)
Returns the color value of the pixel at the specified logical coordinates. This implements the SCRN(x,y) function in Applesoft BASIC.
Return value:
0 if no pixel has been drawn at this location
Color value (1-15 for GR, 0-7 for HGR) if pixel exists
Usage in BASIC: C = SCRN(100,50) (get color at 100,50) IF SCRN(X,Y) <> 0 THEN PRINT "HIT!" (collision detection)
Implementation notes:
Queries the pixel buffer (not frame buffer)
Coordinates are clamped to valid range
Returns 0 for unplotted locations
Parameters
x Logical X coordinate
y Logical Y coordinate
Returns
Color value at that location, or 0 if empty
Definition at line 714 of file graphics.cpp.
References GraphicsWindow::logicalHeight, and GraphicsWindow::logicalWidth.
Referenced by funcScrn().
setColor()
void Graphics::setColor (int color)
Set drawing color.
Set current drawing color.
Parameters
color Color value (0-15 for GR, 0-7 for HGR)
Sets the color for subsequent plot operations. Clamped to 0-255 range.
Parameters
color Color value (0-15 for GR, 0-7 for HGR)
Definition at line 189 of file graphics.cpp.
References color().
Referenced by HcolorStmt::execute(), and ColorStmt::execute().
setRenderer()
void Graphics::setRenderer (std::shared_ptr< GraphicsRenderer > renderer)
Set platform-specific renderer.
Set platform-specific renderer implementation.
Parameters
renderer Shared pointer to GraphicsRenderer implementation
renderer Shared pointer to GraphicsRenderer
Definition at line 113 of file graphics.cpp.
setRotate()
void Graphics::setRotate (int angle)
Set rotation angle for shape drawing (ROTATE implementation)
Sets the rotation angle applied to shapes drawn with DRAW/XDRAW. Angle is in degrees, clockwise from the positive X axis.
Usage: ROTATE=45: DRAW 1 (draw shape 1 rotated 45 degrees)
The rotation is applied to each point in the shape relative to the origin.
Parameters
angle Rotation angle in degrees (0-359)
Definition at line 458 of file graphics.cpp.
Referenced by RotateStmt::execute().
setScale()
void Graphics::setScale (int scale)
Set scale factor for shape drawing (SCALE implementation)
Sets the scaling factor applied to shapes drawn with DRAW/XDRAW. Scale is a multiplier applied to shape coordinates.
Usage: SCALE=2: DRAW 1 (draw shape 1 at 2× size) SCALE=1 (normal size - default)
Minimum scale is 1 (no scale less than 1 allowed).
Parameters
scale Scale factor (minimum 1)
Definition at line 474 of file graphics.cpp.
Referenced by ScaleStmt::execute().
shouldClose()
bool Graphics::shouldClose () const
Check if window close requested.
Check if window close requested by user.
Returns
true if user closed graphics window
true if close requested, false otherwise
Definition at line 145 of file graphics.cpp.
vlin()
void Graphics::vlin (double y1, double y2, double x)
Draw vertical line (VLIN implementation)
Draws a vertical line from (x,y1) to (x,y2). This implements the VLIN command from Applesoft BASIC for low-resolution graphics.
Usage in BASIC: VLIN 0,39 AT 20 (draw line down screen at column 20) VLIN 10,30 AT 5 (draw vertical segment)
The line is drawn in the current color (set by COLOR command). Y coordinates are automatically clamped to valid screen range.
Parameters
y1 Starting Y coordinate
y2 Ending Y coordinate
x X coordinate (constant for vertical line)
Definition at line 369 of file graphics.cpp.
Referenced by VlinStmt::execute().
window()
const GraphicsWindow & Graphics::window () const
Get graphics window dimensions.
Returns
Reference to GraphicsWindow structure
Definition at line 154 of file graphics.cpp.
xdraw()
void Graphics::xdraw (int shapeNum, double x = -1, double y = -1)
Draw shape with XOR mode (XDRAW implementation)
Similar to draw() but uses XOR (exclusive or) mode for drawing. In XOR mode:
Drawing on background sets pixels
Drawing on existing pixels clears them
Drawing the same shape twice returns to original state
XOR drawing is useful for:
Animation (draw/erase/move/redraw without clearing screen)
Cursors and temporary graphics
Creating "invert" effects
XOR Logic:
If pixel is off (0), set to current color
If pixel is on (non-zero), set to off (0)
This makes drawing reversible: XDRAW twice = no change
Usage in BASIC: XDRAW 1 AT 100,100 (draw shape 1) XDRAW 1 AT 100,100 (erase shape 1 - back to original) ' Move and redraw XDRAW 1 AT 110,100 (draw at new position)
All rotation and scale transformations apply as with DRAW.
Parameters
shapeNum Shape number to draw in XOR mode
x X coordinate of origin (< 0 uses last position)
y Y coordinate of origin (< 0 uses last position)
Definition at line 583 of file graphics.cpp.
Referenced by XdrawStmt::execute().
The documentation for this class was generated from the following files:
src/graphics.h
src/graphics.cpp