MSBasic - Applesoft BASIC Interpreter: PrintStmt Class Reference
PrintStmt Class Reference
Public Types
enum class Separator { None , Semicolon , Comma }
Public Member Functions
PrintStmt (std::vector< std::shared_ptr< Expression > > exprs, std::vector< Separator > separators)
void execute (Interpreter *interp) override
Execute this statement.
Public Member Functions inherited from Statement
virtual ~Statement ()=default
virtual void collectData (std::vector< Value > &) const
Allow statements like DATA to contribute to pre-run data collection.
Detailed Description
Definition at line 628 of file parser.cpp.
Member Enumeration Documentation
Separator
enum class PrintStmt::Separator strong
Enumerator
None
Semicolon
Comma
Definition at line 630 of file parser.cpp.
Constructor & Destructor Documentation
PrintStmt()
PrintStmt::PrintStmt (std::vector< std::shared_ptr< Expression > > exprs, std::vector< Separator > separators) inline
Definition at line 632 of file parser.cpp.
Member Function Documentation
execute()
void PrintStmt::execute (Interpreter * interp) inline override virtual
Execute this statement.
Parameters
interp Pointer to the interpreter (for I/O, control flow, etc.)
Exceptions
std::runtime_error On execution errors
Implements Statement.
Definition at line 636 of file parser.cpp.
References Comma, Value::getString(), None, Interpreter::printNewline(), Interpreter::printText(), Interpreter::printToNextZone(), and Semicolon.
The documentation for this class was generated from the following file:
src/parser.cpp