MSBasic - Applesoft BASIC Interpreter: TapeManager Class Reference
TapeManager Class Reference
Cassette tape emulation for sequential data storage.
#include <tape_manager.h>
Public Member Functions
TapeManager ()
Construct tape manager (no tape loaded)
~TapeManager ()
Destructor, closes tape if open.
void setTapeFile (const std::string &filename)
Set tape file path.
std::string getTapeFile () const
Get current tape file path.
bool hasTape () const
Check if tape file is set.
void openForRead ()
Open tape for reading.
void openForWrite ()
Open tape for writing.
void close ()
Close tape.
void rewind ()
Rewind tape to beginning.
void writeRecord (const std::vector< uint8_t > &data)
Write record to tape.
std::vector< uint8_t > readRecord ()
Read record from tape.
bool isOpen () const
Check if tape is open.
bool isReadMode () const
Check if tape is open for reading.
bool isWriteMode () const
Check if tape is open for writing.
size_t getPosition () const
Get current tape position.
bool isEndOfTape () const
Check if at end of tape.
Static Public Member Functions
static std::string showFileSelector (const std::string &title="Select Tape File")
Show platform-specific file selector dialog.
Detailed Description
Cassette tape emulation for sequential data storage.
Emulates Apple II cassette tape operations with record-based sequential I/O. Each record has a size header followed by data bytes, mimicking the format used by Apple II tape storage.
The manager maintains tape state including current position, read/write mode, and provides rewind capability matching physical tape behavior.
Definition at line 52 of file tape_manager.h.
Constructor & Destructor Documentation
TapeManager()
TapeManager::TapeManager ()
Construct tape manager (no tape loaded)
Definition at line 63 of file tape_manager.cpp.
~TapeManager()
TapeManager::~TapeManager ()
Destructor, closes tape if open.
Destructor - closes tape file if open.
Definition at line 68 of file tape_manager.cpp.
References close().
Member Function Documentation
close()
void TapeManager::close ()
Close tape.
Close the tape file.
Flushes and closes the tape file. Safe to call if not open.
Closes the current tape file and resets position to 0. Safe to call even if no file is open.
Definition at line 176 of file tape_manager.cpp.
Referenced by openForRead(), openForWrite(), setTapeFile(), and ~TapeManager().
getPosition()
size_t TapeManager::getPosition () const inline
Get current tape position.
Returns
Byte offset from start of tape
Definition at line 160 of file tape_manager.h.
getTapeFile()
std::string TapeManager::getTapeFile () const inline
Get current tape file path.
Returns
Tape file path or empty string if no tape set
Definition at line 79 of file tape_manager.h.
Referenced by Interpreter::getTapeFile().
hasTape()
bool TapeManager::hasTape () const inline
Check if tape file is set.
Returns
true if tape file path is configured
Definition at line 85 of file tape_manager.h.
Referenced by Interpreter::loadShapeTableFromFile(), Interpreter::recallArray(), and Interpreter::storeArray().
isEndOfTape()
bool TapeManager::isEndOfTape () const
Check if at end of tape.
Check if end of tape has been reached.
Returns
true if at EOF
Returns true if tape is open for reading and EOF has been reached. Returns false if not in read mode or tape not open.
Returns
true if at end of tape, false otherwise
Definition at line 346 of file tape_manager.cpp.
References isOpen().
isOpen()
bool TapeManager::isOpen () const inline
Check if tape is open.
Returns
true if open for reading or writing
Definition at line 142 of file tape_manager.h.
Referenced by isEndOfTape(), openForRead(), openForWrite(), readRecord(), rewind(), setTapeFile(), and writeRecord().
isReadMode()
bool TapeManager::isReadMode () const inline
Check if tape is open for reading.
Returns
true if in read mode
Definition at line 148 of file tape_manager.h.
isWriteMode()
bool TapeManager::isWriteMode () const inline
Check if tape is open for writing.
Returns
true if in write mode
Definition at line 154 of file tape_manager.h.
openForRead()
void TapeManager::openForRead ()
Open tape for reading.
Open tape file for reading.
Exceptions
RuntimeError if no tape set or file cannot be opened
Opens the current tape file in read mode for RECALL and SHLOAD operations. If already open in read mode, keeps current position. If open in write mode, closes and reopens in read mode.
Position tracking allows sequential reads across multiple RECALL commands without rewinding.
Exceptions
std::runtime_error if no tape loaded or file cannot be opened
Definition at line 101 of file tape_manager.cpp.
References close(), and isOpen().
Referenced by Interpreter::loadShapeTableFromFile(), and Interpreter::recallArray().
openForWrite()
void TapeManager::openForWrite ()
Open tape for writing.
Open tape file for writing.
Exceptions
RuntimeError if no tape set or file cannot be opened
Opens file in append mode to preserve existing data.
Opens the current tape file in write mode for STORE operations. If already open in write mode, keeps current position. If open in read mode, closes and reopens in write mode.
Write operations append at the current position, allowing sequential writes across multiple STORE commands.
Exceptions
std::runtime_error if no tape loaded or file cannot be opened
Definition at line 139 of file tape_manager.cpp.
References close(), and isOpen().
Referenced by Interpreter::storeArray().
readRecord()
std::vector< uint8_t > TapeManager::readRecord ()
Read record from tape.
Read a record from tape (sequential read)
Returns
Byte vector containing record data
Exceptions
RuntimeError if tape not open for reading or read error
Reads size header then data bytes. Returns empty vector at EOF.
Reads the next data record from the tape file at the current position. Each record consists of a 4-byte size header followed by the data bytes. This implements the sequential tape read behavior of Applesoft BASIC.
Record format:
Size header: 4 bytes (uint32_t) in native byte order
Data: Variable length based on size header
Behavior:
Reads from current file position (sequential)
Advances position for next read
Returns data as byte vector
Validates size against MAX_RECORD_SIZE (1 MB)
Error conditions:
Tape not open: "TAPE NOT OPEN FOR READING"
In write mode: "TAPE NOT OPEN FOR READING"
End of file: "END OF TAPE"
Invalid size (0 or > 1MB): "INVALID TAPE FORMAT"
Partial read: "TAPE READ ERROR"
Size validation:
Maximum 1 MB prevents corruption issues
Zero size indicates format error
Checks gcount() to verify complete read
Returns
Vector of bytes containing record data
Exceptions
std::runtime_error if tape not open for reading, EOF, or read fails
Read the next record from the tape at the current position
Reads the 4-byte size header followed by that many payload bytes.
Safety:
Rejects records larger than MAX_RECORD_SIZE to prevent unbounded allocations from corrupt or malicious tape files.
Error behavior:
Throws "TAPE NOT OPEN FOR READING" if tape is not open in read mode.
Throws "END OF TAPE" when EOF is reached.
Throws "INVALID TAPE FORMAT" for invalid size headers.
Throws "TAPE READ ERROR" if the payload cannot be fully read.
Returns
Record payload bytes
Exceptions
std::runtime_error on invalid mode, EOF, format error, or I/O error
Definition at line 309 of file tape_manager.cpp.
References isOpen(), and MAX_RECORD_SIZE.
Referenced by Interpreter::loadShapeTableFromFile(), and Interpreter::recallArray().
rewind()
void TapeManager::rewind ()
Rewind tape to beginning.
Exceptions
RuntimeError if tape not open
Resets file position to the start of the tape. Used when starting over with a sequence of reads or writes. No-op if tape is not open.
Definition at line 189 of file tape_manager.cpp.
References isOpen().
setTapeFile()
void TapeManager::setTapeFile (const std::string & filename)
Set tape file path.
Set the current tape file.
Parameters
filename Path to tape file
Sets the tape file but doesn't open it. Call openForRead() or openForWrite() to actually open the file.
Changes the tape file path and resets position to start. Closes any currently open tape file.
Usage in BASIC: TAPE "MYDATA.TAP" (sets current tape file)
Parameters
filename Path to tape file
Definition at line 81 of file tape_manager.cpp.
References close(), and isOpen().
Referenced by Interpreter::changeTapeFile(), and Interpreter::setTapeFile().
showFileSelector()
std::string TapeManager::showFileSelector (const std::string & title = "Select Tape File") static
Show platform-specific file selector dialog.
Display a native file picker to select a tape file.
Parameters
title Dialog window title
Returns
Selected file path or empty string if cancelled
Uses native file dialog on supported platforms. Returns empty string on platforms without GUI support.
Provides a best-effort platform-specific UI for selecting a tape file path. This is intended for interactive use (e.g., selecting a .tap file) and is not required for core interpreter functionality. Typical platform behaviors include using the Win32 dialog on Windows, osascript on macOS, and zenity/kdialog on Linux. The function returns an absolute path on success or an empty string if the user cancels or no suitable UI is available. Callers should treat an empty string as "no file selected".
Parameters
title Dialog title/prompt string
Returns
Selected file path, or empty string on cancel/unavailable UI
Definition at line 382 of file tape_manager.cpp.
Referenced by Interpreter::changeTapeFile().
writeRecord()
void TapeManager::writeRecord (const std::vector< uint8_t > & data)
Write record to tape.
Write a record to tape (sequential write)
Parameters
data Byte vector to write as record
Exceptions
RuntimeError if tape not open for writing
Writes size header (4 bytes) followed by data bytes.
Writes a data record to the tape file at the current position. Each record consists of a 4-byte size header followed by the data bytes. This implements the sequential tape write behavior of Applesoft BASIC.
Record format:
Size header: 4 bytes (uint32_t) in native byte order
Data: Variable length based on size header
Behavior:
Writes at current file position (sequential)
Automatically flushes to disk after write
Updates position counter
Position maintained across multiple writes
Error conditions:
Tape not open: "TAPE NOT OPEN FOR WRITING"
In read mode: "TAPE NOT OPEN FOR WRITING"
Write failure: "TAPE WRITE ERROR"
Cross-platform note:
Uses native byte order for size (not portable across architectures)
For cross-platform compatibility, use tapes on same architecture
Future: Could implement little-endian serialization
Parameters
data Byte vector containing record data to write
Exceptions
std::runtime_error if tape not open for writing or write fails
Definition at line 234 of file tape_manager.cpp.
References isOpen().
Referenced by Interpreter::storeArray().
The documentation for this class was generated from the following files:
src/tape_manager.h
src/tape_manager.cpp