MSBasic - Applesoft BASIC Interpreter: src/filesystem.cpp File Reference
filesystem.cpp File Reference
Cross-platform filesystem operations for BASIC file I/O.
#include "filesystem.h"
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
std::vector< FileInfo > listFiles (const std::string &path)
List files in a directory.
bool fileExists (const std::string &filename)
Check if a file exists.
std::string readTextFile (const std::string &filename)
Read entire text file into a string.
void writeTextFile (const std::string &filename, const std::string &content)
Write an entire text file from a string.
bool deleteFile (const std::string &filename)
Delete a filesystem entry.
bool renameFile (const std::string &oldName, const std::string &newName)
Rename a filesystem entry.
std::string getCurrentPrefix ()
Get the current ProDOS prefix (working directory)
bool setPrefix (const std::string &path)
Set the current ProDOS prefix (working directory)
Detailed Description
Cross-platform filesystem operations for BASIC file I/O.
This file implements platform-independent filesystem operations used by the BASIC interpreter for commands like LOAD, SAVE, CATALOG, and file selector dialogs.
Key features:
Cross-platform file listing (Windows and POSIX)
BASIC program file reading/writing with line number preservation
Binary array data I/O for RECALL/STORE commands
Native file selector dialogs (zenity/kdialog/osascript/Windows COM)
ProDOS-compatible error messages
Platform-specific implementations:
Windows: Uses WIN32 API (FindFirstFile, CoCreateInstance for dialogs)
Linux: Uses dirent.h (opendir/readdir) and zenity/kdialog
macOS: Uses dirent.h and osascript for file selection
Definition in file filesystem.cpp.
Function Documentation
deleteFile()
bool deleteFile (const std::string & filename)
Delete a filesystem entry.
Delete file (DELETE)
Implements the ProDOS-style DELETE behavior used by the interpreter. Returns a boolean rather than throwing so callers can map failures to ProDOS-like error messages.
Parameters
filename Path to file
Returns
true if deletion succeeded, false otherwise
Definition at line 169 of file filesystem.cpp.
fileExists()
bool fileExists (const std::string & filename)
Check if a file exists.
Check if file exists.
Simple existence check by attempting to open the file for reading.
Parameters
filename Path to file
Returns
true if file exists and is readable, false otherwise
Definition at line 109 of file filesystem.cpp.
Referenced by FileManager::lockFile(), and FileManager::unlockFile().
getCurrentPrefix()
std::string getCurrentPrefix ()
Get the current ProDOS prefix (working directory)
Get current working directory prefix (PREFIX)
The interpreter treats the process working directory as the ProDOS PREFIX. This function returns that directory for commands like PREFIX with no argument.
Returns
Current working directory path, or empty string on failure
Definition at line 206 of file filesystem.cpp.
Referenced by Interpreter::showPrefix().
listFiles()
std::vector< FileInfo > listFiles (const std::string & path)
List files in a directory.
List files in directory (CATALOG)
Returns information about all files in the specified directory, excluding "." and ".." entries. Uses platform-specific APIs for optimal performance.
Parameters
path Directory path to list
Returns
Vector of FileInfo structures with name, size, and isDirectory
Definition at line 52 of file filesystem.cpp.
References FileInfo::isDirectory, FileInfo::name, and FileInfo::size.
Referenced by Interpreter::catalog(), and Interpreter::catalogFiles().
readTextFile()
std::string readTextFile (const std::string & filename)
Read entire text file into a string.
Read entire text file into string.
Reads the file contents into memory as a string. Used for loading BASIC program files.
Parameters
filename Path to file
Returns
File contents as string
Exceptions
std::runtime_error with "PATH NOT FOUND ERROR" if file cannot be opened
Definition at line 125 of file filesystem.cpp.
Referenced by Interpreter::chainProgram(), Interpreter::chainProgram(), Interpreter::dashProgram(), Interpreter::execFile(), and Interpreter::loadProgram().
renameFile()
bool renameFile (const std::string & oldName, const std::string & newName)
Rename a filesystem entry.
Rename file (RENAME)
Implements the ProDOS-style RENAME behavior used by the interpreter. Returns a boolean rather than throwing so callers can map failures to ProDOS-like error messages.
Parameters
oldName Existing path
newName New path
Returns
true if rename succeeded, false otherwise
Definition at line 188 of file filesystem.cpp.
setPrefix()
bool setPrefix (const std::string & path)
Set the current ProDOS prefix (working directory)
Set current working directory prefix (PREFIX)
In ProDOS, PREFIX changes the default directory used to resolve partial pathnames. In this host implementation, we map PREFIX to process working directory.
Parameters
path New working directory path
Returns
true if the directory was changed successfully, false otherwise
Definition at line 224 of file filesystem.cpp.
writeTextFile()
void writeTextFile (const std::string & filename, const std::string & content)
Write an entire text file from a string.
Write string to text file.
Used by BASIC commands that create or overwrite text files, such as SAVE and simple text persistence used by some ProDOS-style commands.
Error behavior:
Throws "I/O ERROR" when the file cannot be opened for writing.
Overwrites existing content.
Parameters
filename Path to file
content Full file content to write
Exceptions
std::runtime_error with "I/O ERROR" if the file cannot be written
Definition at line 150 of file filesystem.cpp.
Referenced by Interpreter::saveProgram().