MSBasic - Applesoft BASIC Interpreter: src/filesystem.h File Reference
filesystem.h File Reference
DOS/ProDOS-compatible file system operations.
#include <string>
#include <vector>
#include <fstream>
#include <map>
#include <memory>
Classes
struct FileInfo
File or directory metadata.
struct FileHandle
Internal file handle structure.
class FileManager
Singleton managing open file handles for BASIC file I/O.
Enumerations
enum class FileAccessMode { READ , WRITE , APPEND }
File access mode for opening files.
Functions
std::vector< FileInfo > listFiles (const std::string &path=".")
List files in directory (CATALOG)
bool fileExists (const std::string &filename)
Check if file exists.
std::string readTextFile (const std::string &filename)
Read entire text file into string.
void writeTextFile (const std::string &filename, const std::string &content)
Write string to text file.
bool deleteFile (const std::string &filename)
Delete file (DELETE)
bool renameFile (const std::string &oldName, const std::string &newName)
Rename file (RENAME)
std::string getCurrentPrefix ()
Get current working directory prefix (PREFIX)
bool setPrefix (const std::string &path)
Set current working directory prefix (PREFIX)
Detailed Description
DOS/ProDOS-compatible file system operations.
Provides file I/O operations compatible with Apple II DOS and ProDOS commands:
File management (CATALOG, DELETE, RENAME)
Directory operations (PREFIX for working directory)
Sequential file I/O (OPEN, READ, WRITE, CLOSE)
Binary file loading (BLOAD/BSAVE)
File locking/unlocking
The FileManager singleton maintains open file handles and manages file state, providing ProDOS-style file operations while using standard C++ filesystem APIs.
Error handling:
File operations return error codes matching ProDOS conventions
Error codes stored in memory location 222 (accessible via PEEK)
Operations throw RuntimeError for critical failures
File access modes:
READ: Sequential reading from file
WRITE: Sequential writing to file (creates/truncates)
APPEND: Sequential writing starting at end of file
File handles:
Integer handles allocated sequentially starting from 1
Files can be accessed by handle or filename
Multiple files can be open simultaneously
Automatic cleanup on program termination
Definition in file filesystem.h.
Enumeration Type Documentation
FileAccessMode
enum class FileAccessMode strong
File access mode for opening files.
Enumerator
READ
Read-only access.
WRITE
Write access (truncates existing file)
APPEND
Append access (writes at end)
Definition at line 57 of file filesystem.h.
Function Documentation
deleteFile()
bool deleteFile (const std::string & filename)
Delete file (DELETE)
Parameters
filename File to delete
Returns
true if successful
Delete file (DELETE)
Implements the ProDOS-style DELETE behavior used by the interpreter. Returns a boolean rather than throwing so callers can map failures to ProDOS-like error messages.
Parameters
filename Path to file
Returns
true if deletion succeeded, false otherwise
Definition at line 169 of file filesystem.cpp.
fileExists()
bool fileExists (const std::string & filename)
Check if file exists.
Parameters
filename File path
Returns
true if file exists and is accessible
Check if file exists.
Simple existence check by attempting to open the file for reading.
Parameters
filename Path to file
Returns
true if file exists and is readable, false otherwise
Definition at line 109 of file filesystem.cpp.
Referenced by FileManager::lockFile(), and FileManager::unlockFile().
getCurrentPrefix()
std::string getCurrentPrefix ()
Get current working directory prefix (PREFIX)
Returns
Current directory path
Get current working directory prefix (PREFIX)
The interpreter treats the process working directory as the ProDOS PREFIX. This function returns that directory for commands like PREFIX with no argument.
Returns
Current working directory path, or empty string on failure
Definition at line 206 of file filesystem.cpp.
Referenced by Interpreter::showPrefix().
listFiles()
std::vector< FileInfo > listFiles (const std::string & path)
List files in directory (CATALOG)
Parameters
path Directory path (default: current directory)
Returns
Vector of FileInfo structures
List files in directory (CATALOG)
Returns information about all files in the specified directory, excluding "." and ".." entries. Uses platform-specific APIs for optimal performance.
Parameters
path Directory path to list
Returns
Vector of FileInfo structures with name, size, and isDirectory
Definition at line 52 of file filesystem.cpp.
References FileInfo::isDirectory, FileInfo::name, and FileInfo::size.
Referenced by Interpreter::catalog(), and Interpreter::catalogFiles().
readTextFile()
std::string readTextFile (const std::string & filename)
Read entire text file into string.
Parameters
filename File path
Returns
File contents as string
Exceptions
RuntimeError if file cannot be read
Read entire text file into string.
Reads the file contents into memory as a string. Used for loading BASIC program files.
Parameters
filename Path to file
Returns
File contents as string
Exceptions
std::runtime_error with "PATH NOT FOUND ERROR" if file cannot be opened
Definition at line 125 of file filesystem.cpp.
Referenced by Interpreter::chainProgram(), Interpreter::chainProgram(), Interpreter::dashProgram(), Interpreter::execFile(), and Interpreter::loadProgram().
renameFile()
bool renameFile (const std::string & oldName, const std::string & newName)
Rename file (RENAME)
Parameters
oldName Current filename
newName New filename
Returns
true if successful
Rename file (RENAME)
Implements the ProDOS-style RENAME behavior used by the interpreter. Returns a boolean rather than throwing so callers can map failures to ProDOS-like error messages.
Parameters
oldName Existing path
newName New path
Returns
true if rename succeeded, false otherwise
Definition at line 188 of file filesystem.cpp.
setPrefix()
bool setPrefix (const std::string & path)
Set current working directory prefix (PREFIX)
Parameters
path New working directory
Returns
true if successful
Set current working directory prefix (PREFIX)
In ProDOS, PREFIX changes the default directory used to resolve partial pathnames. In this host implementation, we map PREFIX to process working directory.
Parameters
path New working directory path
Returns
true if the directory was changed successfully, false otherwise
Definition at line 224 of file filesystem.cpp.
writeTextFile()
void writeTextFile (const std::string & filename, const std::string & content)
Write string to text file.
Parameters
filename File path
content String to write
Exceptions
RuntimeError if file cannot be written
Write string to text file.
Used by BASIC commands that create or overwrite text files, such as SAVE and simple text persistence used by some ProDOS-style commands.
Error behavior:
Throws "I/O ERROR" when the file cannot be opened for writing.
Overwrites existing content.
Parameters
filename Path to file
content Full file content to write
Exceptions
std::runtime_error with "I/O ERROR" if the file cannot be written
Definition at line 150 of file filesystem.cpp.
Referenced by Interpreter::saveProgram().