MSBasic - Applesoft BASIC Interpreter: src/functions.h File Reference
functions.h File Reference
Applesoft BASIC built-in functions and memory operations.
#include "types.h"
#include <string>
Functions
Value funcSin (const Value &arg)
Sine function (SIN)
Value funcCos (const Value &arg)
Cosine function (COS)
Value funcTan (const Value &arg)
Tangent function (TAN)
Value funcAtn (const Value &arg)
Arctangent function (ATN)
Value funcExp (const Value &arg)
Exponential function (EXP)
Value funcLog (const Value &arg)
Natural logarithm (LOG)
Value funcSqr (const Value &arg)
Square root (SQR)
Value funcAbs (const Value &arg)
Absolute value (ABS)
Value funcInt (const Value &arg)
Integer part (INT)
Value funcSgn (const Value &arg)
Sign function (SGN)
Value funcRnd (const Value &arg)
Random number generator (RND)
Value funcLen (const Value &arg)
String length (LEN)
Value funcVal (const Value &arg)
Convert string to number (VAL)
Value funcAsc (const Value &arg)
ASCII code of first character (ASC)
Value funcChr (const Value &arg)
Character from ASCII code (CHR$)
Value funcLeft (const Value &str, const Value &len)
Left substring (LEFT$)
Value funcRight (const Value &str, const Value &len)
Right substring (RIGHT$)
Value funcMid (const Value &str, const Value &start, const Value &len)
Middle substring (MID$)
Value funcStr (const Value &arg)
Convert number to string (STR$)
Value funcTab (const Value &arg)
Tab to column position (TAB)
Value funcSpc (const Value &arg)
Output spaces (SPC)
Value funcPos (const Value &arg)
Get cursor column position (POS)
Value funcFre (const Value &arg)
Free memory available (FRE)
Value funcPdl (const Value &arg)
Read paddle/joystick position (PDL)
Value funcPeek (const Value &arg)
Read memory byte (PEEK)
Value funcScrn (const Value &x, const Value &y)
Read screen pixel color (SCRN)
Value funcUsr (const Value &addr)
Call machine language routine (USR)
void pokeMemory (int addr, int val)
Write byte to memory (POKE)
int peekMemory (int addr)
Read byte from memory (PEEK)
std::string formatHexAddress (int addr, bool mask16bit=true)
Format memory address as hexadecimal string.
void setMemoryBounds (int lomem, int himem)
Configure memory address bounds for PEEK/POKE/WAIT.
Detailed Description
Applesoft BASIC built-in functions and memory operations.
This file implements all built-in functions from Applesoft BASIC including:
Mathematical functions (SIN, COS, TAN, ATN, EXP, LOG, SQR, ABS, INT, SGN)
Random number generation (RND)
String functions (LEN, VAL, ASC, CHR$, LEFT$, RIGHT$, MID$, STR$)
Output formatting (TAB, SPC, POS)
Memory operations (PEEK, POKE)
System functions (FRE, PDL, SCRN, USR)
Memory Model: The interpreter maintains a simplified memory map matching Applesoft conventions. LOMEM and HIMEM define the valid memory range. Addresses outside this range trigger "MEMORY RANGE ERROR" (matching ILLEGAL QUANTITY ERROR behavior).
Key memory locations:
222 ($DE): ProDOS error code
24 ($18): Horizontal cursor position
Various other system locations for compatibility
Memory bounds are configurable via setMemoryBounds() to support different memory configurations (e.g., 48K, 64K systems).
Definition in file functions.h.
Function Documentation
formatHexAddress()
std::string formatHexAddress (int addr, bool mask16bit)
Format memory address as hexadecimal string.
Parameters
addr Address value
mask16bit If true, display as 16-bit address (default)
Returns
Hex string in format "0xXXXX" or "0xXXXXXXXX"
Used for error messages and debugging output.
Format memory address as hexadecimal string.
Converts an integer address to a hexadecimal string prefixed with '$'. Used for displaying addresses in error messages and CALL statements.
Implementation details:
When mask16bit is true, address is masked to 16 bits (0xFFFF) and formatted with exactly 4 hex digits (e.g., $C000)
When mask16bit is false, address is shown with its natural width (e.g., $186A0 for 100000)
All hex digits are uppercase per Applesoft convention
Parameters
addr Address to format (may be negative for Apple II convention)
mask16bit If true, mask to 16 bits; if false, show full value
Returns
Formatted hex string like "$C000" or "$186A0"
Definition at line 108 of file functions.cpp.
Referenced by Interpreter::callAddress(), peekMemory(), and pokeMemory().
funcAbs()
Value funcAbs (const Value & arg)
Absolute value (ABS)
Parameters
arg Value
Returns
Absolute value of arg
Returns the absolute value using Float40 precision.
Parameters
arg Input value
Returns
|arg| (always non-negative)
Definition at line 501 of file functions.cpp.
References Float40::abs(), Value::getNumber(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcAsc()
Value funcAsc (const Value & arg)
ASCII code of first character (ASC)
Parameters
arg Non-empty string
Returns
ASCII code of first character
Exceptions
RuntimeError if string is empty
ASCII code of first character (ASC)
Returns the ASCII code (0-255) of the first character in a string. This is commonly used to check for special keys or control characters.
The function throws "ILLEGAL QUANTITY ERROR" if the string is empty, matching Applesoft BASIC behavior.
Examples: ASC("A") = 65 ASC("HELLO") = 72 (ASCII code of 'H') ASC("") raises error
Parameters
arg String value (must be non-empty)
Returns
ASCII code of first character (0-255)
Exceptions
std::runtime_error if string is empty
Definition at line 625 of file functions.cpp.
References Value::getString().
Referenced by FunctionCallExpr::evaluate().
funcAtn()
Value funcAtn (const Value & arg)
Arctangent function (ATN)
Parameters
arg Value to compute arctangent of
Returns
Arctangent of arg in radians (-π/2 to π/2)
Computes arctangent using Float40 to match Applesoft precision. Returns value in range -π/2 to π/2.
Parameters
arg Value to compute arctangent of
Returns
Arctangent of arg in radians
Definition at line 445 of file functions.cpp.
References Float40::atn(), Value::getNumber(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcChr()
Value funcChr (const Value & arg)
Character from ASCII code (CHR$)
Parameters
arg ASCII code (0-255)
Returns
Single-character string
Character from ASCII code (CHR$)
Returns a single-character string containing the character with the specified ASCII code. This is the inverse of ASC.
The function validates that the code is in range 0-255 and throws "ILLEGAL QUANTITY ERROR" for out-of-range values.
Commonly used for:
Control characters: CHR$(7) = bell, CHR$(13) = carriage return
Special display effects
Building strings character by character
Examples: CHR$(65) = "A" CHR$(7) = bell character CHR$(13) = carriage return CHR$(256) raises error
Parameters
arg ASCII code (must be 0-255)
Returns
Single-character string
Exceptions
std::runtime_error if code is out of range
Definition at line 657 of file functions.cpp.
References Value::getNumber().
Referenced by FunctionCallExpr::evaluate().
funcCos()
Value funcCos (const Value & arg)
Cosine function (COS)
Parameters
arg Angle in radians
Returns
Cosine of arg
Computes cosine using Float40 to match Applesoft precision.
Parameters
arg Angle in radians
Returns
Cosine of arg
Definition at line 418 of file functions.cpp.
References Float40::cos(), Value::getNumber(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcExp()
Value funcExp (const Value & arg)
Exponential function (EXP)
Parameters
arg Exponent
Returns
e raised to the power of arg
Computes e^arg using Float40 to match Applesoft precision.
Parameters
arg Exponent
Returns
e raised to the power of arg
Definition at line 458 of file functions.cpp.
References Float40::exp(), Value::getNumber(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcFre()
Value funcFre (const Value & arg)
Free memory available (FRE)
Parameters
arg Dummy argument (if 0) or string to trigger garbage collection
Returns
Number of bytes of free memory
In Applesoft, FRE(0) returns free memory. This implementation returns a fixed value for compatibility.
Free memory available (FRE)
In Applesoft BASIC, FRE() returned the number of free bytes available for program and variables. This implementation returns a fixed value for deterministic behavior across platforms.
Usage in BASIC: PRINT FRE(0) (argument ignored, always returns same value)
Note: Original Applesoft would trigger garbage collection when called with a string argument (FRE("")) to reclaim string space.
Parameters
dummy Argument (ignored, kept for compatibility)
Returns
Fixed value 32767.0 representing available memory
Definition at line 944 of file functions.cpp.
Referenced by FunctionCallExpr::evaluate().
funcInt()
Value funcInt (const Value & arg)
Integer part (INT)
Parameters
arg Value
Returns
Largest integer not greater than arg (floor function)
Examples: INT(2.7) = 2, INT(-2.7) = -3
Returns the largest integer less than or equal to arg (floor function). This matches Applesoft BASIC behavior where INT(-2.5) = -3.
Note: This is NOT truncation towards zero. INT always rounds down. Examples: INT(2.5) = 2 INT(-2.5) = -3 (not -2)
Parameters
arg Input value
Returns
Largest integer <= arg
Definition at line 520 of file functions.cpp.
References Value::getNumber(), Float40::intPart(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcLeft()
Value funcLeft (const Value & str, const Value & len)
Left substring (LEFT$)
Parameters
str Source string
len Number of characters (from left)
Returns
Leftmost len characters of str
Left substring (LEFT$)
Returns the leftmost n characters of a string. If n exceeds the string length, returns the entire string. Negative values for n are treated as 0.
Examples: LEFT$("HELLO", 2) = "HE" LEFT$("HELLO", 10) = "HELLO" (n > length) LEFT$("HELLO", 0) = "" LEFT$("HELLO", -1) = "" (negative treated as 0)
Parameters
str String value
len Number of characters to extract
Returns
Leftmost len characters of str
Definition at line 681 of file functions.cpp.
References Value::getNumber(), and Value::getString().
Referenced by FunctionCallExpr::evaluate().
funcLen()
Value funcLen (const Value & arg)
String length (LEN)
Parameters
arg String value
Returns
Number of characters in string
Returns the number of characters in a string.
Parameters
arg String value
Returns
Length of string as a number
Definition at line 575 of file functions.cpp.
References Value::getString().
Referenced by FunctionCallExpr::evaluate().
funcLog()
Value funcLog (const Value & arg)
Natural logarithm (LOG)
Parameters
arg Value (must be positive)
Returns
Natural logarithm of arg
Exceptions
RuntimeError if arg <= 0
Computes natural logarithm using Float40 to match Applesoft precision. Throws error if arg <= 0 (log of non-positive numbers is undefined).
Parameters
arg Value (must be positive)
Returns
Natural logarithm of arg
Exceptions
RuntimeError if arg <= 0
Definition at line 473 of file functions.cpp.
References Value::getNumber(), Float40::log(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcMid()
Value funcMid (const Value & str, const Value & start, const Value & len)
Middle substring (MID$)
Parameters
str Source string
start Starting position (1-based)
len Number of characters to extract
Returns
Substring starting at start with length len
Middle substring (MID$)
Returns a substring starting at position start with length len. In Applesoft BASIC, string positions are 1-indexed (first character is 1).
Behavior details:
start is 1-indexed: MID$("HELLO", 1, 2) = "HE"
If start < 1, treated as 1
If start > string length, returns empty string
If len is negative, treated as 0 (returns empty string)
If len exceeds remaining characters, returns rest of string
Examples: MID$("HELLO", 2, 3) = "ELL" (start at position 2, take 3 chars) MID$("HELLO", 4, 10) = "LO" (only 2 chars remain) MID$("HELLO", 10, 2) = "" (start beyond end) MID$("HELLO", 0, 2) = "HE" (start < 1 treated as 1)
Parameters
str String value
start Starting position (1-indexed)
len Number of characters to extract
Returns
Substring from start position with length len
Definition at line 741 of file functions.cpp.
References Value::getNumber(), and Value::getString().
Referenced by FunctionCallExpr::evaluate().
funcPdl()
Value funcPdl (const Value & arg)
Read paddle/joystick position (PDL)
Parameters
arg Paddle number (0-3)
Returns
Paddle value (0-255)
Returns simulated paddle values for compatibility.
Read paddle/joystick position (PDL)
In Applesoft BASIC, PDL() read analog game paddle controllers connected to the Apple II game port. Values ranged from 0-255 based on paddle position.
Usage in BASIC: X = PDL(0) (read paddle 0) Y = PDL(1) (read paddle 1)
This implementation returns 0 as paddle input is not supported on modern platforms. Programs using PDL() for input should be adapted to use keyboard (GET) or INPUT instead.
Parameters
paddle Paddle number 0-3 (ignored)
Returns
Always 0.0 (paddle not supported)
Definition at line 968 of file functions.cpp.
Referenced by FunctionCallExpr::evaluate().
funcPeek()
Value funcPeek (const Value & arg)
Read memory byte (PEEK)
Parameters
arg Memory address
Returns
Byte value at address (0-255)
Exceptions
RuntimeError if address is outside LOMEM-HIMEM range
Accesses simplified memory model. Key addresses:
222 ($DE): ProDOS error code
24 ($18): Horizontal cursor position
Read memory byte (PEEK)
Reads a single byte from the specified memory address. This is the functional equivalent of the PEEK statement.
Usage in BASIC: A = PEEK(49152) (read keyboard register) X = PEEK(-16384) (negative addresses converted to 16-bit unsigned)
See peekMemory() for details on address handling and special locations.
Parameters
arg Address to read from (converted to integer)
Returns
Byte value at address (0-255)
Definition at line 988 of file functions.cpp.
References Value::getNumber(), and peekMemory().
Referenced by FunctionCallExpr::evaluate().
funcPos()
Value funcPos (const Value & arg)
Get cursor column position (POS)
Parameters
arg Dummy argument (typically 0)
Returns
Current horizontal cursor position (0-based)
Returns current column on terminal. Implementation uses ANSI queries on POSIX systems and Windows console API on Windows.
Get cursor column position (POS)
Returns the current horizontal cursor position (column number) where the next character will be printed. Column numbering starts at 0.
Platform-specific implementation:
Windows: Uses GetConsoleScreenBufferInfo to query cursor position
POSIX: Uses ANSI escape sequence (CPR - Cursor Position Report)
Falls back to 0 if cursor position cannot be determined
The POSIX implementation:
Sends escape sequence "\x1B[6n" to query cursor position
Terminal responds with "\x1B[row;colR"
Parses the response to extract column number
Temporarily sets terminal to raw mode for reliable reading
Times out after 0.1 seconds if no response
Used by PRINT TAB to calculate spacing needed to reach target column.
Parameters
Unused argument (for function signature compatibility)
Returns
Current cursor column (0-based), or 0 if cannot be determined
Definition at line 881 of file functions.cpp.
Referenced by FunctionCallExpr::evaluate().
funcRight()
Value funcRight (const Value & str, const Value & len)
Right substring (RIGHT$)
Parameters
str Source string
len Number of characters (from right)
Returns
Rightmost len characters of str
Right substring (RIGHT$)
Returns the rightmost n characters of a string. If n exceeds the string length, returns the entire string. Negative values for n are treated as 0.
Examples: RIGHT$("HELLO", 2) = "LO" RIGHT$("HELLO", 10) = "HELLO" (n > length) RIGHT$("HELLO", 0) = "" RIGHT$("HELLO", -1) = "" (negative treated as 0)
Parameters
str String value
len Number of characters to extract
Returns
Rightmost len characters of str
Definition at line 707 of file functions.cpp.
References Value::getNumber(), and Value::getString().
Referenced by FunctionCallExpr::evaluate().
funcRnd()
Value funcRnd (const Value & arg)
Random number generator (RND)
Parameters
arg Seed control: <0 reseeds, 0 repeats last, >0 generates new
Returns
Random value in range [0, 1)
RND(1) generates a new random number RND(0) repeats the last generated number RND(negative) reseeds the generator with the seed value
Generates pseudo-random numbers using Float40 implementation for Applesoft-compatible random number sequences.
Behavior based on argument:
RND(1) or RND(positive): Returns random number in range [0, 1)
RND(0): Repeats the last random number generated
RND(negative): Reseeds the generator based on the argument value
This matches Applesoft BASIC's RND behavior exactly, including the ability to reseed for reproducible sequences.
Parameters
arg Control parameter (typically 1 for new random number)
Returns
Random number in [0, 1) or repeated/reseeded value
Definition at line 558 of file functions.cpp.
References Value::getNumber(), and Float40::rnd().
Referenced by FunctionCallExpr::evaluate().
funcScrn()
Value funcScrn (const Value & x, const Value & y)
Read screen pixel color (SCRN)
Parameters
x Horizontal position
y Vertical position
Returns
Color value at position
Returns color of pixel at specified position in current graphics mode.
Read screen pixel color (SCRN)
Returns the color value of the pixel at the specified screen coordinates. Works in both GR (low-res) and HGR (high-res) graphics modes.
Usage in BASIC: C = SCRN(X,Y) (get color at position X,Y) IF SCRN(10,10) = 5 THEN PRINT "WHITE"
Color values:
GR mode: 0-15 (16 colors)
HGR mode: 0-7 (8 colors including black/white)
Parameters
x X coordinate
y Y coordinate
Returns
Color value at specified position
Definition at line 1012 of file functions.cpp.
References Value::getNumber(), graphics(), and Graphics::scrn().
Referenced by FunctionCallExpr::evaluate().
funcSgn()
Value funcSgn (const Value & arg)
Sign function (SGN)
Parameters
arg Value
Returns
-1 if arg < 0, 0 if arg = 0, 1 if arg > 0
Returns the sign of the argument:
Returns -1 if arg < 0
Returns 0 if arg = 0
Returns 1 if arg > 0
Parameters
arg Input value
Returns
-1, 0, or 1 depending on sign of arg
Definition at line 536 of file functions.cpp.
References Value::getNumber(), Float40::sgn(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcSin()
Value funcSin (const Value & arg)
Sine function (SIN)
Parameters
arg Angle in radians
Returns
Sine of arg
Computes sine using Float40 to match Applesoft precision.
Parameters
arg Angle in radians
Returns
Sine of arg
Definition at line 405 of file functions.cpp.
References Value::getNumber(), Float40::sin(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcSpc()
Value funcSpc (const Value & arg)
Output spaces (SPC)
Parameters
arg Number of spaces
Returns
Control value for PRINT statement spacing
Used in PRINT statements: PRINT SPC(5);"TEXT"
Output spaces (SPC)
SPC is used in PRINT statements to output a specific number of spaces. Unlike TAB, SPC always outputs exactly n spaces regardless of cursor position.
Negative values are treated as 0 (no spaces).
Examples: PRINT "A";SPC(5);"B" outputs "A B"
Parameters
arg Number of spaces to generate
Returns
String containing arg spaces
Definition at line 851 of file functions.cpp.
References Value::getNumber().
funcSqr()
Value funcSqr (const Value & arg)
Square root (SQR)
Parameters
arg Value (must be non-negative)
Returns
Square root of arg
Exceptions
RuntimeError if arg < 0
Computes square root using Float40 to match Applesoft precision. Throws error if arg < 0 (square root of negative numbers is undefined).
Parameters
arg Value (must be non-negative)
Returns
Square root of arg
Exceptions
RuntimeError if arg < 0
Definition at line 488 of file functions.cpp.
References Value::getNumber(), Float40::sqr(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcStr()
Value funcStr (const Value & arg)
Convert number to string (STR$)
Parameters
arg Numeric value
Returns
String representation with leading space for positive numbers
Converts a numeric value to its string representation using Float40 formatting to match Applesoft precision and format.
Applesoft convention:
Positive numbers get a leading space: STR$(5) = " 5"
Negative numbers get a minus sign: STR$(-5) = "-5"
This leading space ensures alignment in columnar output
The formatting matches Applesoft's number display format including scientific notation for very large or very small numbers.
Examples: STR$(123) = " 123" STR$(-456) = "-456" STR$(1.5) = " 1.5"
Parameters
arg Numeric value to convert
Returns
String representation with Applesoft formatting
Definition at line 778 of file functions.cpp.
References Value::getNumber(), and Float40::toString().
Referenced by FunctionCallExpr::evaluate().
funcTab()
Value funcTab (const Value & arg)
Tab to column position (TAB)
Parameters
arg Column number (1-based)
Returns
Control value for PRINT statement positioning
Used in PRINT statements: PRINT TAB(10);"TEXT"
Tab to column position (TAB)
TAB is used in PRINT statements to position output at a specific column. This function returns a string of spaces to pad to the specified position.
Note: The actual TAB positioning logic is in the PRINT statement handler, which uses current cursor position. This function just generates spaces.
Negative values are treated as 0 (no spaces).
Parameters
arg Target column position
Returns
String of spaces
Generate spaces to move cursor to specific column (TAB)
TAB is used in PRINT statements to position the cursor at a specific column. Unlike SPC which outputs a fixed number of spaces, TAB calculates the number of spaces needed based on current cursor position.
Behavior:
If target column already passed, does nothing (no spaces)
If target column ahead, outputs spaces to reach it
Negative values treated as 0
This function returns the string of spaces; the PRINT logic handles tracking the current column position.
BASIC Usage: PRINT TAB(10);"HELLO" (start at column 10) PRINT TAB(5);A;TAB(15);B;TAB(25);C (columnar output)
Note: The actual cursor positioning logic is in Interpreter::htab(). This function just creates the spacing string.
Parameters
arg Target column number (0-based)
Returns
String containing spaces (may be empty if n <= 0)
Definition at line 830 of file functions.cpp.
References Value::getNumber().
funcTan()
Value funcTan (const Value & arg)
Tangent function (TAN)
Parameters
arg Angle in radians
Returns
Tangent of arg
Computes tangent using Float40 to match Applesoft precision.
Parameters
arg Angle in radians
Returns
Tangent of arg
Definition at line 431 of file functions.cpp.
References Value::getNumber(), Float40::tan(), and Float40::toDouble().
Referenced by FunctionCallExpr::evaluate().
funcUsr()
Value funcUsr (const Value & addr)
Call machine language routine (USR)
Parameters
addr Address of routine
Returns
Value from routine (always 0 in this implementation)
Simulated for compatibility; does not execute actual machine code.
Call machine language routine (USR)
In Applesoft BASIC, USR() called a machine language subroutine at the specified memory address and returned a result value.
Usage in BASIC: X = USR(2048) (call routine at address 2048)
This implementation is a stub that always returns 0. Machine language calls are not supported as they would be highly platform-specific and potentially unsafe.
Programs using USR() need to be rewritten using native language extensions or external tools for equivalent functionality.
Parameters
addr Address of machine code (ignored)
Returns
Always 0.0 (machine code calls not supported)
Definition at line 1038 of file functions.cpp.
Referenced by FunctionCallExpr::evaluate().
funcVal()
Value funcVal (const Value & arg)
Convert string to number (VAL)
Parameters
arg String containing numeric value
Returns
Numeric value, or 0 if string doesn't start with a number
Parses leading numeric portion of string. VAL("123ABC") = 123
Parses a string and returns its numeric value. This function attempts to interpret the string as a number, following these rules:
Leading whitespace is ignored
Parsing stops at first non-numeric character
Invalid strings return 0.0 (no error)
Examples: VAL("123") = 123 VAL("12.5") = 12.5 VAL(" 45") = 45 VAL("12ABC") = 12 (stops at 'A') VAL("ABC") = 0 (invalid)
Parameters
arg String to convert
Returns
Numeric value, or 0.0 if string is not a valid number
Definition at line 598 of file functions.cpp.
References Value::getString().
Referenced by FunctionCallExpr::evaluate().
peekMemory()
int peekMemory (int addr)
Read byte from memory (PEEK)
Parameters
addr Memory address
Returns
Byte value at address
Exceptions
RuntimeError if address is outside LOMEM-HIMEM range
Helper function for PEEK(). Accesses simplified memory model.
Read byte from memory (PEEK)
Implements the PEEK function which reads a byte from a memory address. Like POKE, this handles special Apple II memory-mapped locations and provides read access to system state and I/O registers.
Address Handling:
Negative addresses are converted to 16-bit unsigned (Apple II convention)
Returns 0 for uninitialized memory locations (sparse storage)
All values returned are in range 0-255 (byte values)
Special Read-Only Addresses:
Keyboard input (0xC000/-16384): Returns last key pressed with high bit set
Button inputs (0xC061-0xC063): Returns button states (stub: always 0)
Special Read-Write Addresses:
All addresses writable by POKE can also be read
System variables, pointers, I/O locations
Implementation Notes:
Keyboard and button inputs are stubs returning default values
Real Apple II hardware would return actual hardware state
Unwritten addresses return 0 (memory map is sparse)
Range Checking: Unlike POKE, PEEK does not throw errors for out-of-range addresses. This matches Applesoft behavior where PEEK can read anywhere but returns undefined values outside LOMEM-HIMEM range.
Parameters
addr Memory address to read from (may be negative)
Returns
Byte value at address (0-255), or 0 if uninitialized
Definition at line 265 of file functions.cpp.
References formatHexAddress().
Referenced by WaitStmt::execute(), funcPeek(), and Interpreter::runFrom().
pokeMemory()
void pokeMemory (int addr, int val)
Write byte to memory (POKE)
Parameters
addr Memory address
val Byte value (0-255)
Exceptions
RuntimeError if address is outside LOMEM-HIMEM range
Modifies simplified memory model. Used for system configuration.
Write byte to memory (POKE)
Implements the POKE statement which writes a byte to a memory address. This function handles the complex address mapping of the Apple II including special system addresses, I/O locations, and memory-mapped hardware.
Address Handling:
Negative addresses are converted to 16-bit unsigned (Apple II convention) Example: POKE -16368,0 becomes POKE 49168,0 (clear keyboard strobe)
Values are masked to 8 bits (0-255) to simulate byte storage
Special Addresses (bypass range checking):
Zero page system variables (0x00-0xFF)
Text window control (0x20-0x25)
Memory pointers: LOMEM (0x69-0x6A), HIMEM (0x73-0x74)
Error handling: ONERR flag (0xD8), line (0xDA-0xDB), error code (0xDE)
Shape table pointer (0xE8-0xE9)
Graphics page pointers (0x67-0x68)
Hi-res page base addresses (0x4000, 0x6000)
Keyboard strobe clear (0xC010/-16368) - acknowledged but no-op
Display control switches (0xC050-0xC057)
Annunciator outputs (0xC058-0xC05F)
Range Checking: Addresses not in the special categories above must fall within LOMEM to HIMEM bounds. Out-of-range addresses throw "MEMORY RANGE ERROR" which matches Applesoft's "ILLEGAL QUANTITY ERROR" for invalid memory access.
Parameters
addr Memory address to write to (may be negative)
val Value to write (will be masked to 0-255)
Exceptions
std::runtime_error If address is outside valid range and not special
Definition at line 152 of file functions.cpp.
References formatHexAddress().
Referenced by Interpreter::callAddress(), PokeStmt::execute(), Interpreter::handleError(), Interpreter::Interpreter(), Interpreter::loadShapeTableFromFile(), Interpreter::printNewline(), Interpreter::runFrom(), Interpreter::setHimem(), Interpreter::setLomem(), and Interpreter::vtab().
setMemoryBounds()
void setMemoryBounds (int lomem, int himem)
Configure memory address bounds for PEEK/POKE/WAIT.
Parameters
lomem Lower memory bound (inclusive)
himem Upper memory bound (inclusive)
Sets valid address range for memory operations. Addresses outside this range trigger "MEMORY RANGE ERROR". Used to simulate different Apple II memory configurations (e.g., 48K, 64K systems).
Default bounds match typical Applesoft configuration.
Configure memory address bounds for PEEK/POKE/WAIT.
Configures the valid memory range for PEEK/POKE operations. This allows the interpreter to simulate different Apple II configurations (48K, 64K, etc.)
Default bounds:
LOMEM: 0x0800 (2048) - Start of BASIC program area on 48K Apple II
HIMEM: 0xC000 (49152) - Start of I/O and ROM on Apple II
The bounds are validated for sanity - LOMEM must be <= HIMEM. If invalid bounds are provided, the existing bounds are retained unchanged.
Special addresses (zero page, I/O) always bypass these checks, so setting restrictive bounds won't prevent access to system locations.
Parameters
lomem Lower memory bound (inclusive)
himem Upper memory bound (inclusive)
Definition at line 384 of file functions.cpp.
Referenced by Interpreter::setHimem(), and Interpreter::setLomem().