MSBasic - Applesoft BASIC Interpreter: src/graphics.h File Reference
graphics.h File Reference
Apple II graphics subsystem (GR, HGR, plotting, shapes)
#include <unordered_map>
#include <vector>
#include <memory>
#include <utility>
Classes
struct GraphicsWindow
Graphics window dimensions and scaling.
struct PlotSample
Single pixel/plot operation record.
class Graphics
Singleton managing graphics state and operations.
Enumerations
enum class GraphicsMode { None , LowRes , HighRes }
Current graphics mode.
Functions
Graphics & graphics ()
Global accessor for Graphics singleton.
Detailed Description
Apple II graphics subsystem (GR, HGR, plotting, shapes)
Implements Applesoft BASIC graphics modes and operations:
Low-resolution (GR): 40×48 with 16 colors
High-resolution (HGR/HGR2): 280×192 with 6 colors + mixed modes
Plotting operations (PLOT, HPLOT)
Shape tables (DRAW, XDRAW with ROTATE/SCALE)
Graphics pipeline:
Commands (HPLOT, DRAW, etc.) update off-screen buffer
Buffer accumulates all operations per frame
renderFrame() sends buffer to GraphicsRenderer for display
The Graphics class is a singleton managing graphics state including current color, drawing position, shape transformation matrix, and the frame buffer of plot samples.
Shape operations:
Shape tables contain vector drawing commands
ROTATE and SCALE affect subsequent DRAW/XDRAW
XDRAW uses XOR mode for animation
This design separates graphics logic from platform-specific rendering, with GraphicsRenderer handling actual window/pixel operations.
Definition in file graphics.h.
Enumeration Type Documentation
GraphicsMode
enum class GraphicsMode strong
Current graphics mode.
Enumerator
None
Text mode.
LowRes
GR: 40×48 low-resolution graphics.
HighRes
HGR/HGR2: 280×192 high-resolution graphics.
Definition at line 44 of file graphics.h.
Function Documentation
graphics()
Graphics & graphics ()
Global accessor for Graphics singleton.
Returns
Reference to Graphics singleton
Definition at line 88 of file graphics.cpp.
References Graphics::instance().
Referenced by PlotStmt::execute(), HlinStmt::execute(), VlinStmt::execute(), HplotStmt::execute(), MoveStmt::execute(), RotateStmt::execute(), ScaleStmt::execute(), ShloadStmt::execute(), DrawStmt::execute(), XdrawStmt::execute(), HgrStmt::execute(), HcolorStmt::execute(), ColorStmt::execute(), GrStmt::execute(), HiresStmt::execute(), funcScrn(), and main().