MSBasic - Applesoft BASIC Interpreter: src/graphics.cpp File Reference
graphics.cpp File Reference
Implementation of Applesoft BASIC graphics operations.
#include "graphics.h"
#include "graphics_config.h"
#include "graphics_renderer.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <sys/ioctl.h>
#include <unistd.h>
Functions
Graphics & graphics ()
Global accessor for Graphics singleton.
Detailed Description
Implementation of Applesoft BASIC graphics operations.
This file implements the Graphics class which provides Apple II graphics functionality including low-resolution (GR) and high-resolution (HGR) modes, plotting, line drawing, and shape table operations.
Graphics architecture:
Graphics singleton maintains graphics state and frame buffer
Commands (HPLOT, DRAW, etc.) add plot operations to frame buffer
renderFrame() sends buffer to GraphicsRenderer for display
Separate logic from rendering allows headless operation
Shape table implementation:
Shapes stored as polyline vectors relative to origin
ROTATE and SCALE affect transformation matrix
DRAW plots shapes, XDRAW uses XOR mode
Default shapes include common geometric forms
The graphics subsystem can operate in three modes:
Full rendering (window displayed with Raylib)
Off-screen only (buffer maintained, no display)
Disabled (graphics commands raise errors)
Definition in file graphics.cpp.
Function Documentation
graphics()
Graphics & graphics ()
Global accessor for Graphics singleton.
Returns
Reference to Graphics singleton
Definition at line 88 of file graphics.cpp.
References Graphics::instance().
Referenced by PlotStmt::execute(), HlinStmt::execute(), VlinStmt::execute(), HplotStmt::execute(), MoveStmt::execute(), RotateStmt::execute(), ScaleStmt::execute(), ShloadStmt::execute(), DrawStmt::execute(), XdrawStmt::execute(), HgrStmt::execute(), HcolorStmt::execute(), ColorStmt::execute(), GrStmt::execute(), HiresStmt::execute(), funcScrn(), and main().