10 REM TEST NO-GRAPHICS MODE
20 REM THIS TEST IS DESIGNED TO FAIL GRACEFULLY
30 REM IT SHOULD PRODUCE AN ERROR WHEN RUN WITH --NO-GRAPHICS
40 REM BUT RUN SUCCESSFULLY IN NORMAL MODE
50 PRINT "TESTING GRAPHICS MODE DETECTION"
60 END
