10 REM TEST SHLOAD WITH BINARY FILE - SIMPLE VERSION
20 PRINT "LOADING SHAPE TABLE FROM FILE"
30 SHLOAD "test_shape.tbl"
40 PRINT "SHAPE TABLE LOADED SUCCESSFULLY"
50 P1 = PEEK(232)
60 P2 = PEEK(233)
70 PRINT "SHAPE TABLE POINTER: ";P1;",";P2
80 PRINT "TEST COMPLETED"
